### ISSUE TITLE
[EPIC] Support Partitioning/Bucket/Sorted order for Gravitino conector

### ISSUE THREAD

**Issue by yuqi1129** [datastrato/gravitino#1155]
### Describe the proposal

Currently, Gravitino doesn't support features like partitioning, bucketing and sorted by table,  we need to support it. 

### Task list

To be added.

**Comment by jerryshao** [comment]
This should be finished, right @yuqi1129 ?

**Comment by yuqi1129** [comment]
> This should be finished, right @yuqi1129 ?

Yeah
