### ISSUE TITLE
[Improvement] Spelling errors about Gravition

### ISSUE THREAD

**Issue by JunpingDu** [datastrato/gravitino#1166]
### What would you like to be improved?

There are still places to use old name - Graviton in document like attached screenshot
<img width="825" alt="截屏2023-12-14 11 49 15" src="https://github.com/datastrato/gravitino/assets/888093/f765a2e8-b917-4e69-9121-b51b50d418b1">

### How should we improve?

replace graviton with gravitino

**Comment by jerryshao** [comment]
@yuqi1129 can you please link PR to this issue, not using "MINOR".

**Comment by yuqi1129** [comment]
OK
