### ISSUE TITLE
[Bug report] Gravitino Web UI details are not shown for Postgres tables

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#1168]
### Describe what's wrong

Detail information is not shown for Postgres tables in the web UI.

### Error message and/or stacktrace

N/A

### How to reproduce

View Postgres table details in web UI using Chrome browser.

### Additional context

<img width="976" alt="image" src="https://github.com/datastrato/gravitino/assets/144504/ffe01a22-2511-4228-bce9-e87b3c4e11b1">

**Comment by ch3yne** [comment]
I can't reproduce the issue at the moment.
The latest code merges global error message display and showing empty data.
Please pull the latest code and check it again.
If still happened, please reopen this issue.
