### ISSUE TITLE
[Improvement] Add how to develop Gravitino trino connector for new developers

### ISSUE THREAD

**Issue by yuqi1129** [datastrato/gravitino#1193]
### What would you like to be improved?

There seem to be no instructions on how to debug and develop the Gravitino Trino connector locally for new developers. We need to add some documents about it.

**Comment by xiacongling** [comment]
Hi, @yuqi1129. I had to compile the connector and then build a docker image for debugging. Is there any easier way to quickly start a development server? Can you share your experience about that?

**Comment by yuqi1129** [comment]
@xiacongling
Well, I'll write a doc on how to debug and create "Trino-connector" locally. Please take a look at this.

**Comment by yuqi1129** [comment]
@xiacongling 
The related PR is here #2446, please take a look, thanks.
