### ISSUE TITLE
[Improvement] Move Trino and Gravitino property key to `common` or `api` module

### ISSUE THREAD

**Issue by yuqi1129** [datastrato/gravitino#1204]
### What would you like to be improved?

Currently,  catalog property keys in `Gravitino` and `Trino connector` are managed separately, which introduces the following problems:
- It's difficult to manage.
- Hard to extend and error-prone.

So, we need to move them into one `common` place and manage them unified.

**Comment by yuqi1129** [comment]
@jerryshao @diqiu50 

I intend to move them to the common module, and `api` module is also OK,  what's your opinion?

**Comment by jerryshao** [comment]
This is already fixed.
