### ISSUE TITLE
[Improvement] Remove Lombok annotation from API module

### ISSUE THREAD

**Issue by mchades** [datastrato/gravitino#1220]
### What would you like to be improved?

Lombok annotation is convenient for developers, but may not be explicit enough for API definition

### How should we improve?

Remove Lombok annotations from the API module, such as `@EqualsAndHashCode` and `@Getter`

**Comment by 724thomas** [comment]
hi, can i pick this up?

**Comment by mchades** [comment]
Of course! Welcome for contributing!
