### ISSUE TITLE
[Improvement] If the connection to Gravitino is lost from the web UI there no indication that something is wrong

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#1225]
### What would you like to be improved?

Data seems to be cached for a short while, then calls silently fail (but can be seen in the developer console in Chrome), and then you'll get "No rows" displayed when clicking on a table or "No tables" displayed when clicking on a catalog.

### How should we improve?

Give the user some indication that the connection to the Gravitino server has been lost.

**Comment by jerryshao** [comment]
Seem like a UI issue, @ch3yne can you please put this on your schedule?
