### ISSUE TITLE
[Improvement] Files missing headers and license

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#1267]
### What would you like to be improved?

These files don't have a header so people don't know hoe they are licensed or if they are 3rd party code:
./integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/mysql/service/MysqlService.java
./integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/postgresql/service/PostgreSqlService.java

I though the rat plugin would catch this?

### How should we improve?

Add correct headers to files

**Comment by brandboat** [comment]
May I take over this issue ? Many Thanks !

**Comment by yuqi1129** [comment]
> May I take over this issue ? Many Thanks !

Sure， please go ahead.

**Comment by qqqttt123** [comment]
> May I take over this issue ? Many Thanks !

Assigned. Thanks @brandboat
