### ISSUE TITLE
[Subtask] Investigate on how non-tabular data is managed

### ISSUE THREAD

**Issue by jerryshao** [datastrato/gravitino#1284]
### Describe the subtask

This task tracks the work of investigating the current products that support managing non-tabular data, and to see how we should design our own one.

### Parent issue

#1241

**Comment by jerryshao** [comment]
I've done investigating on Unity Catalog and OneLake, looks like they're the two products that support managing non-tabular data and relatively mature. I will post the investigation doc here, any comment are welcome.

**Comment by jerryshao** [comment]
https://docs.google.com/document/d/1VmSbBbDyj0-I5XNyuvoExxUQGRiXx8JmvdhawCC-HGk/edit?usp=sharing

**Comment by qqqttt123** [comment]
> https://docs.google.com/document/d/1VmSbBbDyj0-I5XNyuvoExxUQGRiXx8JmvdhawCC-HGk/edit?usp=sharing

Do we need a concept like an external location? Is it in the scope of file catalog?

**Comment by qqqttt123** [comment]
I'm a little curious whether users need version control and file search in the file catalog.
Some systems provide version control, some of them seems popular. 
https://neptune.ai/blog/version-control-for-ml-models
https://github.com/neondatabase/neon

**Comment by coolderli** [comment]
> I'm a little curious whether users need version control and file search in the file catalog. Some systems provide version control, some of them seems popular. https://neptune.ai/blog/version-control-for-ml-models https://github.com/neondatabase/neon

I think the Model Catalog is a special implementation of the File Catalog. Model Catalog may only be applied in AI scenarios, while File Catalog is more universal. If users want to use File Catalog to manage Model versions, they can use other methods such as subdirectories

**Comment by jerryshao** [comment]
> > I'm a little curious whether users need version control and file search in the file catalog. Some systems provide version control, some of them seems popular. https://neptune.ai/blog/version-control-for-ml-models https://github.com/neondatabase/neon
> 
> I think the Model Catalog is a special implementation of the File Catalog. Model Catalog may only be applied in AI scenarios, while File Catalog is more universal. If users want to use File Catalog to manage Model versions, they can use other methods such as subdirectories

From my investigation, model management requires versioning, while non-tabular datasets may not require it. So if we target to a generic file dataset catalog, versioning may not be a required feature.

**Comment by jerryshao** [comment]
Attach the link on how to design this file catalog. https://docs.google.com/document/d/18Hiu0ng-RIHzEJgRH8JUAM9YqyDOJYMvCfYNiGGb7MY/edit?usp=sharing

@coolderli @qqqttt123 please take a review.

Also attached the API design, please take a look https://github.com/datastrato/gravitino/pull/1487

**Comment by jerryshao** [comment]
I'm going to close this issue as the investigation is already done.
