### ISSUE TITLE
[FEATURE] Support Apache Kafka Catalog

### ISSUE THREAD

**Issue by SteNicholas** [datastrato/gravitino#1297]
### Describe the feature

Gravitino supports Apache Iceberg catalog at present. Apache Kafka is an open-source distributed event streaming platform used by thousands of companies for high-performance data pipelines, streaming analytics, data integration, and mission-critical applications. We could support Apache Kafka Catalog to manage Kafka metadata like topic, partition etc.

### Motivation

Apache Kafka is an open-source distributed event streaming platform used by thousands of companies for high-performance data pipelines, streaming analytics, data integration, and mission-critical applications. We could support Apache Kafka Catalog to manage Kafka metadata.

**Comment by SteNicholas** [comment]
@jerryshao, @xunliu, BiliBili needs the Apache Kafka Catalog support to manage the metadata of Kafka like topic, partition etc.

**Comment by jerryshao** [comment]
Thanks @SteNicholas for bringing out this, this is definitely on our radar. I think we can put some of the requirements and initial thoughts here.
