### ISSUE TITLE
[Improvement] Gravitino Web UI only works in Chrome

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#1298]
### What would you like to be improved?

As described in #1150 the Gravitino Web UI only works in Chrome. As it looks like this in planned for the 0.4 release we should document this clearly so users think Gravitino UI doesn't work.

### How should we improve?

Document that Gravitino Web UI only works in Chrome

**Comment by ch3yne** [comment]
I test `Safari`/`Firefox`, running without any errors.
If find any errors again, please reopen this issue.

**Comment by jerryshao** [comment]
Fixed.
