### ISSUE TITLE
[Improvement] gravitino-client needs to support backward compatibility with the server-side response.

### ISSUE THREAD

**Issue by Clearvive** [datastrato/gravitino#1327]
### What would you like to be improved?

gravitino-client needs to support backward compatibility with the server-side response.

### How should we improve?

Add `DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES` to `com.datastrato.gravitino.json.JsonUtils#objectMapper` for parsing parameters.

**Comment by SteNicholas** [comment]
@Clearvive, does `@JsonIgnoreProperties(ignoreUnknown = true)` annotation could support backward compatibility?
