### ISSUE TITLE
[Subtask] Add more badges in README

### ISSUE THREAD

**Issue by qqqttt123** [datastrato/gravitino#1346]
### Describe the subtask

Add more badges in README. You can refer to the pull request https://github.com/apache/incubator-uniffle/pull/219/files

### Parent issue

#1335

**Comment by hiirrxnn** [comment]
I would like to work on this . Can i be assigned this ?

**Comment by qqqttt123** [comment]
> I would like to work on this . Can i be assigned this ?

Thanks @hiirrxnn . Please go ahead.
