### ISSUE TITLE
[Improvement] Support sequence in the configuration

### ISSUE THREAD

**Issue by qqqttt123** [datastrato/gravitino#1357]
### What would you like to be improved?

Spark configuration have implemented to `toSeq` method for configuration options. It's necessary for Gravitino.

### How should we improve?

You can refer to https://github.com/apache/spark/blob/e8dfcd3081abe16b2115bb2944a2b1cb547eca8e/core/src/main/scala/org/apache/spark/internal/config/ConfigBuilder.scala#L126

**Comment by hiirrxnn** [comment]
I would like to work on this. Please tell me what to do exactly !

**Comment by justinmclean** [comment]
@qqqttt123 Can you describe in more detail what is needed here?
