### ISSUE TITLE
[Improvement] add multi PostgreSQL server version to CatalogPostgreSqlIT Integrate test to improve compatibility

### ISSUE THREAD

**Issue by FANNG1** [datastrato/gravitino#1361]
### What would you like to be improved?

`CatalogPostgreSqlIT` testing PostgreSQL with `postgres:13`, we'd better add  12,14,15,16 version

**Comment by qqqttt123** [comment]
Maybe we can split this into two issues.

**Comment by FANNG1** [comment]
> Maybe we can split this into two issues.

ok
