### ISSUE TITLE
[Improvement] Rename the package name "aux" to another as it is a reserved name on 

### ISSUE THREAD

**Issue by shaofengshi** [datastrato/gravitino#1362]
### What would you like to be improved?

When I try to clone this git repository on Windows 10 platform, each time I got such an error:

$ git clone https://github.com/shaofengshi/gravitino
Cloning into 'gravitino'...
remote: Enumerating objects: 15411, done.
remote: Counting objects: 100% (1359/1359), done.
remote: Compressing objects: 100% (473/473), done.
remote: Total 15411 (delta 869), reused 1075 (delta 778), pack-reused 14052
Receiving objects: 100% (15411/15411), 6.96 MiB | 3.40 MiB/s, done.
Resolving deltas: 100% (6129/6129), done.
fatal: cannot create directory at 'core/src/main/java/com/datastrato/gravitino/aux': Invalid argument
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

After doing some search, I found that it is the name "aux" be conflicted with Windows: " It looks like the problem is that 'aux' is a reserved path name on windows, and so the bc/aux directory cannot be cloned to windows".  See here: https://github.com/swcarpentry/DEPRECATED-bc/issues/463

It also can be found in MS websit, "Do not use the following reserved names for the name of a file: CON, PRN, AUX, ...": https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file

### How should we improve?

Rename the package "core/src/main/java/com/datastrato/gravitino/aux" to another name which won't cause the confliction, like "misc".

**Comment by justinmclean** [comment]
Hi @shaofengshi thanks for your contribution and for raising this issue. Currently, we don't support Gravitino on Windows just on macOS and various flavors of Linux, however, we may do so in the future so we'll look into getting this changed.

**Comment by jerryshao** [comment]
@FANNG1 can you please investigate on this to see how to fix this.

**Comment by justinmclean** [comment]
This has already been worked on in another PR

**Comment by FANNG1** [comment]
@shaofengshi , thank you for reporting this, I have proposed #1374  to rename `aux` to `auxiliary`, I doesn't have windows environment, could you help to verify when you are free? 

@justinmclean  #1359  seems not same problems. I try to fix in #1374 .

**Comment by shaofengshi** [comment]
> @shaofengshi , thank you for reporting this, I have proposed #1374 to rename `aux` to `auxiliary`, I doesn't have windows environment, could you help to verify when you are free?
> 
> @justinmclean #1359 seems not same problems. I try to fix in #1374 .

Thank you for the quick action. I will verify it soon, will update you on finish.

**Comment by shaofengshi** [comment]
I merged the PR on a temp branch, and then download the source code as a ZIP on Windows, then it can be unzipped successfully (Before that, this is impossible). So I think this change is good, which is friendly for Windows users to browse the code. Thank you! @FANNG1

**Comment by shaofengshi** [comment]
Verified, I can clone the latest code, no error any more.

**Comment by JunpingDu** [comment]
Great. Thanks to @shaofengshi for reporting the issue and verifying the fix! :)
