### ISSUE TITLE
[Bug report] Tests get stuck on trino-connector:test on macOS

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#1363]
### Describe what's wrong

Tests get stuck on trino-connector tests on macOS. All other tests are complete after 1 minute. The same happens if the mac-docker-connector is running or the docker desktop is not running (with a slightly different output).

### Error message and/or stacktrace

```
------------------ Check Docker environment ---------------------
Docker server status ............................................ [running]
mac-docker-connector status ..................................... [stop]
OrbStack status ................................................. [no]
Run test cases without `gravitino-docker-it` tag ................ [embedded test]
-----------------------------------------------------------------
Tip: Please make sure to use OrbStack or execute the `dev/docker/tools/mac-docker-connector.sh` script before running the integration test on macOS.
<===========--> 90% EXECUTING [10m 25s]
> IDLE
> :trino-connector:test > 0 tests completed
> IDLE
> IDLE
> IDLE
> :trino-connector:test > Executing test com.datastrato...trino.connector.TestG
> IDLE
> IDLE
> IDLE
> IDLE
> IDLE
> IDLE
```

### How to reproduce

The latest version of Gravitio in GitHub run `.\gradlew clean build`.

**Comment by diqiu50** [comment]
@justinmclean Can you reproduce this issue or provide some logs? The log in the directory named `trino-connector/build/test-results`

**Comment by justinmclean** [comment]
Yes I can reproduce the issue. There is no information in the logs just a single output.bin file that's empty (in ./test/binary).

**Comment by yuqi1129** [comment]
```
Docker server status ............................................ [running]
mac-docker-connector status ..................................... [stop]
OrbStack status ................................................. [no]
```

This means that all ITs that depend on Docker will not run, can you confirm which test blocks the build procedure?

**Comment by justinmclean** [comment]
I tried with docker running and not running and got the same result. It's at or before the very first test.

**Comment by yuqi1129** [comment]
Can you show us the stack of stuck processes?
```

# jps | grep GradleWorkerMain |awk '{print $1}'
# jstack {process_id} >> stack.txt
```

**Comment by diqiu50** [comment]
@justinmclean The error doesn't appear to require Docker; it failed in the unit test.  Can you get some logs.

**Comment by justinmclean** [comment]
There are no logs in `trino-connector/build/test-results` other than the blank output.bin file.

**Comment by justinmclean** [comment]
Re stuck processes:

```shell
jps | grep GradleWorkerMain |awk '{print $1}'
2061
2259
1883
justin@Justins-MBP gravitino-playground % jstack 2061 > stack1.txt
justin@Justins-MBP gravitino-playground % jstack 2259 > stack2.txt
2259: Unable to open socket file /var/folders/lz/hv1cpb3d4gscz230l770s8g80000gn/T/.java_pid2259: target process 2259 doesn't respond within 10500ms or HotSpot VM not loaded
justin@Justins-MBP gravitino-playground % jstack 1883 > stack3.txt
1883: Unable to open socket file /var/folders/lz/hv1cpb3d4gscz230l770s8g80000gn/T/.java_pid1883: target process 1883 doesn't respond within 10500ms or HotSpot VM not loaded
```

**Comment by justinmclean** [comment]
[stack1.txt](https://github.com/datastrato/gravitino/files/13856219/stack1.txt)

**Comment by justinmclean** [comment]
This may be a JVM issue or related to how we detect JVMs? Or an OpenJDK vs Amazon Corretto issue?

Having Java Home set to:
`JAVA_HOME=/opt/homebrew/Cellar/openjdk@17/17.0.9/libexec/openjdk.jdk/Contents/Home`

I can reproduce this issue every time.

Having Java home set to:
`export JAVA_HOME=/Library/Java/JavaVirtualMachines/amazon-corretto-8.jdk/Contents/Home`

And all tests will pass.

Having Java home set to:
`export JAVA_HOME=/Library/Java/JavaVirtualMachines/amazon-corretto-11.jdk/Contents/Home`

And the tests also pass.

**Comment by justinmclean** [comment]
Using:
export JAVA_HOME=/Library/Java/JavaVirtualMachines/amazon-corretto-17.jdk/Contents/Home

And the tests also pass.

**Comment by justinmclean** [comment]
Using:
 export JAVA_HOME=/opt/homebrew/Cellar/openjdk@11/11.0.21/libexec/openjdk.jdk/Contents/Home

And the tests also pass.

So it does work on some versions of OpenJDK but not OpenJDK 17. Reinstalling OpenJDK 17 failed to correct the issue.

**Comment by diqiu50** [comment]
Resolved by https://github.com/datastrato/gravitino/issues/1373
