### ISSUE TITLE
[Improvement] add multi MySQL server version to CatalogMysqlIT Integrate test to improve compatibility

### ISSUE THREAD

**Issue by FANNG1** [datastrato/gravitino#1367]
### What would you like to be improved?

CatalogMysqlIT testing MySQL with mysql:8.0, we'd better add mysql:5.7

**Comment by kumarav1nash** [comment]
Hi, I want to take this issue,

 @FANNG1,  can you help run the server, I'm using this cmd  `./bin/gravitino.sh start` but it's not working, am I missing some configuration

**Comment by FANNG1** [comment]
thanks for taking this issue， you can refer https://datastrato.ai/docs/0.3.0/how-to-install/ to how to start GravitinoServer, please  and you could check logs in logs directory, please note that if you deploy Gravitino by `./gradlew compileDistribution`, you should goto `distribution/package` directory to start Gravitino

**Comment by FANNG1** [comment]
Hi, @kumarav1nash this issue is expected to be fixed in 0.4 in this week, so I fixed it.

**Comment by kumarav1nash** [comment]
Thanks @FANNG1, from last two weeks i was occupied with my org release cycle so did not get the chance to work on it.
