### ISSUE TITLE
[Improvement] Check whether a hive table is external when purge table

### ISSUE THREAD

**Issue by FANNG1** [datastrato/gravitino#1390]
### What would you like to be improved?

We shouldn't purge an external hive table in the purge table interface.

### How should we improve?

suggest add a check in `HiveCatalogOperations#purgeTable`

**Comment by coolderli** [comment]
@FANNG1 I submit a patch to fix this: https://github.com/datastrato/gravitino/pull/1418. can you help me review it, thanks.

**Comment by FANNG1** [comment]
> @FANNG1 I submit a patch to fix this: #1418. can you help me review it, thanks.

thanks for your contribution!
