### ISSUE TITLE
[Improvement] Gravitino Web UI update vs edit

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#1396]
### What would you like to be improved?

Generally, you edit something, and once you save the changes it has been updated. The Gravitino Web UI uses the word "update" where "edit" should probably be used.

On the tooltip on the edit icon:
<img width="1512" alt="image" src="https://github.com/datastrato/gravitino/assets/144504/1a695b24-66b3-4628-803e-118bda9411f8">

In the title on metalake dialog:
<img width="1512" alt="image" src="https://github.com/datastrato/gravitino/assets/144504/b5a85124-a036-4da4-85ab-89f9a0d7e553">

(Note the update button is fine).

**Comment by austin362667** [comment]
> (Note the update button is fine).

@ch3yne here
