### ISSUE TITLE
[Improvement] Improve Glossary

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#1416]
### What would you like to be improved?

The glossary (https://github.com/datastrato/gravitino/blob/main/docs/glossary.md) is missing some terms. Look through other documents find out what terms are missing and add them to the glossary.

### How should we improve?

Add more glossary items.

**Comment by hiirrxnn** [comment]
I'd like to work on this . Can i be assigned?

**Comment by yuqi1129** [comment]
> I'd like to work on this . Can i be assigned?

Of course, I would like to assign it to you.

**Comment by hiirrxnn** [comment]
I've made a PR , please review ! Also , I'd like to contribute more to this organization on more complex issues , please enlighten me regarding what tech-stacks should I learn and what resources can I refer to ?
