### ISSUE TITLE
[Bug report] In the Gavitino UI gravitino.identifier is editable

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#1420]
### Describe what's wrong

In the Gavitino UI gravitino.identifier is editable.

<img width="1512" alt="image" src="https://github.com/datastrato/gravitino/assets/144504/204a3324-cee8-45b2-89f9-18258d1d826d">

### Error message and/or stacktrace

No error, but this should probably be a read-only field, as changing it could cause issues.

### How to reproduce

Edit a metalake in the Gravitino Web UI.

**Comment by ch3yne** [comment]
@justinmclean Hi, I'm not sure which of these `properties` should be read-only fields.
Where can I get these fields information ?

**Comment by justinmclean** [comment]
I think the gravitino.identifier is probably the only one, but I'm not the best person to ask.

**Comment by jerryshao** [comment]
Not a problem for now.
