### ISSUE TITLE
[Bug report] Errors in Gravitno Web UI REST calls

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#1421]
### Describe what's wrong

Some REST calls are being made with "null" in the URLs:
<img width="1512" alt="image" src="https://github.com/datastrato/gravitino/assets/144504/ad69ab85-a13f-4918-bdb5-20fdb2724f15">

Note: 
GET http://localhost:8090/api/metalakes/metalake/catalogs/null/schemas/null/tables
GET http://localhost:8090/api/metalakes/metalake/catalogs/null/schemas/null

### Error message and/or stacktrace

See above

### How to reproduce

Open Gravitino Web. UI and browse to a catalog and expand it.

**Comment by ch3yne** [comment]
https://github.com/datastrato/gravitino/issues/1423#issuecomment-1888533089

**Comment by justinmclean** [comment]
Can confirm this has been fixed. Thanks!
