### ISSUE TITLE
[Improvement] Fix link ERROR in doc COMTRIBUTING.md

### ISSUE THREAD

**Issue by SophieTech88** [datastrato/gravitino#1422]
### What would you like to be improved?

In doc of `COMTRIBUTING.md`, there are 3 places of link go to the Error page in Github because the link is not complete.
The link includes [how to build]  in `Development setup` section, and [how to test] in `Testing` section.
![Screen Shot 2024-01-09 at 11 41 17 PM](https://github.com/datastrato/gravitino/assets/141538510/397c2ded-813f-4a11-90ed-42d49b917730)

**Error looks like:**

![Screen Shot 2024-01-09 at 11 42 09 PM](https://github.com/datastrato/gravitino/assets/141538510/9a7d03ed-aead-4993-ad70-65f0f820dd63)

### How should we improve?

Update the link of [how to build] and [how to test].

**Comment by justinmclean** [comment]
Thank you for reporting this, do you want to have a go at fixing it?

**Comment by SophieTech88** [comment]
Yeah. I love to fix it.

**Comment by justinmclean** [comment]
This should be easy to fix, what might be more useful however is writing a link check script. If you want to try that you might be able to repurpose the code in https://github.com/datastrato/gravitino/issues/1424.

**Comment by SophieTech88** [comment]
It is a good idea to check the link in script.

**Comment by justinmclean** [comment]
Yes, often, other similar issues will exist when you find a particular type of issue. You can use any method you like to check the links; you don't have to base the solution on #1424.
