### ISSUE TITLE
[Bug report] REST error in Gravitino Web UI

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#1423]
### Describe what's wrong

Click on a table name gives a rest error with null un URL.

<img width="1512" alt="image" src="https://github.com/datastrato/gravitino/assets/144504/ca017a45-f5ce-45b5-9355-c9e5fceef572">

GET http://localhost:8090/api/metalakes/metalake/catalogs/null/schemas/null/tables/null

### Error message and/or stacktrace

See above

### How to reproduce

Click on a PostgreSQL table name in the Gravitino Web UI.

**Comment by ch3yne** [comment]
This issue fixed under `0.3.1`.
Please change to `0.3.1` and vertify it again.

**Comment by justinmclean** [comment]
Can confirm this has been fixed. Thanks!
