### ISSUE TITLE
[Bug report] Wrong data shown in Gravitino Web UI

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#1425]
### Describe what's wrong

If you click on a table and then click on "No Table" the rows are updated to say "No rows" but the table name in the title stays the same:
<img width="1512" alt="image" src="https://github.com/datastrato/gravitino/assets/144504/05a17e8e-a306-4da0-9649-9bd0916baaa4">

Either click on "No Tables" should do nothing or the title should update to be the correct one.

### Error message and/or stacktrace

No error.

### How to reproduce

Expand the tables in a PostgreSQL catalog, click on a table name, and then click on "No Tables" in a database with no tables.

**Comment by ch3yne** [comment]
Resolved by #1579.
