### ISSUE TITLE
[Improvement] Order of Gravitino nullability and type columns

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#1427]
### What would you like to be improved?

The order of the columns could be changed.

<img width="1512" alt="image" src="https://github.com/datastrato/gravitino/assets/144504/910d5b4b-8b06-410f-9878-59e1378324c2">

### How should we improve?

When creating a table in SQL you use this form:
```SQL
CREATE TABLE table_name
( 
  column1 datatype NOT NULL,
  column2 datatype NULL,
  ...
);

```

It may make more sense in the UI to have the datatype first and then the nullability.

**Comment by hiirrxnn** [comment]
I would like to work on this ! Can i be assigned ? And please let me know what is to be done here precisely

**Comment by ch3yne** [comment]
> I would like to work on this ! Can i be assigned ? And please let me know what is to be done here precisely

Hi @hiirrxnn 
If you want to contribute to this issue, you can assign yourself.
I think you can change the order of the column of `columns`, such as [nullable, type] to [type, nullable].

**Comment by hiirrxnn** [comment]
Could you please tell me which file/files I can find this piece of code to change?

**Comment by ch3yne** [comment]
> Could you please tell me which file/files I can find this piece of code to change?

`web/app/metalakes/TableView.js`
