### ISSUE TITLE
[Improvement] Clarify the definitions and behaviors of interfaces `dropTable` and `purgeTable`

### ISSUE THREAD

**Issue by mchades** [datastrato/gravitino#1436]
### What would you like to be improved?

The described of `dropTable` is:
> Drop a table from the catalog.

and the `purgeTable` is:

> Drop a table from the catalog and completely remove its data.
> If the catalog supports to purge a table, this method should be overridden. The default implementation throws an UnsupportedOperationException.

However, the original intention behind designing these two interfaces was that:
 -  `dropTable` should delete the metadata and data of the table simultaneously. (If a recycle bin is available, the deleted data should go to the recycle bin.)
 - `purgeTable` is intended for catalogs with a recycle bin feature, ensuring that the table data is deleted from the recycle bin after `dropTable`. Otherwise, an `UnsupportedOperationException` should be thrown.

### How should we improve?

Improving the method comment, checking the method call and implementation, and making sure the method's invocation scenario is in line with the semantic meaning of the method.

- [x] #1439
- [x] #1441 
- [x] #1442 
- [x] #1443

**Comment by mchades** [comment]
@jerryshao @yuqi1129 @diqiu50 @FANNG1 @Clearvive @qqqttt123 Do you have any suggestions on this?

**Comment by jerryshao** [comment]
LGTM, let's check it separately.

**Comment by FANNG1** [comment]
Iceberg has different meanings, dropTable is drop metadata while purge table is drop metadata and data.

**Comment by mchades** [comment]
> Iceberg has different meanings, dropTable is drop metadata while purge table is drop metadata and data. @qqqttt123 , do you know any background?

Can you provide some reference for that?

**Comment by FANNG1** [comment]
> > Iceberg has different meanings, dropTable is drop metadata while purge table is drop metadata and data. @qqqttt123 , do you know any background?
> 
> Can you provide some reference for that? @FANNG1

see https://iceberg.apache.org/docs/latest/spark-ddl/#drop-table-purge

```java
  /**
   * Drop a table; optionally delete data and metadata files.
   *
   * <p>If purge is set to true the implementation should delete all data and metadata files.
   *
   * @param identifier a table identifier
   * @param purge if true, delete all data and metadata files in the table
   * @return true if the table was dropped, false if the table did not exist
   */
  boolean dropTable(TableIdentifier identifier, boolean purge);
```

**Comment by qqqttt123** [comment]
> Iceberg has different meanings, dropTable is drop metadata while purge table is drop metadata and data. @qqqttt123 , do you know any background?

I don't think they have different meaning. Iceberg is based on object storage. Object storage may not have their own trash mechnism. Maybe we can treat the snapshot of Iceberg as a trash. So PurgeTable don't  delete data. They can be garbaged.

**Comment by mchades** [comment]
> After that, should the DROP TABLE statement in Trino call the drop table API instead of using purgeTable?

I think most scenarios it is, depending on the semantics of Trino's `Drop TABLE` statement. @diqiu50

**Comment by FANNG1** [comment]
> > Iceberg has different meanings, dropTable is drop metadata while purge table is drop metadata and data. @qqqttt123 , do you know any background?
> 
> I don't think they have different meaning. Iceberg is based on object storage. Object storage may not have their own trash mechnism. Maybe we can treat the snapshot of Iceberg as a trash. So `DropTable` don't delete data. They can be garbaged.

yes, agree.
