### ISSUE TITLE
[Subtask] Ensure the Iceberg catalog implements the correct semantics of `dropTable` and `purgeTable`

### ISSUE THREAD

**Issue by mchades** [datastrato/gravitino#1441]
### Describe the subtask

Ensure the Iceberg catalog implements the correct semantics of `dropTable` and `purgeTable` according to the discussion result in the parent issue.

### Parent issue

#1436

**Comment by FANNG1** [comment]
If we can treat the snapshot of Iceberg as a trash.  drop data and purge data has the correct semantics with Gravitino.
