### ISSUE TITLE
[Bug report] The refresh of the UI will lead to 404

### ISSUE THREAD

**Issue by jerryshao** [datastrato/gravitino#1467]
### Describe what's wrong

In the catalog, shows as below, doing the refresh with cmd+r will lead to 404

<img width="2408" alt="image" src="https://github.com/datastrato/gravitino/assets/850797/833acb25-06b2-4524-ae5b-89297831b875">

After refreshing, the page will be like:

<img width="2228" alt="image" src="https://github.com/datastrato/gravitino/assets/850797/9acdbec3-a52f-462f-a8a8-054b5e14ea1d">

### Error message and/or stacktrace

No.

### How to reproduce

Just refresh the page will reproduce this issue. The Gravitino version is 0.3.1.

**Comment by jerryshao** [comment]
@ch3yne would you please take a look.

**Comment by ch3yne** [comment]
https://github.com/datastrato/gravitino/issues/1494#issuecomment-1892984247

**Comment by yuqi1129** [comment]
<img width="1906" alt="image" src="https://github.com/datastrato/gravitino/assets/15794564/eabd09be-71ca-4663-aed5-8302d56c1593">

@xunliu 
There still exist the issue, please help to check it again?
