### ISSUE TITLE
[Bug report] NOT support load iceberg table with struct column

### ISSUE THREAD

**Issue by TEOTEO520** [datastrato/gravitino#1471]
### Describe what's wrong

if an iceberg have struct column, gravitino can not load it.

### Error message and/or stacktrace

![image](https://github.com/datastrato/gravitino/assets/58762426/295b6029-7c19-4b2c-b555-535e34e0de5b)

### How to reproduce

load iceberg table with struct column

### Additional context

Please assign this for me, I'll fix this bug
<img width="1128" alt="image" src="https://github.com/datastrato/gravitino/assets/58762426/b416e61b-a411-4c36-8500-dec8a866d035">
<img width="1077" alt="image" src="https://github.com/datastrato/gravitino/assets/58762426/aac2242d-d8c7-4750-b0d1-3ee1cfcc3110">

**Comment by FANNG1** [comment]
thanks for reporting this, seems the same problem with #1313
