### ISSUE TITLE
[Bug report] Node.js EventEmitter Memory Leak Warning in Build Process

### ISSUE THREAD

**Issue by Lanznx** [datastrato/gravitino#1473]
### Describe what's wrong

I'm new here, and I was trying to build the project by command `./gradlew clean build -x test`, during the build process of gravitino using Gradle, I'm encountering a series of MaxListenersExceededWarning warnings from Node.js. These warnings suggest a potential memory leak with numerous listeners being added to TLSSocket. This issue has been observed during the execution of the lintOpenAPI task, specifically when using the @redocly/cli package.

Impact: While the build process completes, these warnings are concerning as they may indicate underlying inefficiencies or potential future crashes due to memory leaks.

### Error message and/or stacktrace

> Task :docs:lintOpenAPI
npm WARN exec The following package was not found and will be installed: @redocly/cli@1.5.0
(node:1904) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1904) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(node:1904) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(node:1904) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(node:1904) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(node:1904) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(node:1904) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(node:1904) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(node:1904) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(node:1904) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(node:1904) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(node:1904) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(node:1904) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(node:1904) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(node:1904) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
No configurations were provided -- using built in recommended configuration by default.

### How to reproduce

1. Ensure that Node.js, npm, and Gradle are installed and up to date.
2. Clone the project repository.
3. Run `./gradlew clean build -x test` from the project root directory.
4. Observe the warnings during the :docs:lintOpenAPI task execution.

**Comment by Lanznx** [comment]
After rebuild, the memory leak warning just gone......  it's so weird

**Comment by justinmclean** [comment]
Thanks for reporting the issue however I'm unable to reproduce this. If it does happen again please ask for this issue to be reopened.
