### ISSUE TITLE
[Bug report] Gravitino UI version number is incorrect

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#1478]
### Describe what's wrong

It say 0.3.0 not 0.3.1 in the top right hand corner.
<img width="1512" alt="image" src="https://github.com/datastrato/gravitino/assets/144504/491c3c05-7640-4e37-937a-74ec3a0ebe7b">

### Error message and/or stacktrace

N/A

### How to reproduce

Using the latest main or switching to tag 0.3.1, compile and run the Gravitino UI.

**Comment by justinmclean** [comment]
Also copyright year should now be 2024

**Comment by jerryshao** [comment]
@qqqttt123 Can you please also help to check it, thanks.

**Comment by jerryshao** [comment]
This is my screenshot using tag v0.3.1 to build and run:

<img width="1930" alt="image" src="https://github.com/datastrato/gravitino/assets/850797/7dacf180-7d6b-4434-9bc2-2d0dd279a460">

@justinmclean Can you describe how you reproduce this issue?

> using the latest main or switching to tag 0.3.1

Using main and switching to 0.3.1 should be different.

**Comment by qqqttt123** [comment]
I verified the Docker image. The version is normal.

**Comment by ch3yne** [comment]
@justinmclean [http://localhost:8090/api/version](http://localhost:8090/api/version) What version number did you get from this link?

You can follow the steps to clear the localStorage, then refresh the browser and check it again.
<img width="466" alt="image" src="https://github.com/datastrato/gravitino/assets/17310559/18936803-2c24-4ec0-aaa6-c9dc1712e1a9">

**Comment by justinmclean** [comment]
Still not seeing the correct number:
```shell
 git branch
* (HEAD detached at v0.3.1)
```

Run this:
```shell
./gradlew clean
./gradlew build -x test
./yarn build
./yarn server
```

Are you staying it is getting the version from Gravitino Server via http://localhost:8090/api/version if that is the case then this would be confusing to the user as they would expect the version of the Gravitino UI to be displayed not the version of Gravitino Server.

**Comment by jerryshao** [comment]
There's no Gravitino UI version, the displayed version should be the Grtavitino version, both for server and UI.

**Comment by justinmclean** [comment]
Reporting issues could be confusing, as the UI and server versions may not match.

**Comment by ch3yne** [comment]
The version number displayed in the UI is derived from <http://localhost:8090/api/version>, and the UI's version corresponds to that of Gravitino.

Please provider the following points to facilitate my debugging process.
1. Did you restart server after build the Gravitino?
2. What's your Java version? I can not found `./yarn` in the root project. `yarn build` and `yarn server` started the UI development server, and its port is `3000`.
4. The version number you get from <http://localhost:8090/api/version>.

**Comment by justinmclean** [comment]
I understand the version number is the Gravitino server version, but I'm not sure that is a good idea. Think of these scenarios:
- A user notices we released a new version and tries it out by updating the gravitino repo and can see a new UI with some changes, but the version number and server are older versions because they forgot to update their playground repo.
- A customer wants to test out a new UI version with their existing infrastructure of older Gravition servers. They only want to update the UI, as updating servers takes much more time and effort. They find some bugs in the new UI and report them. They will report the earlier version number they are having issues with, but that is not the correct one, or obvious to us, and we have trouble reproducing the errors.

**Comment by jerryshao** [comment]
I don't think the above scenarios are the typical and common ways for **customers** to use web UI.

1. The current Gravitino UI is bound with backend server, and shipped with the backend server, they're not two different components. We don't recommend **users** to build UI A to test backend B. Like other project, Spark, Flink, etc, they all ship UI with the backend framework. And **users** will never have a chance to use UI and backend server with different versions.
2. We assume that **developers** should understand the codes and know the details, though it is possible to test UI A with backend B, it is a hacky way for developers, developers should think of whether it is a valid scenario for users.
