### ISSUE TITLE
[Improvement] Make it clear what the delete button in the Gravitino UI will do.

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#1486]
### What would you like to be improved?

Change the text on the "Submit" button to "Delete" or even "Delete Metalake"
<img width="506" alt="image" src="https://github.com/datastrato/gravitino/assets/144504/13d6f45b-40dd-4b72-ab05-a77d92a611c5">

### How should we improve?

Make it clear that clicking the button will delete the Metalake.

**Comment by madangopal16072000** [comment]
can i work on this issue.

**Comment by amananand20** [comment]
hey @justinmclean , created PR #1509 for this.
