### ISSUE TITLE
[Bug report] [WEB-UI] Hive catalog icon display problem

### ISSUE THREAD

**Issue by liujinhui1994** [datastrato/gravitino#1492]
### Describe what's wrong

Some of the icons are large and some are small.

### Error message and/or stacktrace

none

### How to reproduce

none

### Additional context

![Uploading b6d38bbf-798e-4fa5-9d85-4b83f570dad4.jpeg…]()

**Comment by jerryshao** [comment]
@liujinhui1994 seems like the uploading image is broken, can you please re-upload the image, thanks.

**Comment by jerryshao** [comment]
@ch3yne can you please look into the issues.
