### ISSUE TITLE
[Bug report] UI: Reboot Gravitino server and refresh web page will get 404

### ISSUE THREAD

**Issue by yuqi1129** [datastrato/gravitino#1494]
### Describe what's wrong

<img width="1609" alt="image" src="https://github.com/datastrato/gravitino/assets/15794564/eebf92f3-201c-446c-be42-1b9603e08c47">

### Error message and/or stacktrace

Please see above

### How to reproduce

1. Create a metalake and a catalog
2. Go to the catalog detail page.
3. Restart Gravitino server
4. Refresh the web page.

**Comment by ch3yne** [comment]
Dup of #1467.
The reason is that the jetty server does not handle other `.html` files except for `index.html`.

**Comment by ch3yne** [comment]
resolved by #1587.
