### ISSUE TITLE
[Bug report] UI: Web Page Jump Problems

### ISSUE THREAD

**Issue by yuqi1129** [datastrato/gravitino#1496]
### Describe what's wrong

![image](https://github.com/datastrato/gravitino/assets/15794564/aa4e7b5d-b0f1-47ec-8910-dbe5783f643f)

### Error message and/or stacktrace

Please see above

### How to reproduce

Please see above

**Comment by ch3yne** [comment]
`←` icon return to metalake page, if you want to redirect to `database` page, click the breadcrumb. 
<img width="172" alt="image" src="https://github.com/datastrato/gravitino/assets/17310559/af85db75-2598-4679-862d-1bb4fc9b484e">

**Comment by yuqi1129** [comment]
Not a bug
