### ISSUE TITLE
[Improvement]  UI: Make catalogs information more clear

### ISSUE THREAD

**Issue by yuqi1129** [datastrato/gravitino#1498]
### What would you like to be improved?

<img width="1596" alt="image" src="https://github.com/datastrato/gravitino/assets/15794564/1f0d3eab-a2e0-474b-b2a8-18bba8a8be0c">
<img width="1548" alt="image" src="https://github.com/datastrato/gravitino/assets/15794564/c24a4870-2f8c-47ae-a4d2-83675be7fba9">

### How should we improve?

We

**Comment by ch3yne** [comment]
Resolved by #1579.
