### ISSUE TITLE
[Subtask] Add Fileset support for fileset catalog

### ISSUE THREAD

**Issue by jerryshao** [datastrato/gravitino#1527]
### Describe the subtask

This issue tracks the work of implementing FilesetCatalog.

### Parent issue

#1241

**Comment by coolderli** [comment]
https://github.com/datastrato/gravitino/issues/1526 had been merged. I want to try contributing to this issue, could you assign it to me?

**Comment by jerryshao** [comment]
Hi @coolderli sorry I'm already working on this to meet 0.4.0 milestone.

We still have several undone issues in #1241 that I haven't created an issue, I think you can work on that if you'd like to, like:

1. Add server-side REST API support for fileset
2.  Add Java client support for fileset
3.  Add E2E integration test for fileset
4.  Add Python Arrow FileSystem implementation for fileset.

**Comment by coolderli** [comment]
@jerryshao Apology for my abruptness. I'd like to take a look at these issues. By the way, when will 0.4.0 be released? I found there are still a lot of issues on the 0.4.0 milestone.

**Comment by jerryshao** [comment]
Hi @coolderli the 0.4.0 version will be shipped out before Spring festival, but we can only merge parts of the functionality of this fileset catalog support, others will be shipped in 0.5.0.
