### ISSUE TITLE
[Bug report] In Gavitino Web UI sometime clicking on Details, Edit or Delete does nothing

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#1538]
### Describe what's wrong

About 1 in 10 clicks on  Details, Edit or Delete icons do nothing.

### Error message and/or stacktrace

N/A

### How to reproduce

Click on Details, Edit or Delete several times until you see a click that doesn't work.

### Additional context

Might be a difference between clicking on a colored pixel in the icon or the background?

**Comment by ch3yne** [comment]
Its a MUI components bug, https://github.com/mui/material-ui/issues/4532
