### ISSUE TITLE
[Bug report] In Gravitino Web UI error occurs when clicking on any table

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#1540]
### Describe what's wrong

Clicking on a table causes an error. Both Hive and PostgreSQL tables cause an error.

### Error message and/or stacktrace

<img width="1512" alt="image" src="https://github.com/datastrato/gravitino/assets/144504/cb9fa2cd-31b6-4b31-a108-86488d3ce873">

### How to reproduce

Start up the playground, click on metalake, expand a catalog, and click on a table.

### Additional context

Was working yesterday, so must be a bug introduced in the last couple of days.

**Comment by ch3yne** [comment]
Could you provide the data from your departments table?
```
curl http://localhost:8090/api/metalakes/metalake_demo/catalogs/catalog_postgres/schemas/hr/tables/departments
```

I guess the issue is that the column type is not in the enums list. I adds a default color when the type is not in the enums. PR: #1542

**Comment by justinmclean** [comment]
It's the playground so it shouldn't contain anything that is not supported.

```shell
{"code":0,"table":{"name":"departments","columns":[{"name":"department_id","type":"integer","nullable":true},{"name":"department_name","type":"varchar(100)","nullable":true}],"properties":{},"audit":{},"distribution":{"strategy":"hash","number":0,"funcArgs":[]},"sortOrders":[],"partitioning":[]}}%    
``` 

But does look like there is an extra % at the end?

**Comment by ch3yne** [comment]
> It's the playground so it shouldn't contain anything that is not supported.
> 
> ```shell
> {"code":0,"table":{"name":"departments","columns":[{"name":"department_id","type":"integer","nullable":true},{"name":"department_name","type":"varchar(100)","nullable":true}],"properties":{},"audit":{},"distribution":{"strategy":"hash","number":0,"funcArgs":[]},"sortOrders":[],"partitioning":[]}}%    
> ```
> 
> But does look like there is an extra % at the end? Or perhaps the newer distribution content?

This data is already useful enough for me, thank you!
BTW, the `%` symbol was generated by terminal, means that the response data follows immediately after the command prompt. Its not a problem.
