### ISSUE TITLE
[Bug report] [UI]The next page button is insensitive.

### ISSUE THREAD

**Issue by danhuawang** [datastrato/gravitino#1543]
### Describe what's wrong

<img width="431" alt="截屏2024-01-17 14 14 24" src="https://github.com/datastrato/gravitino/assets/154112360/01c72c1d-29e5-4181-96b5-0aaf39a03b3e">

### Error message and/or stacktrace

NA

### How to reproduce

create more data for list

**Comment by ch3yne** [comment]
Dup of #1537
