### ISSUE TITLE
[Bug report] [UI]Missing scroll bar

### ISSUE THREAD

**Issue by danhuawang** [datastrato/gravitino#1545]
### Describe what's wrong

<img width="1507" alt="截屏2024-01-17 14 24 24" src="https://github.com/datastrato/gravitino/assets/154112360/10f54581-eed0-49a1-9f97-d3b11912730e">

### Error message and/or stacktrace

NA

### How to reproduce

prepare data for list view

**Comment by ch3yne** [comment]
Dup of #1537
