### ISSUE TITLE
[Improvement] The API message should display slightly more complete content

### ISSUE THREAD

**Issue by ch3yne** [datastrato/gravitino#1551]
### What would you like to be improved?

The API message only shows java class name on the `message` field, more info shows in `stack` field and the main information is on the first line.
The web UI only show text from the `message` field.

### How should we improve?

I think we should show more complete content.
option 1: showing message plus the first line of`stack` in the web UI.
option 2: join more complete content on the `message` field in the backend.

**Comment by jerryshao** [comment]
I will handle this.
