### ISSUE TITLE
[Subtask] [spark-connector] support more spark data types

### ISSUE THREAD

**Issue by FANNG1** [datastrato/gravitino#1552]
### Describe the subtask

After #1529 , we just support String and integer types in spark,  we should support more spark types:
1. `AtomicType`, besides String and Integer
2. `ArrayType`, `MapType`, `StructType`

`NullType`, `ObjectType`, `UserDefinedType`, `CalenderIntervalType` is not supported by gravitino,  will be supported latter if nesseseray.

### Parent issue

#1227

**Comment by mchades** [comment]
`NullType` is already supported. 
https://github.com/datastrato/gravitino/blob/7cedbd6cd9f9c6a2808b53329bd12360f26076d8/api/src/main/java/com/datastrato/gravitino/rel/types/Types.java#L15-L16

**Comment by FANNG1** [comment]
> `NullType` is already supported.
> 
> https://github.com/datastrato/gravitino/blob/7cedbd6cd9f9c6a2808b53329bd12360f26076d8/api/src/main/java/com/datastrato/gravitino/rel/types/Types.java#L15-L16

cool
