### ISSUE TITLE
[Bug report] Edit one metalake , then create a new metalake, the edited metalake info shouldn't be auto filled.

### ISSUE THREAD

**Issue by danhuawang** [datastrato/gravitino#1559]
### Describe what's wrong

<img width="592" alt="截屏2024-01-17 16 41 35" src="https://github.com/datastrato/gravitino/assets/154112360/4a67055a-c5e0-4fa0-9604-5498877559e9">
<img width="583" alt="截屏2024-01-17 16 35 29" src="https://github.com/datastrato/gravitino/assets/154112360/d6395337-f1a4-4194-b167-5adfc660196e">

### Error message and/or stacktrace

NA

### How to reproduce

1.select one metalake to edit
2.click "create metalake" button

**Comment by ch3yne** [comment]
@danhuawang 
I can't reappear this bug.
If it still happens, please reopen this issue.
