### ISSUE TITLE
[Subtask] [spark-connector] support table DDL operations

### ISSUE THREAD

**Issue by FANNG1** [datastrato/gravitino#1565]
### Describe the subtask

create&load&drop table are supported, we should also support:
1. list table
2. alter table

### Parent issue

#1227

**Comment by hiirrxnn** [comment]
I would like to work on this . Please tell me precisely what is to be done here

**Comment by FANNG1** [comment]
this issue could be started after #1521 related PR is merged in one week,  #1521 is good start point to know what is a spark-connector.

**Comment by hiirrxnn** [comment]
Alright , I will get started once #1521 is merged .

**Comment by FANNG1** [comment]
@hiirrxnn , spark table operation is supportted in #2133,   do you still want to work on this?

**Comment by hiirrxnn** [comment]
I will make a draft pr and you can tell me if it's correct or not.

**Comment by FANNG1** [comment]
more table interface are implemented, suggest to support  `UpdateColumnPosition` or `UpdateColumnType` in AlterTable. you could refer #2456 #2458 . please create corresponding issues if you want to take it to notice other you're working on it.
