### ISSUE TITLE
[Subtask] [spark-connector] support Iceberg catalog

### ISSUE THREAD

**Issue by FANNG1** [datastrato/gravitino#1571]
### Describe the subtask

support DDL and DML operations to Iceberg catalog

### Parent issue

#1227

**Comment by caican00** [comment]
Hi @FANNG1 May i ask whether i can work on it or not?

**Comment by FANNG1** [comment]
sure

**Comment by FANNG1** [comment]
@caican00 , 0.5.1 is planed to be code freeze at 5.27, Are any features about Iceberg catalog support to be done?  Could it meet the time requirement?

**Comment by caican00** [comment]
> @caican00 , 0.5.1 is planed to be code freeze at 5.27, Are any features about Iceberg catalog support to be done? Could it meet the time requirement?

https://github.com/datastrato/gravitino/pull/3266
https://github.com/datastrato/gravitino/pull/3481

@FANNG1 please help review these two PRs.
And support for Iceberg properties has not yet started, but it does not affect the 0.5.1 release.
