### ISSUE TITLE
[Subtask] [spark-connector] support multi spark&scala version 

### ISSUE THREAD

**Issue by FANNG1** [datastrato/gravitino#1574]
### Describe the subtask

support spark 2.4 and scala 2.13 for now,  we should support multi spark and scala versions

- [x] #3007 
- [x] #3305 
- [x] #3330 
- [x] #3320 
- [x] #3554
- [x] #3555 

### Parent issue

#1227

**Comment by caican00** [comment]
Hi @FANNG1 will we consider support for spark3.1 and spark3.3 latter? Currently the main versions of spark in XIAOMI are spark3.1 and spark3.3.

**Comment by FANNG1** [comment]
yes, but we planned to do this after the basic feature of the spark-connector is set up. If you're interested, you could do some work.

**Comment by caican00** [comment]
> yes, but we planned to do this after the basic feature of the spark-connector is set up. If you're interested, you could do some work.

It sounds reasonable. Let's set up the basic feature first and if there are version compatibility issues, we can build on a lower version first.
