### ISSUE TITLE
[Subtask] Add user doc for column default value

### ISSUE THREAD

**Issue by mchades** [datastrato/gravitino#1590]
### Describe the subtask

Add user doc for column default value

### Parent issue

#896

**Comment by hiirrxnn** [comment]
Please tell me precisely what is to be done here and I will get started on it .

**Comment by mchades** [comment]
> Please tell me precisely what is to be done here and I will get started on it .

Thank you for volunteering!

The document with missing values depends on the expression document, because the default values of the column are represented by expressions. Did you write the expression document first?

**Comment by hiirrxnn** [comment]
Could you please guide me on how to document the expression ?

**Comment by mchades** [comment]
Of course! 
But this may require some prior knowledge. Are you familiar with Gravitino Expression or SQL Expression? If you are already familiar with those, we need a document named `gravitino-expression-system.md`. In this document, present the definition, implementation, and invocation method of the `com.datastrato.gravitino.rel.expressions.Expression` interface from the user's perspective. Provide corresponding REST and Java use cases, as well as equivalent SQL semantics. Finally, add a document link to any mentions of Expression in other documents.

I understand that this may be challenging for non-interface developers. If you feel the same way, I still have more accessible issues to choose from, such as #1640

**Comment by hiirrxnn** [comment]
Since I have no prior experience in Gravitino/SQL expression , I feel I am better suited for #1640 . Also , please let me know which topics/tech-stacks to be studied so I can solve a problem like this one , in the future.

**Comment by mchades** [comment]
> Since I have no prior experience in Gravitino/SQL expression , I feel I am better suited for #1640 . Also , please let me know which topics/tech-stacks to be studied so I can solve a problem like this one , in the future.

Any one of the Gravitino catalog engines is good for study, such as Iceberg, Hive, MySQL, PostgreSQL
