### ISSUE TITLE
[Bug report] List schemas in Hive catalogs meets error

### ISSUE THREAD

**Issue by yuqi1129** [datastrato/gravitino#1605]
### Describe what's wrong

<img width="1947" alt="image" src="https://github.com/datastrato/gravitino/assets/15794564/fe3173d7-b7df-425c-b244-18e662da9f24">

Why I click `hive_catalog` and the error information is mysql_catalog related?

```
➜  [/Users/yuqi] curl -X GET http://localhost:8090/api/metalakes/test/catalogs/mysql_catalog
{"code":0,"catalog":{"name":"mysql_catalog","type":"relational","provider":"jdbc-mysql","comment":"comment","properties":{"jdbc-url":"jdbc:mysql://127.0.0.1:3306?useSSL=false&allowPublicKeyRetrieval=true","jdbc-user":"root","jdbc-password":"123456","jdbc-driver":"com.mysql.cj.jdbc.Driver"},"audit":{"creator":"anonymous","createTime":"2024-01-18T13:45:31.430765Z"}}}%
➜  [/Users/yuqi] curl -X GET http://localhost:8090/api/metalakes/test/catalogs/hive_catalog
{"code":0,"catalog":{"name":"hive_catalog","type":"relational","provider":"hive","comment":"comment","properties":{"gravitino.bypass.hive.metastore.client.capability.check":"false","metastore.uris":"thrift://localhost:9083"},"audit":{"creator":"anonymous","createTime":"2024-01-18T13:45:21.052546Z"}}}%
```

### Error message and/or stacktrace

Please see about

### How to reproduce

Please see about

**Comment by ch3yne** [comment]
This should be the error that occurred when clicking to expand `mysql_catalog`, but because the request took some time, the results were only obtained when switching to another page.

I will add a loading state when requesting data to avoid this kind of inconvenience.
