### ISSUE TITLE
[Bug report] When failed to get table columns, UI mistakenly fill the content

### ISSUE THREAD

**Issue by jerryshao** [datastrato/gravitino#1619]
### Describe what's wrong

<img width="1452" alt="image" src="https://github.com/datastrato/gravitino/assets/850797/9da60925-bea9-4114-9a8b-bc9dbe80223a">

if the "column_priv" is failed to get, the right panel has wrong content.

### Error message and/or stacktrace

No.

### How to reproduce

N/A

**Comment by ch3yne** [comment]
Dup of #1605.
