### ISSUE TITLE
[Bug report] "connect timed out" error when running integration test

### ISSUE THREAD

**Issue by puchengy** [datastrato/gravitino#1621]
### Describe what's wrong

As title.

### Error message and/or stacktrace

```
java.lang.RuntimeException: Failed to connect to Hive Metastore
...
Caused by: java.net.ConnectException: Operation timed out (Connection timed out)
...
```
or 
```
org.apache.iceberg.exceptions.RESTException: Error occurred while processing GET request
...
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
...
```

See all failure reports: [reports.zip](https://github.com/datastrato/gravitino/files/14002118/reports.zip)

### How to reproduce

On MacOS, use main branch, open 1 terminal to run `dev/docker/tools/mac-docker-connector.sh` and the other terminal to run `./gradlew clean build`.

**Comment by justinmclean** [comment]
Running the integration tests I was unable to reproduce this. Please give us more details on the macOS version, CPU, amount of memory, and the Java version you are using.

**Comment by puchengy** [comment]
@justinmclean 
```
Build time:   2023-06-30 18:02:30 UTC
Revision:     5f4a070a62a31a17438ac998c2b849f4f6892877

Kotlin:       1.8.20
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          1.8.0_362 (Amazon.com Inc. 25.362-b08)
OS:           Mac OS X 14.2.1 aarch64
```
I think it might be something related to docker setup, as the read time out indicates a network issue.

**Comment by justinmclean** [comment]
I can't tell from the information provided, but it might be possible that something is running on one of the ports used for the integration test.

**Comment by puchengy** [comment]
@justinmclean The issue is gone after upgraded to latest docker software.
