### ISSUE TITLE
[Bug report] pnpm build fails with error 

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#1623]
### Describe what's wrong

`pnpm build` fails with error on latest main.

### Error message and/or stacktrace

```shell
.next/types/app/(home)/page.ts:2:24
Type error: Cannot find module '../../../../app/(home)/page.js' or its corresponding type declarations.

  1 | // File: /Users/justin/gravitino/web/app/(home)/page.js
> 2 | import * as entry from '../../../../app/(home)/page.js'
    |                        ^
  3 | import type { ResolvingMetadata, ResolvingViewport } from 'next/dist/lib/metadata/types/metadata-interface.js'
  4 |
  5 | type TEntry = typeof import('../../../../app/(home)/page.js')
 ELIFECYCLE  Command failed with exit code 1.
justin@Justins-MBP web % 
```

### How to reproduce

Try to build Gravitino Web UI

**Comment by justinmclean** [comment]
I did do this, so that's not the issue:
```shell
pnpm install
Lockfile is up to date, resolution step is skipped
Already up to date
Done in 508ms
```

**Comment by justinmclean** [comment]
It seems that doing a top-level clean build fixes this issue.

**Comment by ch3yne** [comment]
using `pnpm dist` instead of `pnpm build`.

**Comment by justinmclean** [comment]
`pnpm dist` doesn't start the server on port 3000

**Comment by justinmclean** [comment]
I'm not sure if `pnpm dist` is correct as I get `500:Internal Error` in the Gravitino Web UI

**Comment by ch3yne** [comment]
> I'm not sure if `pnpm dist` is correct as I get `500:Internal Error` in the Gravitino Web UI

Can you paste some pictures or error outputs about this?

**Comment by justinmclean** [comment]
Sure:
<img width="1512" alt="image" src="https://github.com/datastrato/gravitino/assets/144504/96813123-8082-42c1-9fd9-0f2822a78e0f">
<img width="570" alt="image" src="https://github.com/datastrato/gravitino/assets/144504/35626697-2bbc-48fc-865e-6281d62e165e">
<img width="1512" alt="image" src="https://github.com/datastrato/gravitino/assets/144504/0e7d1ac9-3ab7-42d6-9bab-b5009459088b">

**Comment by justinmclean** [comment]
Looks like its using port 3000 rather than 8090 to connect to Gavitino?

**Comment by ch3yne** [comment]
> Looks like its using port 3000 rather than 8090 to connect to Gavitino?

If you need to make changes to the web, you'll have to start the development environment with debugging enabled, and the port to use is 3000.
If you're just using it, you don't need to start the development server, you can just access it using port 8090.

**Comment by justinmclean** [comment]
I also tried with `pnpm dev` and some error occurs.

**Comment by ch3yne** [comment]
Can I ask what `Ollama` in the browser title is? Will it conflict with other services?

**Comment by justinmclean** [comment]
It runs on port 3000, but it been turned off. If it is running the Webb UI starts on port 3001. I think the icon is just cached.
