### ISSUE TITLE
[Subtask] Replace `ColumnDTO` with `ColumnImpl` in test cases

### ISSUE THREAD

**Issue by mchades** [datastrato/gravitino#1635]
### Describe the subtask

Replace `ColumnDTO` with `ColumnImpl` in test cases

### Parent issue

#1292

**Comment by zivali** [comment]
Hi @mchades, 
I see in some test cases, the `ColumnDTO` object will be used to create [TableDTO](https://github.com/datastrato/gravitino/blob/main/common/src/main/java/com/datastrato/gravitino/dto/rel/TableDTO.java#L63) and [TableCreateRequest](https://github.com/datastrato/gravitino/blob/main/common/src/main/java/com/datastrato/gravitino/dto/requests/TableCreateRequest.java#L83).
e.g. in
https://github.com/datastrato/gravitino/blob/main/clients/client-java/src/test/java/com/datastrato/gravitino/client/TestRelationalTable.java#L82-L109

For `TableDTO` and `TableCreateRequest`, should they continue to use DTO object or switch to use `ColumnImpl` as well?
I see in https://github.com/datastrato/gravitino/commit/ae0054f3368be8958e8482a06fa1ba69b982e270 you stayed with `ColumnDTO` and added a toDTOs method. So I suppose all other test cases should do the same?

**Comment by mchades** [comment]
Hi @zivali , below is my supplement to this issue which may answer the question you mentioned above
The criterion for determining whether to use `ColumnDTO` is based on: 

**whether the constructed `Column` object is needed for Java client calls to the Gravitino API.**

If it is required for this purpose, then `ColumnImpl` should be used; otherwise, `ColumnDTO` can be utilized.

In the examples you provided, `Column` objects are used to mock the server response containing `ColumnDTO`, which is acceptable.
https://github.com/datastrato/gravitino/blob/ec2fd57ce77d386e1eed0b7855ef6b16fef691ac/clients/client-java/src/test/java/com/datastrato/gravitino/client/TestRelationalTable.java#L82-L109

But the code immediately following it is faulty:
https://github.com/datastrato/gravitino/blob/ec2fd57ce77d386e1eed0b7855ef6b16fef691ac/clients/client-java/src/test/java/com/datastrato/gravitino/client/TestRelationalTable.java#L113-L123

As the client is invoking the `createTable` API of Gravitino, `ColumnDTO` should not be passed as a parameter. We can modify the code as follows to align with our standards:
```java
    partitionedTable =
        catalog
            .asTableCatalog()
            .createTable(
                tableId,
                fromDTOs(columns), // client should use ColumnImpl to create Table, here use fromDTOs just for code reuse
                "comment",
                Collections.emptyMap(),
                partitioning,
                DistributionDTO.NONE,
                SortOrderDTO.EMPTY_SORT);
```
