### ISSUE TITLE
[Improvement] Standardize the invocation method for the Builder pattern

### ISSUE THREAD

**Issue by mchades** [datastrato/gravitino#1640]
### What would you like to be improved?

There are two invocations for Builder pattern in the project currently:

case one:
```java
ColumnDTO column =
        ColumnDTO.builder()
            .withName(name)
            .withDataType(type)
            .withComment(comment)
            .withNullable(false)
            .build();
```

case two:
```java
SchemaDTO schema =
        new SchemaDTO.Builder()
            .withName("SchemaA")
            .withComment("comment")
            .withAudit(audit)
            .build();
```

The first provides fluent interfaces that make the code cleaner and more readable

### How should we improve?

Standardize the invocation method to the first format.

Following are some classes that need to be modified. If you are interested in this, please create a new subtask issue before starting work.

- [x] AuditInfo.java (#1730 )
- [ ] BaseColumnExtension.java
- [ ] CatalogDTO.java
- [x] CatalogEntity.java #2023 
- [ ] DistributionDTO.java
- [ ] FuncExpressionDTO.java
- [ ] HiveColumn.java
- [ ] HiveSchema.java
- [ ] HiveTable.java
- [ ] IcebergSchema.java
- [ ] LiteralDTO.java
- [ ] MetalakeDTO.java
- [ ] SchemaDTO.java
- [ ] SortOrderDTO.java
- [ ] TableDTO.java

**Comment by hiirrxnn** [comment]
in which file/files does this have to be updated?

**Comment by mchades** [comment]
> in which file/files does this have to be updated?

There are many files that need to be updated. You can find them by searching for `.build()` throughout the text, and then locate the corresponding class file using the code `new xxx.Builder()`. After you updated the class file, you may find the build failed then you just need to modify the invocation according to the error message

There are many files that need to be updated. You can:
1. Search for `.build()` throughout the text and 
2. Identify the results that use `new xxx.Builder()`
3. Once you have found the corresponding class file (usually xxx.java), update it. (such as `AuditInfo.java`, `SchemaDTO.java` etc.)
4. You may encounter build failures after updating the class files. In that case, simply modify the call according to the error message
5. Just make sure the CI passed in Github

Tips: You can split this task into multiple PRs. Once the first PR is merged, you will know how to proceed. However, ensure that each PR passes the CI. Enjoy the coding :)

**Comment by hiirrxnn** [comment]
<img width="824" alt="Screenshot 2024-01-23 at 7 08 42 PM" src="https://github.com/datastrato/gravitino/assets/142747922/2b36b344-77b3-4771-8c23-37cfca8e21c7">
For example , i have found an instance of the use of xxx.Builder() , but when I visit class of AudioInfo or Its superclasses/interfaces , I can't find an instance of SchemaDTO , please guide me regarding what to update in this instance so I get an overall idea.

**Comment by mchades** [comment]
You can take a look at this draft PR #1663

**Comment by mchades** [comment]
> in which file/files does this have to be updated?

- [ ] AuditInfo.java
- [ ] BaseColumnExtension.java
- [ ] CatalogDTO.java
- [ ] CatalogEntity.java
- [ ] DistributionDTO.java
- [ ] FuncExpressionDTO.java
- [ ] HiveColumn.java
- [ ] HiveSchema.java
- [ ] HiveTable.java
- [ ] IcebergSchema.java
- [ ] LiteralDTO.java
- [ ] MetalakeDTO.java
- [ ] SchemaDTO.java
- [ ] SortOrderDTO.java
- [ ] TableDTO.java

**Comment by coolderli** [comment]
I think it's great.
```
ColumnDTO column =
        ColumnDTO.builder()
            .withName(name)
            .withDataType(type)
            .withComment(comment)
            .withNullable(false)
            .build();
```

In the fist case, if we use the lombok @Builder to generate it. It will have no prefix `with` until we add `setterPrefix='with'`

@mchades Do you have any tendencies？ Or why do we just use the Lombok @Builder to generate it?

```
ColumnDTO column =
        ColumnDTO.builder()
            .name(name)
            .dataType(type)
            .comment(comment)
            .nullable(false)
            .build();
```

**Comment by mchades** [comment]
> I think it's great.
> 
> ```
> ColumnDTO column =
>         ColumnDTO.builder()
>             .withName(name)
>             .withDataType(type)
>             .withComment(comment)
>             .withNullable(false)
>             .build();
> ```
> 
> In the fist case, if we use the lombok @builder to generate it. It will have no prefix `with` until we add `setterPrefix='with'`
> 
> @mchades Do you have any tendencies？ Or why do we just use the Lombok @builder to generate it?
> 
> ```
> ColumnDTO column =
>         ColumnDTO.builder()
>             .name(name)
>             .dataType(type)
>             .comment(comment)
>             .nullable(false)
>             .build();
> ```

I prefer using `withXxx()` because it aligns with the existing Builder pattern used in our project.

**Comment by ajayl83** [comment]
@mchades which DTO's i can pick up.

**Comment by ajayl83** [comment]
@mchades i am picking up CatalogDTO

**Comment by mchades** [comment]
> @mchades i am picking up CatalogDTO

Sorry, it seems #2560 already resolved all issues. I think you can check out the other GOOD FIRST ISSUES, thank you so much for your enthusiasm! @ajayl83

**Comment by yuqi1129** [comment]
@charliecheng630 
Can you leave a comment here, I'm handling the release work, as this is your credit, but due to GitHub restrictions, I can't assign it to you.
