### ISSUE TITLE
[Bug report] Gravitono clicking on table icon doesn't switch to that table.

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#1641]
### Describe what's wrong

Clicking on a table icon does nothing other than grey out the table row.
<img width="1512" alt="image" src="https://github.com/datastrato/gravitino/assets/144504/b26a4d1c-f8e4-484a-82d8-0740ea23956c">

### Error message and/or stacktrace

N/A

### How to reproduce

Run Gravitino and expand a catalog, click on the table icon in the table rows.

**Comment by justinmclean** [comment]
The same happens when clicking on metalake icons and catalog icons.

**Comment by ch3yne** [comment]
It's an issue with the click area of the tree node.

Due to the issue of nested html nodes, I will first change the mouse hover state to a more user-friendly prompt, and only change it to a hand icon when it is clickable.
