### ISSUE TITLE
[Bug report] Gravitino Web UI Catalog show no tables when it does have them

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#1642]
### Describe what's wrong

Sometimes tables do not show when expanding a catalog.

<img width="1512" alt="image" src="https://github.com/datastrato/gravitino/assets/144504/5d950a9c-4594-4cb2-b751-ae8c31abf49e">

### Error message and/or stacktrace

N/A

### How to reproduce

Click on expand/collapse a few times in a row on a schema.

**Comment by ch3yne** [comment]
I tested based on the description, but the error did not occur.
#1657 This PR optimized the expand and collapse of the treeview.
Please pull the latest code and test again.
If the issue still exists, please open this issue.
