### ISSUE TITLE
[Bug report] The page is not update in time when click another table

### ISSUE THREAD

**Issue by yuqi1129** [datastrato/gravitino#1644]
### Describe what's wrong

<img width="1938" alt="image" src="https://github.com/datastrato/gravitino/assets/15794564/8416e9ca-8b6c-4555-8573-3901d8c22e4b">

### Error message and/or stacktrace

Please see above.

### How to reproduce

Please see above.

**Comment by ch3yne** [comment]
Dup of #1619.
