### ISSUE TITLE
[Improvement] [doc]In create table example, it's better to add the complex data type column to show how to define it in gravitino.

### ISSUE THREAD

**Issue by danhuawang** [datastrato/gravitino#1651]
### What would you like to be improved?

https://datastrato.ai/docs/0.3.1/manage-metadata-using-gravitino/#create-a-table
In the example of create table, it's better to add the complex data type column to show how to define it in gravitino.

**Comment by yuqi1129** [comment]
@danhuawang 
Hi,  Gravition column type definition is just about the example, you can refer to it, if you still have problems, please leave comments here.  
<img width="1748" alt="image" src="https://github.com/datastrato/gravitino/assets/15794564/34b0081e-ded9-40cb-b309-ffa6b7691dad">
