### ISSUE TITLE
[Improvement] Add the check for name validation 

### ISSUE THREAD

**Issue by yuqi1129** [datastrato/gravitino#1652]
### What would you like to be improved?

Currently, we do not have any checks for the following things:
- Name identifier check. we can limit the character in the content to avoid some unexpected issues introduced by special character like `&`, `\` and so on.  
- K/V check.  The key and value of key-value pairs should also be considered for simplicity.
-  Others

**Comment by yuqi1129** [comment]
Please also see
#1429
#1633

**Comment by mchades** [comment]
The name identifier is used for the names of schemas and tables. We should investigate whether the underlying catalog also has similar checks for names, in order to make it clear to users whether this is a limitation of Gravitino or the underlying catalog.

**Comment by jerryshao** [comment]
Either we should figure out a generic rule for all the name fields, or we can add to the catalog capabilities for each catalog.
