### ISSUE TITLE
[Subtask] Complete the dropPartition for partition management

### ISSUE THREAD

**Issue by TEOTEO520** [datastrato/gravitino#1655]
### Describe the subtask

Complete the dropPartition for [hive and iceberg] for partition management

### Parent issue

#1575

**Comment by TEOTEO520** [comment]
There is a question that we may need to discuss
For HMS, when we use the hmsClient.dropPartition() to drop partition for a table,  if this table is external table, HMS can not drop the hdfs file of the partition. This is because according to the design of HMS, it won't manage the external table. 

When our users want to drop partition for a table (TTL operation), they need to judge this table whether the table is an external table。 
if it is not an external table, [ hmsClient.dropPartition() ];
if it is  an external table, [ hmsClient.dropPartition() -> path = hmsClient.getPatition -> HDFSUtil.delByPath(path) ];

Can Gravitino unify these operations?

**Comment by TEOTEO520** [comment]
@jerryshao @mchades

**Comment by TEOTEO520** [comment]
There is another question at present. When a user deletes too many partitions, the response time of an interface will be too long, causing timeout and causing inconvenience to the user, making them unsure whether the deletion operation will ultimately be successful; Does Gravitino consider using asynchronous deletion or other methods to deal with situations when too many partitions are deleted at once?

**Comment by mchades** [comment]
> There is another question at present. When a user deletes too many partitions, the response time of an interface will be too long, causing timeout and causing inconvenience to the user, making them unsure whether the deletion operation will ultimately be successful; Does Gravitino consider using asynchronous deletion or other methods to deal with situations when too many partitions are deleted at once?

Currently, all operations in Gravitino are synchronized. 

While supporting asynchronous operations is a good suggestion, it requires careful consideration of various hidden details. To address this matter thoroughly, I propose discussing it separately in a new issue. 

Could you please create a new issue specifically for the topic of asynchronous operations?
