### ISSUE TITLE
[FEATURE] Support MySQL as KV Store backend

### ISSUE THREAD

**Issue by coolderli** [datastrato/gravitino#1659]
### Describe the feature

Currently, the kv store backend only supports RocksDB. It's unable to be used in the production environment. Unfortunately, I couldn't find an available kv database in my company.  So I was wondering if using MySQL as the backend is possible. Will there be scalability issues?

### Describe the solution

Implement MySQL as a kv store backend.

**Comment by yuqi1129** [comment]
Or you can implement another `EntityStore` like JDBCEntityStore,  Using MySQL to implement the KV store is not advised.

**Comment by coolderli** [comment]
@yuqi1129 thanks, I got it.Today is different from the past. I will think about you advice. Thanks.
