### ISSUE TITLE
[Bug report]If the table property use regular expression as value,UI display RegExp incompletely

### ISSUE THREAD

**Issue by danhuawang** [datastrato/gravitino#1684]
### Describe what's wrong

<img width="794" alt="截屏2024-01-24 17 04 07" src="https://github.com/datastrato/gravitino/assets/154112360/dac546b0-5b81-45c5-90d3-15a71db01567">
the parameter in hive is like the following:
<img width="638" alt="截屏2024-01-24 16 54 06" src="https://github.com/datastrato/gravitino/assets/154112360/21eb570b-2015-41a1-8008-66caafac2dc2">
<img width="980" alt="截屏2024-01-24 17 06 37" src="https://github.com/datastrato/gravitino/assets/154112360/6e9fb4d3-b844-4a09-884c-c12c804322a0">

### Error message and/or stacktrace

N/A

### How to reproduce

 Scenario: SerDe Properties
    When set property: key input.regex value bduid\\[(.*)\\]uid\\[(\\d+)\\]uname\\[(.*)\\] for table tt1 in schema department catalog cc2 metalake test
    Then check response code 200 message bduid\\[(.*)\\]uid\\[(\\d+)\\]uname\\[(.*)\\]
    When set property: key output.format.string value %1$s\t%2$s for table tt1 in schema department catalog cc2 metalake test
    Then check response code 200 message %1$s\t%2$s

**Comment by ch3yne** [comment]
Related PR: #1633

**Comment by danhuawang** [comment]
Issue still exist in latest code, so reopen.
