### ISSUE TITLE
[Subtask] Consider upgrading Hadoop client to version 3

### ISSUE THREAD

**Issue by jerryshao** [datastrato/gravitino#1713]

**Comment by YxAc** [comment]
I'd like to work on this issue, may I? @jerryshao

**Comment by justinmclean** [comment]
Hi, @YxAc, if you want to work on an issue, there is no need to ask. Just add a note saying you are working on it.

**Comment by YxAc** [comment]
For this task, do we prefer to directly upgrade to hadoop-v3 or maintain both v3 and v2 branches? what do you think? @jerryshao @justinmclean

**Comment by jerryshao** [comment]
According to my investigation, Hadoop 3 client is compatible with Hadoop 2 server, so it is ok to upgrade to hadoop 3 directly, no need to maintain two branches. What I'm concerned is that for integration test, we put all the catalogs in one classpath, this will introduce dependency issues when we introduce Hadoop 3.

**Comment by YxAc** [comment]
> According to my investigation, Hadoop 3 client is compatible with Hadoop 2 server, so it is ok to upgrade to hadoop 3 directly, no need to maintain two branches. What I'm concerned is that for integration test, we put all the catalogs in one classpath, this will introduce dependency issues when we introduce Hadoop 3.

Can I modify the dependency of integration test first, then update integration test service of CI, and finally modify the other parts? @jerryshao 

We hope use Hadoop 3 when Gravitino landing the production, what do you think? @zhoukangcn

**Comment by jerryshao** [comment]
@YxAc there's not so much work in upgrading Hadoop version to 3 itself. What I'm really concerned is the classpath issue in integration test. 

The integration test depends on multiple catalogs directly, this will simply grab in all the dependencies, I'm worried that some catalogs like Hive and Hadoop may have dependency conflicts. So I would suggest investigating the integration test's dependency issue and minimizing the dependencies as possible as we can. After that, we can easily upgrade to Hadoop 3.

**Comment by YxAc** [comment]
> @YxAc there's not so much work in upgrading Hadoop version to 3 itself. What I'm really concerned is the classpath issue in integration test.
> 
> The integration test depends on multiple catalogs directly, this will simply grab in all the dependencies, I'm worried that some catalogs like Hive and Hadoop may have dependency conflicts. So I would suggest investigating the integration test's dependency issue and minimizing the dependencies as possible as we can. After that, we can easily upgrade to Hadoop 3.

got, i'll try my best.
