### ISSUE TITLE
[Subtask] Add server-side REST API support for fileset

### ISSUE THREAD

**Issue by coolderli** [datastrato/gravitino#1724]
### Describe the subtask

This issue adds server-side REST API support for fileset

### Parent issue

#1241

**Comment by coolderli** [comment]
@jerryshao Are you working on this issue? If not, I'd like to try. But I think it may depend on https://github.com/datastrato/gravitino/issues/1667.

**Comment by jerryshao** [comment]
No, I'm not working on this. You can take a shot on this @coolderli .

**Comment by coolderli** [comment]
I noticed this PR https://github.com/datastrato/gravitino/pull/1714 is merged. I will continue to work on this and rebase my code.
