### ISSUE TITLE
[Improvement] re-organize the code architecture of lakehouse Iceberg

### ISSUE THREAD

**Issue by FANNG1** [datastrato/gravitino#1725]
### What would you like to be improved?

the code of `IcebergRESTcatalog` and `IcebergCatalog` are mixed, we'd better re-organize the code architecture to make it cleaner.

**Comment by FANNG1** [comment]
under `com.datastrato.gravitino.catalog.lakehouse.iceberg` I want to put 3 packages:
1. `catalog`   contains Gravitino Iceberg Catalog specified code
2. `rest.service`  contains Iceberg REST catalog service specified code
3. `common`, the code reused by both.

@jerryshao @Clearvive  any advice? especially for the package name.

**Comment by jerryshao** [comment]
I'm going to remove this out of 0.4.0, we can fix it in the next version.
