### ISSUE TITLE
[Bug report]Gravitino OAuth mode has the CORS issue

### ISSUE THREAD

**Issue by danhuawang** [datastrato/gravitino#1754]
### Version

main branch

### Describe what's wrong

<img width="1506" alt="截屏2024-01-29 11 33 32" src="https://github.com/datastrato/gravitino/assets/154112360/ad4d0d6b-3343-4f2e-9f54-fd7a59879ea1">

### Error message and/or stacktrace

Accept:
application/vnd.gravitino.v1+json
Content-Type:
application/json;charset=UTF-8
Referer:
http://localhost:8090/
Sec-Ch-Ua:
"Not A(Brand";v="99", "Google Chrome";v="121", "Chromium";v="121"
Sec-Ch-Ua-Mobile:
?0
Sec-Ch-Ua-Platform:
"macOS"
User-Agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36

login:1 Access to XMLHttpRequest at 'http://localhost:8177/oauth2/token?grant_type=client_credentials&client_id=test&client_secret=test&scope=test' from origin 'http://localhost:8090' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.

### How to reproduce

1.  docker run -p 8177:8177 --name sample-auth-server -d datastrato/sample-authorization-server:0.3.0
2. enable https for the gravitino server
3.  access url: https://localhost:8433/
4. login in with clientId test, clientSecret test, and scope test

or only configure OAuth  then access http://localhost:8090

### Additional context

image code repo url:
https://github.com/datastrato/gravitino/tree/authorization-server-docker-image
configuration step reference doc:
https://datastrato.ai/docs/0.3.1/security/

**Comment by qqqttt123** [comment]
I should add an another policy for Nignx server of OAuth server.
