### ISSUE TITLE
[Bug report] MysqlTypeConverter cannot handle the datetime data type. 

### ISSUE THREAD

**Issue by hzxiongyinke** [datastrato/gravitino#1761]
### Version

main branch

### Describe what's wrong

Gravitino with mysql catalog, MysqlTypeConverter cannot handle the datetime data type. 

### Error message and/or stacktrace
<img width="1349" alt="image" src="https://github.com/datastrato/gravitino/assets/75288351/09be1751-fc0d-47b5-8f4a-96ffc5d6e977">

### How to reproduce

mysql> CREATE TABLE datetime_table (     id INT PRIMARY KEY,     date_time DATETIME );
![image](https://github.com/datastrato/gravitino/assets/75288351/06cdba21-5db2-4ac0-8ec6-b3a0fc3dec82)

### Additional context

I want to participate in fixing this bug. Can anyone give me some advice?

**Comment by FANNG1** [comment]
@hzxiongyinke , thanks for reporting this issue ,  you could add a transform  to `MysqlTypeConverter` for MySQL, 
seems HiveCatalog IcebergCatalog, PostgreCatalog doesn't support `datatime`too, could you help to fix it?

**Comment by FANNG1** [comment]
@Clearvive @mchades  could you provide some advise?

**Comment by mchades** [comment]
Can you describe the differences between `DATETIME` type and `TIMESTAMP` type of MySQL?

**Comment by hzxiongyinke** [comment]
> Can you describe the differences between `DATETIME` type and `TIMESTAMP` type of MySQL? @hzxiongyinke

For differences between MySQL DATETIME and TIMESTAMP types, refer to https://dev.mysql.com/doc/refman/8.0/en/datetime.html.
By the way, what rules does the data type design of Gravitino follow?

**Comment by mchades** [comment]
> > Can you describe the differences between `DATETIME` type and `TIMESTAMP` type of MySQL? @hzxiongyinke
> 
> For differences between MySQL DATETIME and TIMESTAMP types, refer to https://dev.mysql.com/doc/refman/8.0/en/datetime.html. By the way, what rules does the data type design of Gravitino follow?

------------------------

Before designing the Gravitino type system, we referenced the type systems of other open-source engines such as Substrait, Spark, Hive, and Trino. 

The design goal of the Gravitino type system is to provide a unified semantic and support user-defined types. As it stands, we are striving to cover the most commonly used types in data definition.

Regarding the timestamp type of Gravitino, as described in the [documentation](https://datastrato.ai/docs/0.3.1/manage-metadata-using-gravitino#gravitino-table-column-type):

> Timestamp type indicates a timestamp without timezone
> Timestamp with timezone type indicates a timestamp with timezone


We should be mindful of the differences between `datetime` and `timestamp` in [MySQL](https://dev.mysql.com/doc/refman/8.0/en/datetime.html):

> MySQL converts TIMESTAMP values from the current time zone to UTC for storage, and back from UTC to the current time zone for retrieval. (This does not occur for other types such as DATETIME.) 

Therefore, based on the principle of unified semantics, I believe that we should:

-  **map `datetime` of MySQL to `timestamp` of Gravitino**
-  **map `timestamp` of MySQL to `timestamp_tz` type of Gravitino**. 

Obviously, our current mapping of MySQL `timestamp` type conversion is not appropriate. What do you think? @jerryshao @FANNG1 @Clearvive

**Comment by FANNG1** [comment]
I think Gravitino should provide a `clear` and `general` type definition, the underlying catalog should follow this if there is conflict. and we should add the document to describe this.
* `clear` means the user could easily know the type.
* `general` means most systems follow this.
