### ISSUE TITLE
[Bug report] Failed to create/get schema in postgres 9.2 (use postgres as database)

### ISSUE THREAD

**Issue by danhuawang** [datastrato/gravitino#1786]
### Version

main branch

### Describe what's wrong

<img width="1011" alt="截屏2024-01-30 17 29 40" src="https://github.com/datastrato/gravitino/assets/154112360/d6785954-df01-4a51-ad68-f5a3dff7001f">
<img width="1089" alt="截屏2024-01-30 17 24 14" src="https://github.com/datastrato/gravitino/assets/154112360/b2c51c14-d9ca-4fc2-9faf-a6b4ae1fe119">
<img width="1089" alt="截屏2024-01-30 17 38 48" src="https://github.com/datastrato/gravitino/assets/154112360/e8ee7417-fe87-45e7-906b-3f1982ae279c">

### Error message and/or stacktrace

{
    "code": 1002,
    "type": "RuntimeException",
    "message": "Failed to operate object [pg_temp_1] operation [LOAD] under [pg2], reason [ERROR: type \"regnamespace\" does not exist\n  位置：37]",
    "stack": [
        "java.lang.RuntimeException: com.datastrato.gravitino.exceptions.GravitinoRuntimeException: ERROR: type \"regnamespace\" does not exist",
        "  位置：37",
        "\tat com.datastrato.gravitino.catalog.CatalogOperationDispatcher.doWithCatalog(CatalogOperationDispatcher.java:752)",
        "\tat com.datastrato.gravitino.catalog.CatalogOperationDispatcher.loadSchema(CatalogOperationDispatcher.java:208)",
        "\tat com.datastrato.gravitino.server.web.rest.SchemaOperations.lambda$loadSchema$2(SchemaOperations.java:115)",
        "\tat java.base/java.security.AccessController.doPrivileged(AccessController.java:712)",
        "\tat java.base/javax.security.auth.Subject.doAs(Subject.java:439)",
        "\tat com.datastrato.gravitino.utils.PrincipalUtils.doAs(PrincipalUtils.java:25)",
        "\tat com.datastrato.gravitino.server.web.Utils.doAs(Utils.java:121)",
        "\tat com.datastrato.gravitino.server.web.rest.SchemaOperations.loadSchema(SchemaOperations.java:111)",
        "\tat jdk.internal.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)",
        "\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
        "\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)",
        "\tat org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0

### How to reproduce

1. launch postgres 9.2
2. create catalog in gravitino
jdbc-url: jdbc:postgresql://localhost:5433/postgres
jdbc-user: pgtest
jdbc-driver: org.postgresql.Driver
jdbc-password: pgtest
jdbc-database:  postgres
3. get the exist schema info or create a new schema by api

**Comment by FANNG1** [comment]
I suggest to remove the support for pg 9, for this version is too old and not supported for now. please refer https://help.aliyun.com/zh/rds/apsaradb-rds-for-postgresql/lifecycles-of-major-engine-versions.
And in our integrate test only tests pg from 12 to 16 which is supported for now.

**Comment by danhuawang** [comment]
> https://help.aliyun.com/zh/rds/apsaradb-rds-for-postgresql/lifecycles-of-major-engine-versions

Our doc writes Supports metadata management of PostgreSQL (9.2, 12.0, 13.0)
https://datastrato.ai/docs/0.3.1/jdbc-postgresql-catalog

**Comment by justinmclean** [comment]
Please refer to the official documentation https://www.postgresql.org/support/versioning/ final version dates:
9.2 November 9, 2017
12.0 November 14, 2024
13.0 November 13, 2025

It's unclear from above, but are versions 14,15 and 16 supported? If so, then the documentation should be updated.

**Comment by FANNG1** [comment]
> > https://help.aliyun.com/zh/rds/apsaradb-rds-for-postgresql/lifecycles-of-major-engine-versions
> 
> Our doc writes Supports metadata management of PostgreSQL (9.2, 12.0, 13.0) https://datastrato.ai/docs/0.3.1/jdbc-postgresql-catalog

the document should be corrected, I will post a PR
