### ISSUE TITLE
[Improvement] add auto_increment field in `AddColumn`

### ISSUE THREAD

**Issue by yuqi1129** [datastrato/gravitino#1793]
### What would you like to be improved?

As we have supported column `auto_increment` property, we need to add field `auto_increment` in the `AddColumn` class.

**Comment by SteNicholas** [comment]
@yuqi1129, could you assign this ticket to me?

**Comment by yuqi1129** [comment]
> @yuqi1129, could this ticket also introduce `UpdateColumnAutoIncrement` to support auto_increment? BTW, `AddColumn` should not only add auto_increment, but also support add index, otherwise the `AddColumn` could not add auto_increment.

I'm sorry for not getting back to you earlier, Nicholas. The scenarios you mentioned should also be taken into consideration.

@Clearvive, as you are knowledgeable and responsible for this point, can you follow up on this issue and its aftermath?

**Comment by SteNicholas** [comment]
@Clearvive, any input for above comment?

**Comment by jerryshao** [comment]
Fixed.
