### ISSUE TITLE
[Improvement] Provide a list of fixed CVE for the 0.4 release

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#1803]
### What would you like to be improved?

The release notes should list every publicly known run-time vulnerability fixed in this release.

### How should we improve?

List the CVE's fixed. This is a requirement of https://www.bestpractices.dev/en

**Comment by FANNG1** [comment]
update jersery from 2.39 to 2.41  https://github.com/datastrato/gravitino/pull/1806
update guava from 31.1-jre to 32.1.3-jre https://github.com/datastrato/gravitino/pull/1807
