### ISSUE TITLE
[Improvement] Run static code analysis before 0.4 release

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#1804]
### What would you like to be improved?

Best practice is to use static code analysis.

### How should we improve?

Run sonarlint over the code and look at any major issues. This is a requirement of https://www.bestpractices.dev/en

**Comment by jerryshao** [comment]
@justinmclean can you please help on this, Thanks.

**Comment by justinmclean** [comment]
SonarLint run and most important issues raised (around 90), but still some more work to do.

**Comment by justinmclean** [comment]
While more work needs to be done - it was run for the 0.4 instance.
