### ISSUE TITLE
[Improvement] Add *.ipr file to .gitignore

### ISSUE THREAD

**Issue by FrankYang0529** [datastrato/gravitino#1823]
### What would you like to be improved?

We include [idea plugin](https://github.com/datastrato/gravitino/blob/dd2786a4ff7c84bcb067e1d8a67bdf052992a8d2/build.gradle.kts#L22) in Gradle, so users can run `./gradlew openIdea` or `./gradlew idea` to open IDEA editor. With the command, there is a new file `gravitino.ipr`. The file is not included in [.gitignore](https://github.com/datastrato/gravitino/blob/dd2786a4ff7c84bcb067e1d8a67bdf052992a8d2/.gitignore#L26-L34) or [exclusions](https://github.com/datastrato/gravitino/blob/dd2786a4ff7c84bcb067e1d8a67bdf052992a8d2/build.gradle.kts#L323-L343). If users run `./gradlew build -x test`, they will get failed `rat` task.

### How should we improve?

Add `*.ipr` to `.gitignore` file.

**Comment by FrankYang0529** [comment]
I would like to take the issue. May someone help to assign to me? Thank you.

**Comment by xunliu** [comment]
hi @FrankYang0529 Thank you for your report on this issue.
I think this needs to be fixed.
If you have time, Please fix it, thanks!
