### ISSUE TITLE
[Improvement] Possible bug in `BaseTable.java` with proxyPlugin

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#1868]
### What would you like to be improved?

proxyPlugin (line 68) hides the proxyPlugin field - is this intended?

### How should we improve?

Rename the local variuable?

**Comment by qqqttt123** [comment]
> ### What would you like to be improved?
> proxyPlugin (line 68) hides the proxyPlugin field - is this intended?
> 
> ### How should we improve?
> Rename the local variuable?

I will rename the local variable.
