### ISSUE TITLE
[Improvement] `ErrorHandlers.java` switches should have default cases

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#1894]
### What would you like to be improved?

Adding a final default clause is good practice.

### How should we improve?

Add default cases to switch statements.

**Comment by caican00** [comment]
working on this.

**Comment by yuqi1129** [comment]
@justinmclean @caican00 
It's interesting to me whether switching to a default branch improves code quality overall. Is there any documentation on this topic?

**Comment by justinmclean** [comment]
Yes, it is considered best practice to ensure that unexpected values are not silently ignored.

See for example:
https://pmd.github.io/pmd/pmd_rules_java_bestpractices.html#switchstmtsshouldhavedefault
https://rules.sonarsource.com/java/RSPEC-131/
