### ISSUE TITLE
[Improvement] In `HiveCatalogOperations.java` it may be better to use java.nio.file.Files#delete

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#1909]
### What would you like to be improved?

When java.nio.file.Files#delete fails, it returns one of a series of exception types to better indicate the cause of the failure.

### How should we improve?

Change to use java.nio.file.Files#delete.

**Comment by m1a2st** [comment]
I'm interesting in this issue, my PR is [here](https://github.com/datastrato/gravitino/pull/3715).

**Comment by liujinhui1994** [comment]
Please assign it to me, I have completed it

**Comment by mchades** [comment]
Hi, @m1a2st this issue has already been completed by #3519 , you can pick other issues that interest you, thanks for your enthusiasm
