### ISSUE TITLE
[Improvement] `IcebergConnectorAdapter.java` threading issue

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#1920]
### What would you like to be improved?

static field version is updated by non static method buildInternalConnectorConfig.

Correctly updating a static field from a non-static method is tricky to get right and could easily lead to bugs if there are multiple class instances and/or multiple threads in play. Ideally, static fields are only updated from synchronized static methods.

### How should we improve?

make the method static?

**Comment by jerryshao** [comment]
Fixed by @coolderli in #2139

**Comment by yuqi1129** [comment]
@coolderli 
The same applies to this issue.

**Comment by coolderli** [comment]
Closed by https://github.com/datastrato/gravitino/pull/2139
