### ISSUE TITLE
[Improvement] In `JdbcConfig.java` version number are repeated

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#1927]
### What would you like to be improved?

Version number are repeated. Note other files also do this.

### How should we improve?

Change to use static variables.

**Comment by YxAc** [comment]
there is one mistake in the title of PR #2054 which not fix this issue, can you correct the title of PR 2054? @codeHysteria28 thx.

**Comment by codeHysteria28** [comment]
> there is one mistake in the title of PR #2054 which not fix this issue, can you correct the title of PR 2054? @codeHysteria28 thx.

What is an actual mistake ? Thx

**Comment by YxAc** [comment]
> > there is one mistake in the title of PR #2054 which not fix this issue, can you correct the title of PR 2054? @codeHysteria28 thx.
> 
> What is an actual mistake ? Thx

The title of PR #2054 should remove "[#1927]", you can remove it.

**Comment by codeHysteria28** [comment]
> > > there is one mistake in the title of PR #2054 which not fix this issue, can you correct the title of PR 2054? @codeHysteria28 thx.
> 
> > 
> 
> > What is an actual mistake ? Thx
> 
> 
> 
> The title of PR #2054 should remove "[#1927]", you can remove it.

Should be updated now 😎 thanks for pointing it out ...
