### ISSUE TITLE
[Improvement] Possible resource leak in `JdbcTableOperations.java`

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#1928]
### What would you like to be improved?

This method exists:
```
  protected Connection getConnection(String catalog) throws SQLException {
    Connection connection = dataSource.getConnection();
    connection.setCatalog(catalog);
    return connection;
  }
```

But there is no method to close the connection.

### How should we improve?

Add method to close connection.

**Comment by YxAc** [comment]
@justinmclean I see that all code that calls 'getConnection' use the 'try-with-resources' statement to automatically close the resource.

This statement automatically closes the resource that implements the 'AutoCloseable' interface at the end of the try code block. The Connection interface implements the 'AutoCloseable' interface, so we can use 'try-with-resources' statements to automatically close database connections.

So this problem doesn't have to be fixed?

**Comment by justinmclean** [comment]
Thanks for taking a look and confirming there is no issue here.
