### ISSUE TITLE
[Improvement] Possible thead issue in `JsonUtils.java`

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#1935]
### What would you like to be improved?

Mapper is marked as volatile, but marking a mutable object field volatile means the object reference is volatile but the object itself is not, and other threads may not see updates to the object state.

### How should we improve?

Fix possible thread issue?

**Comment by YxAc** [comment]
@justinmclean Yes, in a multithreaded environment, the volatile keyword does only guarantee the visibility of object references, not the internal state of the object.

However, in the JsonUtils class, the initialization of the ObjectMapper instance uses the double-checked locking mode, which is used with the volatile keyword to ensure thread safety. In this case, once the ObjectMapper instance is initialized, it will not be modified, so multiple threads will not modify the internal state of the ObjectMapper at the same time.

Therefore, although the volatile keyword does not guarantee the visibility of the internal state of the object, in this particular case, the internal state of ObjectMapper will not be modified after initialization, and it is reasonable to declare ObjectMapper as volatile.

So this problem doesn't have to be fixed?

**Comment by YxAc** [comment]
Inspired by @qqqttt123 , Maybe we can use the Lazy Singleton approach, using Java's ClassLoader instant load feature to solve this problem? What do you think? @justinmclean

**Comment by YxAc** [comment]
> Inspired by @qqqttt123 , Maybe we can use the Lazy Singleton approach, using Java's ClassLoader instant load feature to solve this problem? What do you think? @justinmclean

I made some change with lazy singleton to improve it, can you spare some time to review the PR? thx @qqqttt123
