### ISSUE TITLE
[Improvement] `MapUtils.java` is missing a private constructor

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#1940]
### What would you like to be improved?

Utility classes should have private constructors

### How should we improve?

Add private constructor

**Comment by MohitKambli** [comment]
Hello,
Hope you're doing well.
I am terribly sorry for my previous commit that I made.
I have removed the code that would throw the error and simply placed an empty private constructor as you might see in the new commit made.
As you mentioned earlier, I am trying to fire the **"./gradlew :common: spotlessly"** command, but I get the following error logs:

![image](https://github.com/datastrato/gravitino/assets/31406633/4d33f6c8-f9d8-4cb7-83d5-f2490beaa74d)

Do you think I am making any mistake over here?
Extremely sorry if I am doing something wrong.

**Comment by justinmclean** [comment]
Thanks for fixing that. Currently, we only fully support compiling on macOS and Linux, but you may get it to work using Windows Subsystem for Linux. Also I'm sorry but I gave you the wrong command it should be `./gradlew :common:spotlessApply`

**Comment by MohitKambli** [comment]
Hello,
Thank you for helping me out and understanding my side.
I am trying not to trouble you as much as possible, but some or the other issue turns up and creates a problem.
For now, I have implemented the code changes and also I guess the `./gradlew :common:spotlessApply` has executed successfully.

![image](https://github.com/datastrato/gravitino/assets/31406633/c5fd11dc-db34-4c6d-9ebb-4000260d6955)

But, I guess still the test cases aren't getting executed successfully.
I am extremely sorry for causing all this trouble to you.

**Comment by jerryshao** [comment]
Fixed by #2345
