### ISSUE TITLE
[Improvement] Possible thread issue in `MemoryConnectorAdapter.java`

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#1941]
### What would you like to be improved?

A static field version is being updated in a non-static method buildInternalConnectorConfig.
Correctly updating a static field from a non-static method is tricky to get right and could easily lead to bugs if there are multiple class instances and/or multiple threads in play. Ideally, static fields are only updated from synchronized static methods.

### How should we improve?

Make the method static?

**Comment by jerryshao** [comment]
Fixed by @coolderli in #2139

**Comment by yuqi1129** [comment]
@coolderli 
The same applies to this issue.

**Comment by coolderli** [comment]
Closed by https://github.com/datastrato/gravitino/pull/2139
