### ISSUE TITLE
[Improvement] Possible thread issue in `MySQLConnectorAdapter.java`

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#1946]
### What would you like to be improved?

Static variable version is being updated in non-static method buildInternalConnectorConfig.

Correctly updating a static field from a non-static method is tricky to get right and could easily lead to bugs if there are multiple class instances and/or multiple threads in play. Ideally, static fields are only updated from synchronized static methods.

### How should we improve?

Make method static?

**Comment by jerryshao** [comment]
Fixed by @coolderli in #2139

**Comment by yuqi1129** [comment]
@coolderli 
Can you leave a comment here, I'm handling the release work, as this is your credit, but due to GitHub restrictions, I can't assign it to you.

**Comment by coolderli** [comment]
Closed by https://github.com/datastrato/gravitino/pull/2139
