### ISSUE TITLE
[Improvement] Possible thread issue in `PostgreSQLConnectorAdapter.java`

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#1953]
### What would you like to be improved?

Static field version is being updated in non-static method buildInternalConnectorConfig.

Correctly updating a static field from a non-static method is tricky to get right and could easily lead to bugs if there are multiple class instances and/or multiple threads in play. Ideally, static fields are only updated from synchronized static methods.

### How should we improve?

Change method to static?

**Comment by coolderli** [comment]
@justinmclean I submit a PR to fix this: https://github.com/datastrato/gravitino/pull/2139
Please review it when you have time. Thanks.
