### ISSUE TITLE
[Improvement] Possible resource leak in `RocksDBKvBackend.java`

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#1955]
### What would you like to be improved?

In the method scan an exception could mean that db is not closed, same in deleteRange. Local varaible options is not closed in initRocksDB.

### How should we improve?

Use try/catch/finally and close options?

**Comment by coolderli** [comment]
@justinmclean I submit a PR to fix this: https://github.com/datastrato/gravitino/pull/2138
Please help review it when you have time. Thanks.
