### ISSUE TITLE
[Improvement] `ToIcebergSortOrder.java` missing private constructor

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#1961]
### What would you like to be improved?

Utility classes should have private constructors.

### How should we improve?

Add private constructor.

**Comment by YxAc** [comment]
HI @justinmclean ，Noticed that you have report over one hundred optimizations two days ago. I have a plan to solve all of them during the next two weekends. 
Could you assign them to me?

**Comment by justinmclean** [comment]
Thanks for wanting to help out. Just pick a couple of issues and try those out first and see how you go. Feel free to add a comment saying you are working on an issue without having the issue assigned to you.
