### ISSUE TITLE
[Improvement] Possible thead issue in `TransactionIdGeneratorImpl.java`

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#1962]
### What would you like to be improved?

If an InterruptedException  error is not handled properly, the information that the thread was interrupted will be lost. Handling this exception means either to re-throw it or manually re-interrupt the current thread by calling Thread.interrupt().

### How should we improve?

Call Thread.interrupt()?

**Comment by coolderli** [comment]
@justinmclean Can you describe it more clearly? I have no idea which thread will be interrupted

**Comment by YxAc** [comment]
> @justinmclean Can you describe it more clearly? I have no idea which thread will be interrupted

This suggestion is about the handling of InterruptedException：An InterruptedException is thrown when a thread may be interrupted by another thread while waiting, sleeping, or other blocking operations.

This exception is an important communication mechanism that indicates that other threads want to interrupt the current operation of this thread. If you capture the InterruptedException but do not handle it properly, you will lose the message that the thread was interrupted.

Handling this exception properly usually means either re-throwing the exception or manually interrupting the current thread by calling Thread.interrupt ()

i'll fix these.
