### ISSUE TITLE
[Improvement] Possible thread issue is `TransactionalKvBackendImpl.java`

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#1963]
### What would you like to be improved?

ThreadLocal variables are supposed to be garbage collected once the holding thread is no longer alive. Memory leaks can occur when holding threads are re-used which is the case on application servers using pool of threads.
it is recommended to always clean up ThreadLocal variables using the remove() method to remove the current thread’s value for the ThreadLocal variable.

### How should we improve?

Call remove() method.

**Comment by YxAc** [comment]
i noticed it had already been called.
![image](https://github.com/datastrato/gravitino/assets/5182511/e7efefb9-e2fd-404b-8599-3b6cb312af9f)

And the closeTransaction() would be called
![image](https://github.com/datastrato/gravitino/assets/5182511/e1288ad7-9260-47e7-ab03-bc0697c9e582)

**Comment by YxAc** [comment]
hi @justinmclean , can you reconfirm it in your spare time?  thx.

**Comment by justinmclean** [comment]
This looks good to me, thanks for taking the time to check it out.
