### ISSUE TITLE
[Improvement] `Transforms.java` is missing private constructor

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#1964]
### What would you like to be improved?

Utility classes should have private constructors

### How should we improve?

Add a private constructor.

**Comment by codeHysteria28** [comment]
Hi @justinmclean can I help with this one ?

**Comment by justinmclean** [comment]
Sure, if you have any issues, just ask for help.

**Comment by codeHysteria28** [comment]
I've seen multiple issues missing private constructor, can you also assign it to me and I can update it to one PR ? Cheers

**Comment by justinmclean** [comment]
There is no need to wait for an issue to be assigned to you. Just add a comment you are working on and raise a PR.
