### ISSUE TITLE
[Improvement] `VersioningFilter.java` uses "Accept" when it has ACCEPT_VERSION_HEADER

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#1968]
### What would you like to be improved?

use ACCEPT_VERSION_HEADER instead

### How should we improve?

use ACCEPT_VERSION_HEADER instead

**Comment by yuqi1129** [comment]
@YxAc 
Can you leave a comment here, I'm handling the release work, as this is your credit, but due to GitHub restrictions, I can't assign it to you.

**Comment by YxAc** [comment]
@yuqi1129  Sure, Thanks a lot.
