### ISSUE TITLE
[Bug report]  0.4 client access old GravitinoServer 0.3 error

### ISSUE THREAD

**Issue by FANNG1** [datastrato/gravitino#1973]
### Version

main branch

### Describe what's wrong

Unable to process: Error code: 400, message: Invalid distribution strategy: none. Valid values are: [HASH, RANGE, EVEN]

### Error message and/or stacktrace

```
com.datastrato.gravitino.exceptions.RESTException: Unable to process: Error code: 400, message: Invalid distribution strategy: none. Valid values are: [HASH, RANGE, EVEN] (through reference chain: com.datastrato.gravitino.dto.requests.TableCreateRequest$TableCreateRequestBuilder["distribution"])
```

### How to reproduce

1. start 0.4 server
2. use 0.3 client to access the server

**Comment by diqiu50** [comment]
Duplicates with https://github.com/datastrato/gravitino/issues/2866
