### ISSUE TITLE
[Bug report] Something wrong about loading MySQL table: `Table already exists` and `Table does not exist` con-existentence.

### ISSUE THREAD

**Issue by yuqi1129** [datastrato/gravitino#2037]
### Version

main branch

### Describe what's wrong

<img width="994" alt="image" src="https://github.com/datastrato/gravitino/assets/15794564/6cf01b19-eb12-431a-a821-e16d009860e1">

### Error message and/or stacktrace

Please see above.

### How to reproduce

Please see above.

**Comment by yuqi1129** [comment]
<img width="1670" alt="image" src="https://github.com/datastrato/gravitino/assets/15794564/3bc2d6a3-8703-43e2-92ea-e25eaf878b30">

Something wrong with the usage of DatabaseMetaData

**Comment by yuqi1129** [comment]
@jerryshao 
Should we fix it in branch 0.4.0?

**Comment by jerryshao** [comment]
I think so.
