### ISSUE TITLE
[Bug report]When rename the catalog, the left tree view display both old name and new name until fresh the page

### ISSUE THREAD

**Issue by danhuawang** [datastrato/gravitino#2068]
### Version

main branch

### Describe what's wrong

<img width="890" alt="截屏2024-02-05 15 29 12" src="https://github.com/datastrato/gravitino/assets/154112360/49f7c6bc-0335-421a-9b54-d72c25d8886e">

### Error message and/or stacktrace

N/A

### How to reproduce

1.rename catalog
2. see the left tree view

**Comment by jerryshao** [comment]
@ch3yne can you please fix this.

**Comment by danhuawang** [comment]
fresh issue when catalog create
<img width="1461" alt="截屏2024-02-05 15 57 45" src="https://github.com/datastrato/gravitino/assets/154112360/cc277102-9974-4091-8fc9-8df3eb211d67">
