### ISSUE TITLE
[Improvement] Possible improvement issue for gravitino package path naming 

### ISSUE THREAD

**Issue by YxAc** [datastrato/gravitino#2073]
### What would you like to be improved?

Current package path like: 
- Core：com.datastrato.gravitino.catalog.rel.BaseTable.java 
- Common：com.datastrato.gravitino.dto.rel.ColumnDTO.java

Actually, if you just look at the class name or package path, you can't know which module it came from, Core or Common?
Further, when you want to find the 'rel' package, you will be more confused about where to find it.

### How should we improve?

We can naming package by adding module name, like:

Modify them
- Core：com.datastrato.gravitino.catalog.rel.BaseTable.java 
- Common：com.datastrato.gravitino.dto.rel.ColumnDTO.java

To ===>

- Core：com.datastrato.gravitino._**core**_.catalog.rel.BaseTable.java 
- Common：com.datastrato.gravitino.**_common_**.dto.rel.ColumnDTO.java

How do you think this？

**Comment by YxAc** [comment]
what do you think? @justinmclean @jerryshao 
Can I move on with this?

**Comment by justinmclean** [comment]
@jerryshao what do you think?

**Comment by jerryshao** [comment]
Sorry for the late response @YxAc .

IMHO, there're several reasons that I'm conservative to this large refactoring:

1. By adding the module name to the package path as a constraint, this will potentially make some of works hard to do, like sharing the classes to another module without needing to make them public. 
   
    For example, many of DTOs put in `common` module are used for client and server, we don't want them to be used by users, so we can use package private to hide the accessibility. But when we add the module name to the package path, we have to expose them as public classes.

2. The changes in api/client module will break the compatibility as package name is changed. 

As I don't see the strong reason or benefit of doing this. IMHO, I would not defer this until we see the strong reason or necessity to do this refactoring work.

Sorry about this.

**Comment by YxAc** [comment]
> Sorry for the late response @YxAc .
> 
> IMHO, there're several reasons that I'm conservative to this large refactoring:
> 
> 1. By adding the module name to the package path as a constraint, this will potentially make some of works hard to do, like sharing the classes to another module without needing to make them public.
>    For example, many of DTOs put in `common` module are used for client and server, we don't want them to be used by users, so we can use package private to hide the accessibility. But when we add the module name to the package path, we have to expose them as public classes.
> 2. The changes in api/client module will break the compatibility as package name is changed.
> 
> As I don't see the strong reason or benefit of doing this. IMHO, I would not defer this until we see the strong reason or necessity to do this refactoring work.
> 
> Sorry about this.

No problem. Thank you for your reply.
