### ISSUE TITLE
[Improvement] Add document about how to develop Gravitino Trino connector in IDE

### ISSUE THREAD

**Issue by yuqi1129** [datastrato/gravitino#2087]
### What would you like to be improved?

Currently, there is no document on how to set up the local environment to develop the Gravitino Trino connector, making it difficult for developers to participate in the Trino connector module.

**Comment by mchades** [comment]
FYI:
https://github.com/trinodb/trino/blob/master/.github/DEVELOPMENT.md#additional-ide-configuration

**Comment by yuqi1129** [comment]
> FYI: [trinodb/trino@`master`/.github/DEVELOPMENT.md#additional-ide-configuration](https://github.com/trinodb/trino/blob/master/.github/DEVELOPMENT.md?rgh-link-date=2024-02-06T03%3A49%3A52Z#additional-ide-configuration)

The integration of Gravitino into IDE is not as straightforward as it seems, as there are several additional steps to be taken when integrating Gravitino. like
- How to import Gravitino `trino-connetor` to Trino project
- Setting such as maven dependencies and configurations.

**Comment by yuqi1129** [comment]
Duplicated with #1193

**Comment by yuqi1129** [comment]
I'm going to close it as it has been fixed by https://github.com/datastrato/gravitino/pull/2446
