### ISSUE TITLE
[Bug report]OAuth mode, enable https ,Safari: Network Error in login page

### ISSUE THREAD

**Issue by danhuawang** [datastrato/gravitino#2100]
### Version

main branch

### Describe what's wrong

<img width="1512" alt="截屏2024-02-06 10 20 32" src="https://github.com/datastrato/gravitino/assets/154112360/637d597f-1f89-44e5-8b59-756c00828696">

### Error message and/or stacktrace

N/A

### How to reproduce

1. enable OAuth mode
2. enable https
3. access https://localhost:8433

**Comment by jerryshao** [comment]
@ch3yne please add this constraints to the doc.
