### ISSUE TITLE
[Improvement] doc(trino configuration): change gravitino.url to gravitino.uri

### ISSUE THREAD

**Issue by FrankYang0529** [datastrato/gravitino#2118]
### What would you like to be improved?

The example in trino-connector/installation.md uses different keys for gravitino link.

https://github.com/datastrato/gravitino/blob/edfcdbea89dbf16d8e48833573c8917f9bcd5972/docs/trino-connector/installation.md?plain=1#L75-L81

From source code, it should be `gravitino.uri`.

https://github.com/datastrato/gravitino/blob/edfcdbea89dbf16d8e48833573c8917f9bcd5972/trino-connector/src/main/java/com/datastrato/gravitino/trino/connector/GravitinoConfig.java#L22

We also need to fix the one in trino-connector/configuration.md.

https://github.com/datastrato/gravitino/blob/edfcdbea89dbf16d8e48833573c8917f9bcd5972/docs/trino-connector/configuration.md?plain=1#L13

### How should we improve?

Change `gravitino.url` to `gravitino.uri`.

**Comment by FrankYang0529** [comment]
I would like to take the issue. May someone assign to me? Thank you.

**Comment by xunliu** [comment]
@diqiu50 Please help review this issue.

**Comment by diqiu50** [comment]
> I would like to take the issue. May someone assign to me? Thank you.

Ok， We can change it as `uri`

**Comment by xunliu** [comment]
hi @FrankYang0529 
Please help change it to `uri` if you have free time, Thanks!

**Comment by JunpingDu** [comment]
Thank you, @FrankYang0529 for your contribution!
