### ISSUE TITLE
[Improvement] Keep Lock type in each `TreeLockNode` for ease of unlock

### ISSUE THREAD

**Issue by yuqi1129** [datastrato/gravitino#2127]
### What would you like to be improved?

We use a stack of `TreeLockNode` to keep those nodes that have been locked, however, when we encounter errors, the last 
tree lock node that have been locked is not always the same as the `type` TreeLock keeps. 

For example, assuming we want to lock path `metalake.catalog.schema.table` with the write lock, then the size of `lockNodes` in TreeLock is  5 and the value of `lockType` is Write. 

Then, we attempted to lock all the tree lock nodes from the root to the leaf. When we attempt to lock the schema, something unexpected occurs. Then we need to unlock the nodes we already acquired. However, the lock type for the first nodes we need to unlock is `catalog` is READ not Write, so we need to keep the lock type with the tree node.

<img width="1449" alt="image" src="https://github.com/datastrato/gravitino/assets/15794564/63abbc4b-ef27-4d6b-befd-2272332e6ff8">

### How should we improve?

<img width="1206" alt="image" src="https://github.com/datastrato/gravitino/assets/15794564/bb67c88d-a47b-4096-a6bc-d873029f7128">

**Comment by YxAc** [comment]
Good question. I'll fix it.

**Comment by YxAc** [comment]
@yuqi1129 I have submitted the revision, please help review in your spare time, thx
