### ISSUE TITLE
[Improvement] In StorageLayoutException.java and StorageLayoutException.java no passing final variable in format string

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#2152]
### What would you like to be improved?

StorageLayoutException.java:22: error: [FormatStringAnnotation] All variables passed as @FormatString must be final or effectively final
    super(message, args);

StorageLayoutException.java:34: error: [FormatStringAnnotation] All variables passed as @FormatString must be final or effectively final
    super(cause, message, args);

See https://errorprone.info/bugpattern/FormatStringAnnotation for more information

**Comment by coolderli** [comment]
@justinmclean I think this issue can be closed now. Because it has been fixed on https://github.com/datastrato/gravitino/pull/1746.

**Comment by justinmclean** [comment]
Closing as it has been fixed.

**Comment by coolderli** [comment]
@justinmclean Maybe forgot to click the close button.
