### ISSUE TITLE
[Improvement] Column.java Prefer instanceof to getClass

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#2154]
### What would you like to be improved?

Column.java:180: warning: [EqualsGetClass] Prefer instanceof to getClass when implementing Object#equals.
    public boolean equals(Object o) {

See https://errorprone.info/bugpattern/EqualsGetClass.

**Comment by zivali** [comment]
Looking into this one.

**Comment by zivali** [comment]
I noticed there are similar syntax `getClass() != o.getClass()` in multiple other classes.
https://github.com/search?q=repo%3Adatastrato%2Fgravitino+getClass%28%29+%21%3D+o.getClass%28%29&type=code&p=1
```
if (o == null || getClass() != o.getClass()) return false;
```
Is it a good idea to change all of them to the following form?
```
if (!(o instanceof SomeClass)) {
        return false;
}
```

**Comment by justinmclean** [comment]
Sure feel free to change them all in one go
