### ISSUE TITLE
[Improvement] Fill in misisng Javadoc for @return

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#2155]
### What would you like to be improved?

@return missing description in:
JdbcDatabaseOperations.java
ConvertUtil.java
FromIcebergPartitionSpec.java
ToIcebergPartitionSpec.java
IcebergTableOpsHelper.java
JsonUtils.java
TrinoQueryIT.java

**Comment by FrankYang0529** [comment]
I would like to take the issue. @justinmclean, may you assign to me? Thanks.

**Comment by yuqi1129** [comment]
> I would like to take the issue. @justinmclean, may you assign to me? Thanks.

Of course, please go ahead.

**Comment by justinmclean** [comment]
For issues like this, just add a comment you are working on them. There's no need to ask for permission.
