### ISSUE TITLE
[Improvement] throwIfUnchecked is a no-op

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#2160]
### What would you like to be improved?

/DynFields.java:60: error: [ThrowIfUncheckedKnownChecked] throwIfUnchecked(knownCheckedException) is a no-op.
        Throwables.throwIfUnchecked(e);

DynFields.java:69: error: [ThrowIfUncheckedKnownChecked] throwIfUnchecked(knownCheckedException) is a no-op.
        Throwables.throwIfUnchecked(e);
                                 
See https://errorprone.info/bugpattern/ThrowIfUncheckedKnownChecked

**Comment by lambaaryan011** [comment]
i want to work on this issue? can you please assign this issue to me.

**Comment by justinmclean** [comment]
Sure, if you need any help just ask.

**Comment by lambaaryan011** [comment]
ok

**Comment by lambaaryan011** [comment]
Hello sir, i am beginner  can you please provide some guidance on how I can get started? 
Thanks!

**Comment by qqqttt123** [comment]
> Hello sir, i am beginner can you please provide some guidance on how I can get started? Thanks!

You can see https://github.com/datastrato/gravitino/blob/main/CONTRIBUTING.md

**Comment by justinmclean** [comment]
If you are not sure how you can fix this issue, there are a lot of others marked "good first issue" and you can pick one of those instead.

**Comment by lambaaryan011** [comment]
Got it.  But , I resolved the issue, but you're stuck installing a local server. Could you please specify the type of server and any specific problems you're encountering during the installation?

**Comment by justinmclean** [comment]
I'm sorry, but I don't know what server you are referring to. No server installation is needed other than the prerequisites to build the project. If you have a fix, please raise a pull request, and it will be reviewed. If you have problems building the project before making the PR, please tell us what issue you have run into.

**Comment by coolderli** [comment]
@lambaaryan011 Hi, are you still working on this? I think you can take a look at some similar issues,such as https://github.com/datastrato/gravitino/issues/2154.

**Comment by lambaaryan011** [comment]
yes , work is going on

**Comment by liujinhui1994** [comment]
Please assign it to me, I have completed it
