### ISSUE TITLE
[Improvement] TransactionIdGeneratorImpl.java make operator precedence clearer

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#2165]
### What would you like to be improved?

/Users/justin/gravitino/core/src/main/java/com/datastrato/gravitino/storage/kv/TransactionIdGeneratorImpl.java:120: warning: [OperatorPrecedence] Use grouping parenthesis to make the operator precedence explicit
    if (incrementId >= (1 << 18 - 1)) {

See https://errorprone.info/bugpattern/OperatorPrecedence)

### How should we improve?

Does it mean  (incrementId >= (1 << (18 - 1))) or something else? I think this may be a bug.

**Comment by YxAc** [comment]
@justinmclean From the context, the original intention is `(incrementId >= ((1 << 18) - 1))`, i'll improve this.

**Comment by YxAc** [comment]
> @justinmclean From the context, the original intention is `(incrementId >= ((1 << 18) - 1))`, i'll improve this.

Can you review this PR in your spare time? thx. @justinmclean @yuqi1129
