### ISSUE TITLE
[Improvement] RocksDBKvBackend.java is missing coverage in scan and deleteRange

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#2186]
### What would you like to be improved?

 RocksDBKvBackend.java is missing coverage in scan and deleteRange methods.

### How should we improve?

Write more unit tests to cover scan and deleteRange methods.

**Comment by ajayl83** [comment]
@justinmclean i can see some of the conditions are indeed not covered but i do also see comment in test that maybe they are covered in TestTransactionalKvBackend, so my question is can i first analyse if it really needs coverage

**Comment by ajayl83** [comment]
![Uploading Screenshot 2024-02-23 at 08.47.26.png…]()

**Comment by justinmclean** [comment]
Yes, you can look at the test coverage reports as I did.

**Comment by ajayl83** [comment]
@justinmclean  will raise PR for this soon!
