### ISSUE TITLE
[Improvement] There’s is no need to null test in conjunction with an instanceof test.

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#2187]
### What would you like to be improved?

In NameIdentifier.java you have this code:
```java
public boolean equals(Object other) {
    if (other == null || !(other instanceof NameIdentifier)) {
```
There is no need to null test in conjunction with an instanceof test as instanceof null is false.

The same problem exists in Namespace.java and HiveClientPool.java

### How should we improve?

Remove null check and simplify if statements.

**Comment by justinmclean** [comment]
Sorry, @zivali, it looks like someone else provided a fix first. If you see an issue like this, and want to work on it, you can just comment here you are working on it and don't have to ask.

**Comment by zivali** [comment]
Got it, thanks! I think we can remove the null check in `HiveClientPool.java` as well.
