### ISSUE TITLE
[Improvement] Null pointer exception could result in HTTPClient.java

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#2194]
### What would you like to be improved?

In this code:

```java
      if (responseBody == null) {
        throw new RESTException(
            "Invalid (null) response body for request (expected %s): method=%s, path=%s, status=%d",
            responseType.getSimpleName(), method.name(), path, response.getCode());
      }
```

and this:
      if (responseBody == null) {
        throw new RESTException(
            "Invalid (null) response body for request (expected %s): method=%s, path=%s, status=%d",
            responseType.getSimpleName(), method.name(), path, response.getCode());
      }

responseType coudl be null

### How should we improve?

Check that responseType is null and pass a suitable default value.

**Comment by surajbora59** [comment]
@justinmclean , Could you please provide more context or specify which default value you're referring to?

**Comment by YxAc** [comment]
> @justinmclean , Could you please provide more context or specify which default value you're referring to?

This means _ResponseType_ may be null, and if so, a call to _responseType.getSimpleName()_  will results in NullPointerException. To avoid this, you should add an empty check before using _responseType_.

**Comment by justinmclean** [comment]
If ResponseType is null, you might want to default to using "unknown" or similar for expected.

**Comment by justinmclean** [comment]
@surajbora59 @YxAc do either of you want to work on this?
