### ISSUE TITLE
[Improvement] Improve the judgment granularity of exception information in JDBC backend

### ISSUE THREAD

**Issue by xloya** [datastrato/gravitino#2227]
### What would you like to be improved?

Improve the judgment granularity of exception information of different databases in JDBC backend, current method of tracking exception classes is too coarse-grained and requires fine-grained judgment. see https://github.com/datastrato/gravitino/pull/1980#discussion_r1493656736

**Comment by yuqi1129** [comment]
@xloya 
Do you have time to work on it in release 0.5.0?

**Comment by xloya** [comment]
> @xloya Do you have time to work on it in release 0.5.0?

@yuqi1129 Not yet. I'll try my best.

**Comment by yuqi1129** [comment]
OK, If you do not have time, we can postpone it to release 0.5.1 or later since it's just an improvement.
