### ISSUE TITLE
[Subtask] initialization Gravitino Python client

### ISSUE THREAD

**Issue by xunliu** [datastrato/gravitino#2229]
### Describe the subtask

Design according to the proposed document: https://docs.google.com/document/d/1Eq9qd94967cYpSagTps34vHbHNhO4VMPs4R-6tNK8Eo/edit, 
we consider initialization Gravitino Python client.
1. Create Gravitino Python client module in the `gravitino/clients/client-python/*` directory.
2. Use Python REST library `requests` to connector Gravitino Server RESTful interface.
3. Implementation `getVersion()` Python function in the `gravitino/clients/client-python/core` directory.
4. Implementation `getVersionTest()` UnitTest in the `gravitino/clients/client-python/tests` directory.
5. We can reference to Gravitino JAVA client implementation, https://github.com/datastrato/gravitino/blob/main/clients/client-java/src/main/java/com/datastrato/gravitino/client/GravitinoClient.java

We can refer to this article to create a Python library step by step. https://towardsdatascience.com/deep-dive-create-and-publish-your-first-python-library-f7f618719e14

### Parent issue

#2113

**Comment by xunliu** [comment]
hi @Lanznx 
Are you interested in implementing this task?

**Comment by Lanznx** [comment]
yes, i'm willing to do it
