### ISSUE TITLE
[Subtask] Add Metalake APIs in Gravitino Python client

### ISSUE THREAD

**Issue by xunliu** [datastrato/gravitino#2251]
### Describe the subtask

Add these Python function interfaces into Gravitino Python client, refer to the document for the API descriptions.

+ define a `NameIdentifier` structure in Python client, like this: https://github.com/datastrato/gravitino/blob/main/api/src/main/java/com/datastrato/gravitino/NameIdentifier.java
+ listMetalakes(): https://datastrato.ai/docs/0.4.0/api/rest/list-metalakes
+ loadMetalake(): https://datastrato.ai/docs/0.4.0/api/rest/load-metalake
+ createMetalake(): https://datastrato.ai/docs/0.4.0/api/rest/create-metalake
+ alterMetalake(): https://datastrato.ai/docs/0.4.0/api/rest/alter-metalakes
+ dropMetalake(): https://datastrato.ai/docs/0.4.0/api/rest/drop-metalakes

### Parent issue

#2113

**Comment by zhaoyongjie** [comment]
I'd like to join the community and work on this task.

**Comment by shaofengshi** [comment]
Yongjie, awesome! I assigned it to you and please go ahead.
