### ISSUE TITLE
[Subtask] Add Catalog APIs in Gravitino Python client

### ISSUE THREAD

**Issue by xunliu** [datastrato/gravitino#2252]
### Describe the subtask

Add these Python function interfaces into Gravitino Python client, reference to the document for the API descriptions.

+ listCatalogs(Namespace namespace): https://datastrato.ai/docs/0.4.0/api/rest/list-catalogs
+ loadCatalog(NameIdentifier ident): https://datastrato.ai/docs/0.4.0/api/rest/load-catalog
+ createCatalog(...): https://datastrato.ai/docs/0.4.0/api/rest/create-catalog
+ alterCatalog(...): https://datastrato.ai/docs/0.4.0/api/rest/alter-catalog
+ dropCatalog(...): https://datastrato.ai/docs/0.4.0/api/rest/drop-catalog

We can reference the Gravitino JAVA client implementation, [GravitinoMetaLake.java](https://github.com/datastrato/gravitino/blob/main/clients/client-java/src/main/java/com/datastrato/gravitino/client/GravitinoMetaLake.java)

### Parent issue

#2113

**Comment by Lanznx** [comment]
YES, I'm willing to implement this
