### ISSUE TITLE
[Improvement] TestRocksDBKvBackend tests should not return values

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#2258]
### What would you like to be improved?

Test testScan tests return a value, tests shouldn't do this. Has the @Test annotation been added by mistake?

### How should we improve?

Fix test to not return values or remove @Test annotation?

**Comment by yuqi1129** [comment]
@nk1506 

The same applies to this issue.

**Comment by nk1506** [comment]
This is fixed by, https://github.com/datastrato/gravitino/pull/2276
