### ISSUE TITLE
[Bug report] HADOOP_DOWNLOAD_URL in dev/docker/hive/hive-dependency.sh is invaild

### ISSUE THREAD

**Issue by danhuawang** [datastrato/gravitino#2263]
### Version

main branch

### Describe what's wrong

```
curl http://archive.apache.org/dist/hadoop/core/hadoop-2.7.3/hadoop-2.7.3.tar.gz

 <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://archive.apache.org/dist/hadoop/core/hadoop-2.7.3/hadoop-2.7.3.tar.gz">here</a>.</p>
</body></html>
```

```
curl https://archive.apache.org/dist/hadoop/core/hadoop-2.7.3/hadoop-2.7.3.tar.gz -o hadoop-2.7.3.tar.gz

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  204M  100  204M    0     0  2242k      0  0:01:33  0:01:33 --:--:-- 7240k
```

### Error message and/or stacktrace

N/A

### How to reproduce

build gravitino-ci-hive image

**Comment by zhoukangcn** [comment]
`http://` is redirected to `https://`.

I notice that `hive-dependency.sh` just use `http://` in HADOOP_DOWNLOAD_URL, we need change it to `https://`

**Comment by mchades** [comment]
> `http://` is redirected to `https://`.
> 
> I notice that `hive-dependency.sh` just use `http://` in HADOOP_DOWNLOAD_URL, we need change it to `https://`

Good point! BTW, the `-L` option can also be added to the `curl` command for following redirects. Would you be willing to address this issue? @zhoukangcn
