### ISSUE TITLE
[EPIC] Fully revisit the protocol and API compatibility between versions, between server and client

### ISSUE THREAD

**Issue by jerryshao** [datastrato/gravitino#2269]
### Describe the proposal

The priority of Gravitino is to keep the compatibility (at last backward compatibility) between versions, and also keep the different versioned client / server compatible. This is the key thing to the stability of the project. In this version, we should fully revisit the protocol and API definitions, as well as client/server implementation. To make sure Gravitino is version stable and compatible.

### Task list

- [x] #1973 
- [x] #1978 
- [x] #2866 
- [x] #2988

**Comment by coolderli** [comment]
Actually, I'm a little worried about this. For now, we don't support the `Flink` engine. Compatibility is very important for a long-running job.

I found a blog that uses GitHub workflow to validate the compatibility of open-api: https://mindbyte.nl/2023/03/14/ensuring-api-compatibility-with-openapi-comparator-and-github-workflows.html.
But currently, there is no guarantee of strong consistency between OpenAPI and implementation. One way is to ensure during code review that for changes to the client and server, we first modify the openAPI definition file.
