### ISSUE TITLE
[Subtask] Add web UI support for fileset catalog

### ISSUE THREAD

**Issue by jerryshao** [datastrato/gravitino#2292]
### Describe the subtask

This issue tracks the work of add UI for fileset catalog. User can view the created filesets on the web UI.

### Parent issue

#1241

**Comment by coolderli** [comment]
@jerryshao Do we need some operations like `UploadFiles`, `DownloadFiles`, `PreviewFile`, and `ListFiles`?

- UploadFiles: There may some users who want to upload local files to a fileset.
- DownloadFiles: I'm not sure, maybe users want to open one file to test.
- PreviewFile: open a file. Some of my users like to open a file such as CSV on web UI, and take a look at the content.
- ListFiles: Some of our users like to look at the directory to check if the commit meets expectations. And see how many files or directories are in the specified path.

**Comment by jerryshao** [comment]
IMO, I would mainly focus on the read-only/visualization functions in this version. Things you mentioned are valuable but not so necessary, this can be achieved in different ways. Currently, we're lacking of UI person, so I would think of having a basic functionality first.

**Comment by coolderli** [comment]
> IMO, I would mainly focus on the read-only/visualization functions in this version. Things you mentioned are valuable but not so necessary, this can be achieved in different ways. Currently, we're lacking of UI person, so I would think of having a basic functionality first.

Got it. Thanks.
