### ISSUE TITLE
[Improvement] Add more unit tests for fileset

### ISSUE THREAD

**Issue by coolderli** [datastrato/gravitino#2306]
### What would you like to be improved?

There are some missing UT for `fileset` on : 
- TestEntityStore
- TestKvEntityStorage
- TestKvEntityStorage

In this issue, I will add them. 

### How should we improve?
add more UTs

### Parent issue
#1241

**Comment by coolderli** [comment]
@jerryshao @yuqi1129 @qqqttt123 
What do you think about this? Are there any other UTs that need to be added？

**Comment by justinmclean** [comment]
The Audit info related functions does't seem to have much coverage.

**Comment by jerryshao** [comment]
I saw there are some fixes in your E2E test about fileset support in kv storage, I think it is valuable to add more UTs.
