### ISSUE TITLE
[Improvement] In CatalogManager.java string is repeated

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#2320]
### What would you like to be improved?

The string "Catalog %s does not exist" is repeated several times.

### How should we improve?

Make it a string constant.

**Comment by caican00** [comment]
@justinmclean  Hi, I'd like to work on  the several issues raised recently about `string is repeated`, may I?

**Comment by justinmclean** [comment]
Sure go ahead please try and fix a group of them at once.
