### ISSUE TITLE
[Bug report] UI: Unable to show `createTime` of table

### ISSUE THREAD

**Issue by yuqi1129** [datastrato/gravitino#2344]
### Version

main branch

### Describe what's wrong

<img width="1567" alt="image" src="https://github.com/datastrato/gravitino/assets/15794564/091b0054-b972-40db-850a-42798206d95f">

### Error message and/or stacktrace

please see above

### How to reproduce

```shell
curl -X POST -H "Content-Type: application/json" -d '{"name":"test_25001","comment":"my test table","columns":[{"name":"integer1","type":"integer","comment":"id column comment","nullable":false, "autoIncrement": true},{"name":"long1","type":"long","comment":"name column comment","nullable":true},{"name":"float1","type":"float","comment":"name column comment","nullable":true},{"name":"double1","type":"double","comment":"name column comment","nullable":true},{"name":"decimal1","type":"decimal(20, 4)","comment":"name column comment","nullable":true},{"name":"date1","type":"date","comment":"name column comment","nullable":true},{"name":"time1","type":"time","comment":"name column comment","nullable":true},{"name":"string1","type":"string","comment":"name column comment","nullable":true},{"name":"binary1","type":"binary","comment":"name column comment","nullable":true}],"properties":{}, "indexes": [{"indexType": "PRIMARY_KEY", "name": "PRIMARY", "fieldNames":[["integer1"]]}, {"indexType": "UNIQUE_KEY", "name": "unique", "fieldNames":[["long1"], ["double1"], ["date1"], ["time1"]]}]}' http://localhost:8090/api/metalakes/test/catalogs/mysql_catalog/schemas/db1/tables

curl -X GET http://localhost:8090/api/metalakes/test/catalogs/mysql_catalog/schemas/db1/tables/test_25001
```

<img width="1955" alt="image" src="https://github.com/datastrato/gravitino/assets/15794564/204a751c-3e26-48a0-b09d-7dc91e6502ea">
<img width="1734" alt="image" src="https://github.com/datastrato/gravitino/assets/15794564/2c4ffa4e-76f8-45f9-9221-2f598f25f7c1">

**Comment by ch3yne** [comment]
You checked the different catalog.

test-**mysql_catalog2**-db1-test_25001
<img width="1505" alt="image" src="https://github.com/datastrato/gravitino/assets/17310559/4f7571a6-3e17-439c-a1f7-4b21e7f7774f">

test-**mysql_catalog**-db1-test_25001
<img width="1509" alt="image" src="https://github.com/datastrato/gravitino/assets/17310559/0c7443e3-43b6-46f8-a9ba-a0af38aba685">

**Comment by yuqi1129** [comment]
I see, my mistake, I visited catalog names that were different from the ones I used when creation.

**Comment by yuqi1129** [comment]
Close it as it's not a problem.
