### ISSUE TITLE
[Subtask] Add open API doc for fileset catalog

### ISSUE THREAD

**Issue by jerryshao** [datastrato/gravitino#2367]
### Describe the subtask

This issue tracks the work of adding an open API doc for fileset catalog, so that we can test it through the generated open API tool.

### Parent issue

#1241

**Comment by coolderli** [comment]
@jerryshao Are you working on this? I happen to be interested in the Open API recently and I would like to give it a try. Of course, I'd like to complete some other missing open APIs.

**Comment by jerryshao** [comment]
Sure, please go ahead.
