### ISSUE TITLE
[EPIC] Add messaging type catalog support for Gravitino

### ISSUE THREAD

**Issue by mchades** [datastrato/gravitino#2369]
### Describe the proposal

Gravitino currently has already supported relational and fieset type catalog, with the increased requirements of messaging data system(message queue), we should add the messaging type catalog support in Gravitino.

### Task list

- [x] #2370 
- [x] #2371 
- [x] #2466 
- [x] #2467 
- [x] #2468 
- [x] #2610 
- [x] #2611 
- [x] #2612 
- [x] #2613 
- [x] #2773 
- [x] #2774 
- [x] #2775 
- [x] #2614 
- [x] #1297

**Comment by YxAc** [comment]
@SteNicholas @zhoukangcn Can you take some time to join this discussion? thx.
