### ISSUE TITLE
[Subtask] Investigation on how managing Message Queue

### ISSUE THREAD

**Issue by mchades** [datastrato/gravitino#2370]
### Describe the subtask

This task tracks the work of investigating the current products that support managing Message Queue, and to see how we should design our own one.

### Parent issue

#2369

**Comment by mchades** [comment]
Here is the Investigation doc:

https://docs.google.com/document/d/1V2JfLDDlFTXe-kLEHMK3BhRiDQtPuvxKNoriWwqkEZ8/edit?usp=sharing

**Comment by YxAc** [comment]
good investigation!

**Comment by mchades** [comment]
I'm gonna close this issue since the Investigation is done, thanks a lot for helping review and discuss! @YxAc
