### ISSUE TITLE
[Subtask] Complete the metadata and interface design for messaging type catalog

### ISSUE THREAD

**Issue by mchades** [datastrato/gravitino#2371]
### Describe the subtask

This issue tracks the design of the messaging catalog

### Parent issue

#2369

**Comment by mchades** [comment]
Here is the initial design document:

https://docs.google.com/document/d/1NZKbM4e8iEMB0BOYD4nyzNhb3znGhxBXOE7OBx6_0zY/edit?usp=sharing

**Comment by YxAc** [comment]
> Here is the initial design document:
> 
> https://docs.google.com/document/d/1NZKbM4e8iEMB0BOYD4nyzNhb3znGhxBXOE7OBx6_0zY/edit?usp=sharing

I have some comments and pls take a look when you are free. @mchades 

Can you spare some time to join the discussion? @SteNicholas , thx.

**Comment by mchades** [comment]
Given the complexity of message schema management, supporting message schemas in Gravitino is a substantial task. 

Therefore, we do not intend to support schema management in the 0.5.0 version of the stream catalog. 

If you have any requirements or scenarios regarding schema management through the Gravitino stream catalog, feel free to leave comments and engage in discussions on the relevant issue.

Below is the design proposal for the 0.5.0 Gravitino stream catalog.
https://docs.google.com/document/d/1B1DTf_CR_wIqvEBLLfytUZ27-VGsdv-pZqsRkA4iANQ/edit?usp=sharing

**Comment by mchades** [comment]
Regarding "stream", users have provided feedback that they more easily associate it with batch processing, which is primarily used for data handling.

After discussion, we have decided to change the catalog type to "Messaging", referring to the type of data managed by this catalog.
