### ISSUE TITLE
[Bug report]  Gravitino-trino-connector is incompatible with Trino-435

### ISSUE THREAD

**Issue by theoryxu** [datastrato/gravitino#2376]
### Version

main branch

### Describe what's wrong

Hello fellows

There are some problems when gravitino-trino-connector（0.4.0） is working with Trino-435. I guess Trino-435 has some new interfaces that the connector has not yet implemented. Error information is as follows.

### Error message and/or stacktrace

![image](https://github.com/datastrato/gravitino/assets/6671568/14822c7d-0a84-4f4e-8237-d60b7f9896a2)

### How to reproduce

0.4.0 or above

**Comment by jerryshao** [comment]
@diqiu50 can you please take a look at this?

**Comment by diqiu50** [comment]
In the directory of the `graviton-trino-connector` plugin, some Trino jars have different versions than the Trino server.
```
ls   trino-*
-rw-r--r--@ 1 ice  staff   36737 Feb 28 16:14 trino-cache-426.jar
-rw-r--r--@ 1 ice  staff   20523 Feb 28 16:14 trino-matching-426.jar
-rw-r--r--  1 ice  staff  317755 Feb 28 16:24 trino-plugin-toolkit-426.jar
-rw-r--r--@ 1 ice  staff  976399 Feb 28 16:14 trino-spi-426.jar
```
I replaced the trino-plugin-toolkit-426.jar with trino-plugin-toolkit-435.jar, and now the graviton-connector works on Trino-435

So we need to find a way to solve this version issue.

**Comment by jerryshao** [comment]
I think you should not include trino dependencies, perhaps you may need to change the dependency from implementation to compileOnly?

**Comment by yuqi1129** [comment]
> I think you should not include trino dependencies, perhaps you may need to change the dependency from implementation to compileOnly?

Yes, he is going to remove all trino-related jars from the runtime class path.

**Comment by theoryxu** [comment]
@diqiu50 Hi bro, just for your information. There is another case that shows a different error stack trace.

When the node is a worker rather than a coodirator, the error msg is the following:

![image](https://github.com/datastrato/gravitino/assets/6671568/20347654-9736-470a-b804-ecedcc553ee2)

**Comment by diqiu50** [comment]
Ok, I will test it later

**Comment by jerryshao** [comment]
> @diqiu50 Hi bro, just for your information. There is another case that shows a different error stack trace.
> 
> When the node is a worker rather than a coodirator, the error msg is the following:
> 
> ![image](https://private-user-images.githubusercontent.com/6671568/309727508-20347654-9736-470a-b804-ecedcc553ee2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MTAzNjEsIm5iZiI6MTcwOTYxMDA2MSwicGF0aCI6Ii82NjcxNTY4LzMwOTcyNzUwOC0yMDM0NzY1NC05NzM2LTQ3MGEtYjgwNC1lY2VkY2M1NTNlZTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDVUMDM0MTAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODhhM2JlZmM3MTA5NzdhZTE4YWZiYzY1ZWZiZDlmOWFlYTk1YjYyMWFjMjI0MDY3OTk1YTM4M2VlYWE2ZTE5NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._gCv7UFQahgB_0a7kLdWeWCyCpW8AzOyAntjgmY-awE)

Can you please create a separate issue to track this bug?

**Comment by theoryxu** [comment]
@jerryshao, of course:  https://github.com/datastrato/gravitino/issues/2428
