### ISSUE TITLE
[Subtask] Add the relational entity store Garbage Collector

### ISSUE THREAD

**Issue by xloya** [datastrato/gravitino#2385]
### Describe the subtask

Currently, soft deletion is used for data processing under the `relational` entity store, so we need to create the processor like `KvGarbageCollector` to delete the useless reocrds.

### Parent issue

#1811

**Comment by YxAc** [comment]
I'll work on this issue. @xloya

**Comment by yuqi1129** [comment]
@YxAc 
Do you have time to work on this?

**Comment by YxAc** [comment]
> @YxAc Do you have time to work on this?

I will work on this on the recent weekend. @yuqi1129
