### ISSUE TITLE
[Improvement] dropSchema interface should support NoSuchSchemaException 

### ISSUE THREAD

**Issue by FANNG1** [datastrato/gravitino#2392]
### What would you like to be improved?

`dropSchema` interface just supports throw `NonEmptySchemaException`, it should also support `NoSuchSchemaException`.
```java
  boolean dropSchema(NameIdentifier ident, boolean cascade) throws NonEmptySchemaException;
```

**Comment by SteNicholas** [comment]
@FANNG1, could you assign this ticke to me?

**Comment by FANNG1** [comment]
> @FANNG1, could you assign this ticke to me?

sure, thanks for taking this.

**Comment by SteNicholas** [comment]
@FANNG1, I have checked `dropSchema` interface. Because this implementation of this interface return false for `NoSuchSchemaException`. This interface does not need to support `NoSuchSchemaException`. Meanwhile, all drop interfaces have the same behavior that returns false if not existed.

**Comment by FANNG1** [comment]
I think this should be improved, with `NoSuchSchemaException` we could know the exactly reason why drop schema failed.  The background is I'm developing spark-connector,  if Gravitino returns `NoSuchSchemaException`, I could catch it and throw corresponding exception to Spark.
@jerryshao @mchades do you agree?

```java
  public boolean dropSchema(NameIdentifier ident, boolean cascade) throws NonEmptySchemaException {
    try {
      clientPool.run(
          client -> {
            client.dropDatabase(ident.name(), false, false, cascade);
            return null;
          });
      LOG.info("Dropped Hive schema (database) {}", ident.name());
      return true;

    } catch (InvalidOperationException e) {
      throw new NonEmptySchemaException(
          e, "Hive schema (database) %s is not empty. One or more tables exist.", ident.name());

    } catch (NoSuchObjectException e) {
      LOG.warn("Hive schema (database) {} does not exist in Hive Metastore", ident.name());
    // should throw NoSuchSchemaException exception not return false
      return false;

    } catch (TException e) {
      throw new RuntimeException(
          "Failed to drop Hive schema (database) " + ident.name() + " in Hive Metastore", e);

    } catch (Exception e) {
      throw new RuntimeException(e);
    }
  }
```

**Comment by SteNicholas** [comment]
@FANNG1, does only the `dropSchema` need to be improved as above mentioned? What about other interfaces like `dropPartition`?

**Comment by jerryshao** [comment]
I agree with @SteNicholas , we should revisit all the dropXXX interfaces:

a) We should define a clear behavior of return value (false) and exception thrown.
b) We should have a consistent behavior for all the dropXXX interfaces.

**Comment by FANNG1** [comment]
duplicate with #1062,  will close this issue. cc @SteNicholas

**Comment by SteNicholas** [comment]
@jerryshao, @FANNG1, We could introduce `ignoreNotExist` parameter in drop interfaces. When `ignoreNotExist`  is true return false, otherwise throw exception.
