### ISSUE TITLE
[Improvement] add new interface to load all catalog info from Gravitino

### ISSUE THREAD

**Issue by FANNG1** [datastrato/gravitino#2396]
### What would you like to be improved?

Gravitino provides `listCatalog`  to get all catalog names and `loadCatalog` to get one catalog info. If getting all catalog information from Gravitino like in Spark or trino connector, we must combine the two operations, it will cost more time and increase the error process if load one catalog failed.

### How should we improve?

provide a new interface like `getAllCatalogs` to get all catalog info.

**Comment by mchades** [comment]
I suggest adding a `details` parameter to the existing `listCatalog` interface to indicate whether to return catalog information. This would help maintain compatibility with the original interface.

**Comment by LauraXia123** [comment]
Expanding the tree hierarchy relies on catalog type info, fileset type list filesets and others list tables.
I need the catalog more info when load catalog list.
