### ISSUE TITLE
[Improvement] spark-connector support alter namespace operation.

### ISSUE THREAD

**Issue by FANNG1** [datastrato/gravitino#2401]
### What would you like to be improved?

we should support set namespace properties in Spark sql like:
```sql
ALTER DATABASE inventory SET DBPROPERTIES ('Edited-by' = 'John', 'Edit-date' = '01/01/2001');
```

the current `alterNamespace` interface in `GravitinoCatalog.java` should be implemented.
```
 public void alterNamespace(String[] namespace, NamespaceChange... changes)
      throws NoSuchNamespaceException {
    throw new NotSupportedException("Doesn't support altering namespace");
  }
```

**Comment by PengleiShi** [comment]
@FANNG1 i will work on this issue.

**Comment by qqqttt123** [comment]
> @FANNG1 i will work on this issue.

Thanks for taking this issue. Please go ahead.
