### ISSUE TITLE
[Subtask] [spark-connector]: support CTAS and ITAS command

### ISSUE THREAD

**Issue by FANNG1** [datastrato/gravitino#2402]
### Describe the subtask

support CTAS and ITAS command

### Parent issue

#1227

**Comment by caican00** [comment]
Hi @FANNG1 May I know what kind of sql does ITAS correspond to?

**Comment by FANNG1** [comment]
> Hi @FANNG1 May I know what kind of sql does ITAS correspond to?

Insert table as select xx

**Comment by FANNG1** [comment]
> Hi @FANNG1 May I know what kind of sql does ITAS correspond to?
 
Insert table as select, like

```
 INSERT INTO students PARTITION (student_id = 444444)
     SELECT name, address FROM persons WHERE name = "Dora Williams";
```

**Comment by caican00** [comment]
> > Hi @FANNG1 May I know what kind of sql does ITAS correspond to?
> 
> Insert table as select, like
> 
> ```
>  INSERT INTO students PARTITION (student_id = 444444)
>      SELECT name, address FROM persons WHERE name = "Dora Williams";
> ```

I got it, thank you @FANNG1.
But why is it necessary in spark-connector?

**Comment by FANNG1** [comment]
Normally they are not related to spark-connector, but we should add integrate test in `SparkIT` to verify it works as expected because the `CTAS` and `ITAS` are common on productive env.

**Comment by caican00** [comment]
> Normally they are not related to spark-connector, but we should add integrate test in `SparkIT` to verify it works as expected because the `CTAS` and `ITAS` are common on productive env.

got it. thank you @FANNG1
