### ISSUE TITLE
[FEATURE] (trino-connector) Support system table `catalog` 

### ISSUE THREAD

**Issue by diqiu50** [datastrato/gravitino#2416]
### Describe the feature

Support the system table catalog to display all loaded catalog information in the Trino connector.
use can run this sql in Trino cli:
```
select * from gravition.system.catalog
```
the results are:
```
|   name     |  provider   |   properties                   |
-------------+------------ +--------------------------------+
|test.my-hive|     hive    | {"metastore_uril":"http:xxxx"} |
```

```
show create table gravition.system.catalog
```
the results are:

```
 CREATE TABLE gravitino.system.catalog (
    name varchar,
    provider varchar,
    properties map(varchar, varchar)
 )
```

**Comment by FANNG1** [comment]
what's the difference? compared to  `SHOW CATALOGS`

**Comment by jerryshao** [comment]
I think system catalog is quite important for gravitino, so we should carefully design it, not just for trino.

**Comment by diqiu50** [comment]
> what's the difference? compared to `SHOW CATALOGS`

The `Show catalog` command only lists the catalog names.

**Comment by diqiu50** [comment]
I have a design for the Gravitino System catalog  
@jerryshao @FANNG1 @qqqttt123 @yuqi1129  @mchades  Please take a reivew.
[Gravitino System catalog](https://docs.google.com/document/d/1yzDUxlT0kFX1dfFwrJkEqQhy7zu0RFJKfspma7cherU/edit#heading=h.e008761qlvs7)
