### ISSUE TITLE
[Bug report] A typo that mislead users in docs

### ISSUE THREAD

**Issue by theoryxu** [datastrato/gravitino#2419]
### Version

main branch

### Describe what's wrong

Hello fellows, there is a typo that could mislead users in docs.

### Error message and/or stacktrace

https://datastrato.ai/docs/0.4.0/trino-connector/installation#configuring-the-gravitino-connector
<img width="1110" alt="image" src="https://github.com/datastrato/gravitino/assets/6671568/0c27dd71-da43-4258-aa63-8150a136175f">

However, there are some differences in codes.
<img width="1276" alt="image" src="https://github.com/datastrato/gravitino/assets/6671568/907bbc08-77ef-4e43-8b4d-435f92e069e2">

### How to reproduce

just read docs and code

**Comment by jerryshao** [comment]
@theoryxu would you please submit a PR to fix this.

**Comment by theoryxu** [comment]
@jerryshao OK, no problem, bro.

**Comment by theoryxu** [comment]
@jerryshao 

I found the typo was fixed in the code base. Maybe someone needs to regenerate web assets?

https://github.com/datastrato/gravitino/pull/2136
https://github.com/datastrato/gravitino/pull/2142

**Comment by jerryshao** [comment]
Oh, I see, thanks a lot for your finding. We will update the website soon.
