### ISSUE TITLE
[Improvement] use simple catalog name in Trino connector

### ISSUE THREAD

**Issue by xiacongling** [datastrato/gravitino#2433]
### What would you like to be improved?

When using Gravitino Trino connector to access data, user need to use quoted catalog names like `"{metalake}.{catalog}"`. this may lead to compatible problems when migrating file-based catalogs to gravitino metalake. it should keep the original catalog names (usually without `{metalake}.` prefix) for Trino.

**Comment by jerryshao** [comment]
Thanks @xiacongling for your valid feedback, we're working on this thing, I think @shaofengshi may have more to tell.

**Comment by shaofengshi** [comment]
@xiacongling, @diqiu50 do you want to work on this?

**Comment by xiacongling** [comment]
hi, @shaofengshi, @diqiu50. i'd be happy to contribute. we are trying to make our file based catalogs being managed by gravitino and i'll be working on it in the next few days.

**Comment by diqiu50** [comment]
@xiacongling Ok, Thank you for the contribute.  Let's first discuss the solution.

**Comment by xiacongling** [comment]
Well, @diqiu50. The idea is pretty straightforward. Simplify the name when Gravitino invokes Trino's API and canonicalize it when Trino invokes Gravitino.

- When Gravitino creates and drops catalog via `com.datastrato.gravitino.trino.connector.catalog.CatalogInjector#injectCatalogConnector` and `com.datastrato.gravitino.trino.connector.catalog.CatalogInjector#removeCatalogConnector`, metalake prefix of `catalogName` need to be removed when these methods are invoked;
- When Trino create its internal catalog, it gets a delegated connector instance 
 via `com.datastrato.gravitino.trino.connector.catalog.CatalogConnectorManager#getCatalogConnector`. Here, metalake prefix should be added

The metalake name which will be omitted is provided by configuration property `gravitino.metalake` and an additional property `gravitino.simplify-catalog-names` (`false' by default) will be added for enabling this feature on demand.

Not sure if there's anything else I'm missing here. please point them out. thanks!

**Comment by xiacongling** [comment]
@diqiu50 here is a preview: https://github.com/datastrato/gravitino/pull/2547
