### ISSUE TITLE
[Bug report] In Gravitino UI unable to edit properties of catalogs

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#2441]
### Version

main branch

### Describe what's wrong

When editing a catalog you can't edit any of the key properties e.g. For PostgreSQL, you cannot edit jdbc-driver, jdbc-url, jdbc-user, jdbc-password or jdbc-database.

### Error message and/or stacktrace

N/A

### How to reproduce

Run the playground, click on the metalake, and click on the edit button for a catalog.

### Additional context

<img width="577" alt="image" src="https://github.com/datastrato/gravitino/assets/144504/990094a7-ee32-4e16-83cf-32c667434624">

**Comment by ch3yne** [comment]
The required fields for creating a catalog currently only support read-only, not support modification.
