### ISSUE TITLE
[Improvement] [spark-connector] refactor spark connector package name to keep consistent with trino

### ISSUE THREAD

**Issue by FANNG1** [datastrato/gravitino#2442]
### What would you like to be improved?

>
The package should be consistent with the trino.
com.datastrato.gravitino.spark.connector

move related class from  `com.datastrato.gravitino.spark` to `com.datastrato.gravitino.spark.connector`

**Comment by caican00** [comment]
Hi, @FANNG1 i would like to work on it and could you assign it to me? Thanks

**Comment by FANNG1** [comment]
@caican00 thanks for taking this, please note that besides related code, the UT under `com.datastrato.gravitino.spark` should also be refactored
