### ISSUE TITLE
[Subtask] support add table property and remove table property for spark-connector

### ISSUE THREAD

**Issue by FANNG1** [datastrato/gravitino#2448]
### Describe the subtask

please add related code to `com.datastrato.gravitino.spark.catalogGravitinoCatalog.java`,   transfrom Spark TableChange to Gravitino TableChange, you could refer to `renameTable` implement
```java
  public Table alterTable(Identifier ident, TableChange... changes) throws NoSuchTableException {
    throw new NotSupportedException("Doesn't support altering table for now");
  }
```

Related Spark SQL should add to `SparkIT.java`, please refer  https://spark.apache.org/docs/latest/sql-ref-syntax-ddl-alter-table.html

### Parent issue

#1227

**Comment by caican00** [comment]
Hi @FANNG1 could you assign it to me?

**Comment by caican00** [comment]
Hi @FANNG1  Should I support all tablechange in one pr？

**Comment by FANNG1** [comment]
> Hi @FANNG1 Should I support all tablechange in one pr？

One or two PR are ok for me, It's depends on you,  please note that some TableChange issues are assigned to other developers.

**Comment by caican00** [comment]
> > Hi @FANNG1 Should I support all tablechange in one pr？
> 
> One or two PR are ok for me, It's depends on you, please note that some TableChange issues are assigned to other developers.

got it.

**Comment by FANNG1** [comment]
There is an initial implement about UpdateColumnPostion #2454, you could reference to it if not familiar with spark-connector :)
