### ISSUE TITLE
[Subtask] support float and double type for spark-connector

### ISSUE THREAD

**Issue by FANNG1** [datastrato/gravitino#2451]
### Describe the subtask

should add related logic in `SparkTypeConverter` and add test in `TestSparkTypeConverter`
please refer below document
Spark date type: https://spark.apache.org/docs/latest/sql-ref-datatypes.html
Gravitino data type:  https://datastrato.ai/docs/0.4.0/manage-metadata-using-gravitino#gravitino-table-column-type

current implement:
```java
  public static Type toGravitinoType(DataType sparkType) {
    if (sparkType instanceof StringType) {
      return Types.StringType.get();
    } else if (sparkType instanceof BooleanType) {
      return Types.BooleanType.get();
    } else if (sparkType instanceof IntegerType) {
      return Types.IntegerType.get();
    }
    throw new UnsupportedOperationException("Not support " + sparkType.toString());
  }

  public static DataType toSparkType(Type gravitinoType) {
    if (gravitinoType instanceof Types.StringType) {
      return StringType$.MODULE$;
    } else if (gravitinoType instanceof Types.BooleanType) {
      return BooleanType$.MODULE$;
    } else if (gravitinoType instanceof Types.IntegerType) {
      return IntegerType$.MODULE$;
    }
    throw new UnsupportedOperationException("Not support " + gravitinoType.toString());
  }
```

### Parent issue

#1227

**Comment by ichuniq** [comment]
Hi can I work on this?

**Comment by FANNG1** [comment]
@ichuniq thanks for taking this, could you propose a pr after #2452 is merged? Spark provides a helper class `DataTypes` could simple the code.

**Comment by FANNG1** [comment]
@ichuniq ,  #2452  is merged, please use the lattest `DataTypes` way.
