### ISSUE TITLE
[Subtask] Optimize the UI design for metalake

### ISSUE THREAD

**Issue by shaofengshi** [datastrato/gravitino#2480]
### Describe the subtask

Today's Web UI uses a metalake list as the home page. While metalake is a logiacl container similar as an organization or tenant. It is not that frequent to manage the metalake. So I suggest to give less space and chance to show up the metalake list. In most of the time, user should see the catalog list after login to Gravitino. 

https://docs.google.com/document/d/1ArSfGXTFEl1eGIOwKS6LWC0yPvtH_9kyuB8aqLdun0U/edit#heading=h.w480bdwc9ba4

### Parent issue

#2418

**Comment by shaofengshi** [comment]
@LauraXia123 Laura, would you like to work on this?

**Comment by LauraXia123** [comment]
@shaofengshi Ok, I assign myself the issue
