### ISSUE TITLE
[Subtask] support complex types for spark-connector

### ISSUE THREAD

**Issue by caican00** [datastrato/gravitino#2498]
### Describe the subtask

Complex types have been supported in spark-connector now, such as: `ArrayType`, `MapType` and `StructType`

### Parent issue

https://github.com/datastrato/gravitino/issues/1552

**Comment by caican00** [comment]
i will work on this.

**Comment by FANNG1** [comment]
thanks for working on this, something you could refer:
[Trino and Gravitino type converter](https://github.com/datastrato/gravitino/blob/main/trino-connector/src/main/java/com/datastrato/gravitino/trino/connector/util/GeneralDataTypeTransformer.java)
[Hive type and Gravitino type converter](https://github.com/datastrato/gravitino/blob/main/catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/converter/ToHiveType.java)
[Spark type to Iceberg Type]( https://github.com/apache/iceberg/blob/main/spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/SparkTypeVisitor.java)
[Iceberg type to Spark Type](https://github.com/apache/iceberg/blob/c13c0c94daf9f6abc34cb109a1a4fd15c8a47a04/spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkSchemaUtil.java#L97)

**Comment by FANNG1** [comment]
this feature is expected in 0.5 which is released in 4.16,  is the time suitable for you?

**Comment by caican00** [comment]
> this feature is expected in 0.5 which is released in 4.16, is the time suitable for you?

It looks OK. I'll try my best.

**Comment by caican00** [comment]
Hi @hiirrxnn I was wondering if you would to solve this issue, which we talked about in https://github.com/datastrato/gravitino/issues/2494.

**Comment by caican00** [comment]
> Hi @hiirrxnn I was wondering if you would like to solve this issue, which we talked about in #2494.
> 
> If you are interested in it, please reply in the issue. Thank you.

i will continue on this because no one take it.
