### ISSUE TITLE
[Subtask] integrate pytest with gradle to run python test with CICD

### ISSUE THREAD

**Issue by shaofengshi** [datastrato/gravitino#2518]
### Describe the subtask

As discussed in https://github.com/datastrato/gravitino/pull/2280, integrate pytest with gradle, so that we can use gradle to build/test the python client module

This might be a good reference: https://attx-project.github.io/Building-with-Gradle.html

### Parent issue

#2229

**Comment by coolderli** [comment]
@shaofengshi Hi, Why do we use `gradle` to integrate pytest. We can use the Github CI to finish it. If we develop the python module, we can use `pytest` to have a test.

**Comment by shaofengshi** [comment]
> @shaofengshi Hi, Why do we use `gradle` to integrate pytest. We can use the Github CI to finish it. If we develop the python module, we can use `pytest` to have a test locally.

Peidian, with gradle integration, user can run the build in local, without dependency on Github. Is that reasonable? Just let me know if that will bring potential issue.

**Comment by coolderli** [comment]
> > @shaofengshi Hi, Why do we use `gradle` to integrate pytest. We can use the Github CI to finish it. If we develop the python module, we can use `pytest` to have a test locally.
> 
> @coolderli , with gradle integration, user can run the build in local, without dependency on Github. Is that reasonable? Just let me know if that will bring potential issue.

@shaofengshi Users can use `pytest` to have a test in local env. Some Python users may not be familiar with `gradle`. I'd like to use some Python tools to build and test the Python project.

**Comment by shaofengshi** [comment]
> > > @shaofengshi Hi, Why do we use `gradle` to integrate pytest. We can use the Github CI to finish it. If we develop the python module, we can use `pytest` to have a test locally.
> > 
> > 
> > @coolderli , with gradle integration, user can run the build in local, without dependency on Github. Is that reasonable? Just let me know if that will bring potential issue.
> 
> @shaofengshi Users can use `pytest` to have a test in local env. Some Python users may not be familiar with `gradle`. I'd like to use some Python tools to build and test the Python project.

Hi Peidian, I believe python user still use pytest to run the test. What Jerry suggests is, when run a "gradle build" command, it will call the "pytest" command in the client-python module. Not sure whether this solves your concern. @coolderli
