### ISSUE TITLE
[Bug report] Trino: incompatible interface/method signature

### ISSUE THREAD

**Issue by yuqi1129** [datastrato/gravitino#2577]
### Version

main branch

### Describe what's wrong

![image](https://github.com/datastrato/gravitino/assets/15794564/d7944e7f-5770-4437-9549-60f43dd01771)

### Error message and/or stacktrace

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project trino-gravitino: Compilation failure: Compilation failure: 
[ERROR] /Users/yuqi/project/trino/plugin/trino-gravitino/src/main/java/com/datastrato/gravitino/trino/connector/system/table/GravitinoSystemTableCatalog.java:[61,24] 不兼容的类型: 不存在类型变量E的.spi.block.SqlMap与io.trino.spi.block.Block一致
[ERROR] /Users/yuqi/project/trino/plugin/trino-gravitino/src/main/java/com/datastrato/gravitino/trino/connector/system/table/GravitinoSystemTableCatalog.java:[74,12] 对于Page(int,io.trino.spi.blocklockBuilder,io.trino.spi.block.BlockBuilder,io.trino.spi.block.MapBlockBuilder), 找不到合适的构造器
[ERROR]     构造器 io.trino.spi.Page.Page(io.trino.spi.block.Block...)不适用
[ERROR]       (varargs 不匹配; int无法转换为io.trino.spi.block.Block)
[ERROR]     构造器 io.trino.spi.Page.Page(int,io.trino.spi.block.Block...)不适用
[ERROR]       (varargs 不匹配; io.trino.spi.block.BlockBuilder无法转换为io.trino.spi.block.Block)
[ERROR] -> [Help 1]

### How to reproduce

Trino: version 435

**Comment by diqiu50** [comment]
@yuqi1129 I checked it in Trino 435, and we can build it successfully.
