### ISSUE TITLE
[Improvement] [spark-connector] add IntervalYearType and IntervalDayType for spark connector

### ISSUE THREAD

**Issue by FANNG1** [datastrato/gravitino#2596]
### What would you like to be improved?

you could refer #2484 add IntervalYearType and IntervalDayType support for spark connector,  add transform logic in `SparkTypeConverter` and add test in `TestSparkTypeConverter`

**Comment by FANNG1** [comment]
@mchades ,  I checked [spark types](https://spark.apache.org/docs/3.4.0/sql-ref-datatypes.html),  Gravitino `IntervalYearType` and `IntervalDayType` couldn't convert to Spark `YearMonthIntervalType(startField, endField)` and `DayTimeIntervalType(startField, endField)` because they have parameters. Yes?

**Comment by mchades** [comment]
Gravitino `IntervalYearType` can convert to Spark `YearMonthIntervalType(YEAR, MONTH)`
Gravitino `IntervalDayType` can convert to Spark `DayTimeIntervalType(DAY, SECOND)`

FYI: https://substrait.io/types/type_classes/

**Comment by charliecheng630** [comment]
@FANNG1 @mchades I would like to work on this.

**Comment by FANNG1** [comment]
> @FANNG1 @mchades I would like to work on this. After tracing code, should `IntervalYearType` and `IntervalDayType` be added with parameters (startField, endField)?

I'm not sure about this, How should Spark `DayTimeIntervalType(DAY, MINUTE)` translate to Gravitino? @mchades

**Comment by charliecheng630** [comment]
Do we need to add parameters in [Types](https://github.com/datastrato/gravitino/blob/main/api/src/main/java/com/datastrato/gravitino/rel/types/Types.java)? If needed, I would like to implement.

**Comment by mchades** [comment]
I think we should understand how the `interval` type is actually used in Spark in order to determine if additional parameters are needed. 
Could you provide code examples of how Spark defines and reads/writes the interval type? @FANNG1

**Comment by FANNG1** [comment]
Take `YearMonthIntervalType` for example, it has two parameters `startField` and `endFiled` which could be `YEAR` and `MONTH`, valid types are:
  * interval year,  like  `INTERVAL '100' YEAR`
  * interval month,   like  `INTERVAL '2' MONTH`
  * interval year to month,  like  `INTERVAL '100 2' YEAR TO MONTH`

```scala
  override val typeName: String = {
    val startFieldName = fieldToString(startField)
    val endFieldName = fieldToString(endField)
    if (startFieldName == endFieldName) {
      s"interval $startFieldName"
    } else if (startField < endField) {
      s"interval $startFieldName to $endFieldName"
    } else {
      throw QueryCompilationErrors.invalidDayTimeIntervalType(startFieldName, endFieldName)
    }
  }
```

**Comment by mchades** [comment]
This issue should be considered together with #2373

**Comment by FANNG1** [comment]
> Gravitino `IntervalYearType` can convert to Spark `YearMonthIntervalType(YEAR, MONTH)` Gravitino `IntervalDayType` can convert to Spark `DayTimeIntervalType(DAY, SECOND)`
> 
> FYI: https://substrait.io/types/type_classes/

seems we could do the transform like this, because  the simpleString of `YearMonthIntervalType` is `YearMonthIntervalType(YEAR, MONTH)` which is used to transform to hive types in spark.  @mchades WDYT?

**Comment by mchades** [comment]
> > Gravitino `IntervalYearType` can convert to Spark `YearMonthIntervalType(YEAR, MONTH)` Gravitino `IntervalDayType` can convert to Spark `DayTimeIntervalType(DAY, SECOND)`
> > FYI: https://substrait.io/types/type_classes/
> 
> seems we could do the transform like this, because the simpleString of `YearMonthIntervalType` is `YearMonthIntervalType(YEAR, MONTH)` which is used to transform to hive types in spark. @mchades WDYT?

we can convert it like this first.

**Comment by FANNG1** [comment]
@charliecheng630 do you still like to work on this?

**Comment by FANNG1** [comment]
@charliecheng630 , this issue is expected to be fix in 0.5 in next week, If you didn't have time, I'd like to work on this.

**Comment by charliecheng630** [comment]
@FANNG1 I probably won't make it in time to work on this issue.

**Comment by FANNG1** [comment]
Spark don't support create table or load table with IntervalXXType column, not plan to support it unless a real need.
