### ISSUE TITLE
[Improvement] move catalog property constant to bundled-catalog

### ISSUE THREAD

**Issue by FANNG1** [datastrato/gravitino#2617]
### What would you like to be improved?

now catalog property constant is in XXPropertiesMetadata like `LOCATION` in `HiveTablePropertiesMetadata`,  it could only accessed by specific catalogs, couldn't used by trino or spark connector. 

### How should we improve?

we could move the property constant to bundled-catalog, like add HivePropertiesConstant to encope hive related properties like `LOCATION`, `FORMAT`.

**Comment by jerryshao** [comment]
Fixed
