### ISSUE TITLE
[Subtask] [spark connector] support hive table location properties

### ISSUE THREAD

**Issue by FANNG1** [datastrato/gravitino#2621]
### Describe the subtask

supports location properties, transform from Spark location to Gravitino location,   please add UT to `TestHivePropertiesConverter`, add  IT to `SparkHiveCatalogIT`.

```sql
CREATE TABLE xx LOCATION xxx
```

### Parent issue

#1549

**Comment by FANNG1** [comment]
@Yangxuhao123 you could refer #2605

**Comment by FANNG1** [comment]
> Sorry, I've dealt with some things during this time. Have you completed this part of the work? @FANNG1

ok, will wait to see if some other persons could do this.

**Comment by FANNG1** [comment]
> Sorry, I've dealt with some things during this time. Have you completed this part of the work? @FANNG1

No, I haven't finished it, do you have time to work on this?

**Comment by charliecheng630** [comment]
May I take on this issue?

**Comment by FANNG1** [comment]
> May I take on this issue?

@Yangxuhao123 is working on this

**Comment by charliecheng630** [comment]
@FANNG1 Should I support `external` property?
`CREATE EXTERNAL TABLE  xxx LOCATION xxx`

**Comment by charliecheng630** [comment]
@FANNG1 [the key of location property in Gravitino](https://github.com/datastrato/gravitino/blob/main/catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/HiveSchemaPropertiesMetadata.java#L17) is same as Spark, do we still need to modify the converter?

**Comment by FANNG1** [comment]
> @FANNG1 [the key of location property in Gravitino](https://github.com/datastrato/gravitino/blob/main/catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/HiveSchemaPropertiesMetadata.java#L17) is same as Spark, do we still need to modify the converter?

I think it's necessary to change it explicitly, they are happens to the same.
