### ISSUE TITLE
[Bug report] Incomplete description of fileset API in openapi.yml

### ISSUE THREAD

**Issue by LauraXia123** [datastrato/gravitino#2624]
### Version

main branch

### Describe what's wrong

FilesetCreateRequest interfaces have one nullable field "storageLocation", which is inaccuracy. 
For external fileset, the storageLocation must be set.
Storage location must be set for fileset  when it's catalog and schema location are not set.
<img width="722" alt="image" src="https://github.com/datastrato/gravitino/assets/9210625/6b12b117-ca5c-4068-b9da-d1b35ee695b6">
I think need to give more info about the field "storageLocation" in openapi.yml

And the eg about storageLocation in FilesetCreatRequest is not correct, while is not supprt for s3 right now.
<img width="538" alt="image" src="https://github.com/datastrato/gravitino/assets/9210625/fed25205-5627-465d-921d-8a2b39cbeabf">

The nullable field "type" must one of the values accepted for Enum class: [EXTERNAL, MANAGED]
<img width="756" alt="image" src="https://github.com/datastrato/gravitino/assets/9210625/1d735782-acbc-4ef1-b6a9-7930dd63e5fc">

### Error message and/or stacktrace

<img width="735" alt="image" src="https://github.com/datastrato/gravitino/assets/9210625/fc08227f-e13b-4fc9-a6c5-ad030b642d0a">
<img width="915" alt="image" src="https://github.com/datastrato/gravitino/assets/9210625/eca254e5-2f07-490f-a533-092912e7bb59">
<img width="930" alt="image" src="https://github.com/datastrato/gravitino/assets/9210625/8ba71ecc-0d6b-41cc-a876-aa48529fe6ff">

### How to reproduce

About the field "storageLocation" and "type", add more info, and give more correct eg in `FilesetCreatRequest` in openapi.yml

**Comment by jerryshao** [comment]
Hi @coolderli would you please help to improve the yml doc, seems currently there's several ambiguities here that makes users hard to understand, would you please help to add more descriptions here?

**Comment by coolderli** [comment]
> Hi @coolderli would you please help to improve the yml doc, seems currently there's several ambiguities here that makes users hard to understand, would you please help to add more descriptions here?

@jerryshao No ploblem. I'll finish it.
