### ISSUE TITLE
[Improvement] [trino-connector] Gravitino's dynamic catalogs should be loaded before server is ready

### ISSUE THREAD

**Issue by xiacongling** [datastrato/gravitino#2627]
### What would you like to be improved?

Now, catalogs managed by Gravitino are loaded in another thread when Trino starting up. These catalogs may not be loaded before server is ready for serving and queries will fail.

### How should we improve?

load catalog in metalake immediately when gravitino connector is created in current thread

**Comment by jerryshao** [comment]
@diqiu50 @yuqi1129 please take a look.
