### ISSUE TITLE
[Bug report] Create fileset api failed

### ISSUE THREAD

**Issue by LauraXia123** [datastrato/gravitino#2629]
### Version

main branch

### Describe what's wrong

I can create fileset this morning, set the `"storageLocation": "/Users/xiaqian/Documents/GitHub" `.
Then test the `Drop fileset` api which it successful, but drop my repository under my GitBub file directory too.
And I clone the repository again, found cannot create fileset  by the same way

### Error message and/or stacktrace

<img width="981" alt="image" src="https://github.com/datastrato/gravitino/assets/9210625/17c52aed-525f-4c45-8125-1a2a5884a28d">

### How to reproduce

curl -L -X POST 'http://localhost:8090/api/metalakes/test/catalogs/catalogType/schemas/schemas1/filesets' \ 
-H 'Content-Type: application/json' \
-H 'Accept: application/vnd.gravitino.v1+json' \
--data-raw '{
  "name": "fileset11",
  "type": "managed",                                          
  "comment": "This is a comment",
  "storageLocation": "/Users/xiaqian/Documents/GitHub/fileset",        
  "properties": {
    "key1": "value1",
    "key2": "value2"
  }
}'

I create new file directory for storageLocation
<img width="611" alt="image" src="https://github.com/datastrato/gravitino/assets/9210625/6e6a388e-481a-4c93-aa2e-4d99a12b1d25">

**Comment by jerryshao** [comment]
This seems like a codebase issue, can you please rebuild gravitino to test again? I don't have an issue in my local environment.

**Comment by LauraXia123** [comment]
I tested it after a rebuild.

**Comment by jerryshao** [comment]
It's weird, I don't think there's a problem here. IT should already cover this.

@coolderli did you see an issue here?

**Comment by LauraXia123** [comment]
I've resolved the issue. I tested it after a rebuild  but had not restart. Sorry for that.
