### ISSUE TITLE
[Subtask] Add the gvfs user doc

### ISSUE THREAD

**Issue by xloya** [datastrato/gravitino#2640]
### Describe the subtask

Add user documentation for gvfs usage.

### Parent issue

#1616

**Comment by jerryshao** [comment]
@xloya will you work on this?

**Comment by jerryshao** [comment]
I'm just asking if you plan to do it, if not I can do it later on, if you plan to do so, you can go ahead.

**Comment by xloya** [comment]
> I'm just asking if you plan to do it, if not I can do it later on, if you plan to do so, you can go ahead.

Okay, i will do this today.
