### ISSUE TITLE
[Improvement] Replace TypeScript with JavaScript in the web

### ISSUE THREAD

**Issue by ch3yne** [datastrato/gravitino#2643]
### What would you like to be improved?

Replace TypeScript with JavaScript for the consistency of the frontend code.

### How should we improve?

Modify the code in the related files:
- `web/types/*`
- `web/lib/enums/*`
- `web/lib/utils/axios/*`
- `web/src/components/ColumnTypeChip.js#L7`

Replace `/web/tsconfig.json` to `web/jsconfig.json`.

**Comment by hiirrxnn** [comment]
I would like to work on this !

**Comment by hiirrxnn** [comment]
Please review draft PR #2662 and advice regarding how other files have to be changed.
