### ISSUE TITLE
[Improvement] Stress test report on gravitino fileset API

### ISSUE THREAD

**Issue by bknbkn** [datastrato/gravitino#2647]
### What would you like to be improved?

Tests show that  the `list` api on **main branch** have bad performance, 

**There's 2 metalakes, 1 catalogs,10 schemas, 100 fileset in the test environment**

**The sever has 1 cpu and 4GB mem**

config in jetty is:
  - gravitino.server.webserver.maxThreads = 200 (The max thread size of the built-in web server) 
  - gravitino.server.webserver.stopTimeout = 30000 (The stop timeout of the built-in web server)
  -  gravitino.server.webserver.threadPoolWorkQueueSize = 2000 

We use **500 client** to test，here's some of the result data：

![image](https://github.com/datastrato/gravitino/assets/67318028/1398ded8-9e15-4e2d-b6be-c53e405c5647)

the list request response time is very long：

![image](https://github.com/datastrato/gravitino/assets/67318028/61f05236-1167-4851-bca6-67b6d1166592)

And the TPS is not hign (about 100+) :

![image](https://github.com/datastrato/gravitino/assets/67318028/f61be09a-18a4-44c2-9eee-0593b94e9607)

At the same time on the server side, cpu is not fully used ：

![image](https://github.com/datastrato/gravitino/assets/67318028/3a51733e-438e-4277-9691-825522edeeba)

### How should we improve?

I wonder if **list** requests can be optimized more.

And other observable phenomenon is that  same type of **read request** seem to block each other. For example, when testing  listCatalog, the response of other listCatalog request will be significantly slower, but the response of listMetalake will not be affected.  I think this mutual exclusion between read requests is unreasonable, May be there is a lock between read requests.

**Comment by YxAc** [comment]
@bknbkn can you offer detailed test documentation with google doc? Thx.

**Comment by bknbkn** [comment]
ok，I will offer more test case and test detail in google later

**Comment by bknbkn** [comment]
@YxAc @yuqi1129 
More test details are being updated. Before that, I found that the ```list api``` uses a write lock, which should be the cause of the slow speed. However, the ```list api``` is very frequently used in actual use (especially when using the UI interface, the list often It is the pre-operation of get). This write lock seems to be deliberately designed like this. I wonder the reason for the original design and whether there is anything that can be improved.

![ab867bae-ff4d-4bae-b8b6-1e1d5aba30d9](https://github.com/datastrato/gravitino/assets/67318028/090ceaa8-53ca-439b-b74f-afcdc4c83944)

**Comment by yuqi1129** [comment]
@bknbkn 
Thanks for your hard work on it. Indeed the write lock is deliberately designed, please see https://github.com/datastrato/gravitino/pull/2260#discussion_r1495156151, in our initial design, list operation is far less than `get`, `load` operations in real scenario, so I chose the second solution in https://github.com/datastrato/gravitino/pull/2260#discussion_r1495156151. I'm also working on improving Gravitino's overall performance of Gravitino server, so we'd better find a compromise about it and needs more test cases and real scenario, can you share your real-world environment, such as the percentage of Read/Write/List operations?

**Comment by bknbkn** [comment]
@yuqi1129 Thanks for the reply, I will provide a reference scenario. When I use Web UI, the whole usage process is like this:

First it will list all metalakes (use list metalak):

![image](https://github.com/datastrato/gravitino/assets/67318028/85ffc51a-4187-4804-a14a-24bb0b00128b)

And then I choose one metalake, it will use get metalake api:

![image](https://github.com/datastrato/gravitino/assets/67318028/b0d1ff61-1c92-4b11-b2f5-3c9447879b0e)

Then list catalogs will be used:

![image](https://github.com/datastrato/gravitino/assets/67318028/56d7132e-e1b5-4c2a-aeaa-c511ec5e2df6)

After the above operations, I will use get catalog to obtain a specific catalog.

so in this scenario, the list/get will be 1 : 1

**Comment by bknbkn** [comment]
@YxAc @yuqi1129 Updated preliminary test result in google doc,  you can take a look 
https://docs.google.com/document/d/1GPynb8SbxcIU2s6h3W-mPqeRVqmv0ac9_rBJm63awqs/edit
