### ISSUE TITLE
[Subtask]  support UpdateColumnNullable in AlterTable for spark connector

### ISSUE THREAD

**Issue by FANNG1** [datastrato/gravitino#2649]
### Describe the subtask

please add related code to `com.datastrato.gravitino.spark.catalogGravitinoCatalog.java`, transfrom Spark TableChange to Gravitino TableChange, you could refer to #2502 , Hive doesn't support update column nullable for now, so no need to add integrate test.
`
  public Table alterTable(Identifier ident, TableChange... changes) throws NoSuchTableException {
  }
`

### Parent issue

#1227

**Comment by ichuniq** [comment]
Hi I would like to work on this

**Comment by FANNG1** [comment]
@ichuniq , you needn't add `testAlterTableUpdateColumnNullability()` in `SparkCommonIT.java`, because it wouldn't work. you only need to implement convert logic and add unit test.
