### ISSUE TITLE
[Subtask] support UpdateColumnDefaultValue in AlterTable for spark connector

### ISSUE THREAD

**Issue by FANNG1** [datastrato/gravitino#2650]
### Describe the subtask

please add related code to com.datastrato.gravitino.spark.catalogGravitinoCatalog.java, transfrom Spark UpdateColumnDefaultValue to Gravitino UpdateColumnDefaultValue, you could refer to https://github.com/datastrato/gravitino/pull/2502 , Hive doesn't support update column default value for now, so no need to add integrate test.
```
public Table alterTable(Identifier ident, TableChange... changes) throws NoSuchTableException { }
```

### Parent issue

#1227

**Comment by charliecheng630** [comment]
I would like to work on this. @FANNG1

**Comment by FANNG1** [comment]
@charliecheng630  thanks for taking this.

**Comment by FANNG1** [comment]
@charliecheng630 , I just noticed that Gravitino doesn't support `UpdateColumnDefaultValue` for now, we need to support it in a separate issue before adding it to Spark. cc @mchades

**Comment by charliecheng630** [comment]
@mchades Can I create a separate issue to perform `UpdateColumnDefaultValue` for Gravitino?

**Comment by mchades** [comment]
> @mchades Can I create a separate issue to perform `UpdateColumnDefaultValue` for Gravitino?

Yeah, I was also thinking of doing that. Go ahead and do that. 😄

**Comment by charliecheng630** [comment]
@FANNG1  @mchades  The  `defautValue` of UpdateColumnDefaultValue in spark connector is [`String`](https://github.com/apache/spark/blob/master/sql/catalyst/src/main/java/org/apache/spark/sql/connector/catalog/TableChange.java#L234), but in Gravitino it should be [`Expression`](https://github.com/datastrato/gravitino/blob/main/api/src/main/java/com/datastrato/gravitino/rel/TableChange.java#L1152).
Can the default value of a string be converted into an expression?

**Comment by mchades** [comment]
Maybe you can try to convert it to `StringLiteral`, I guess the Spark engine will do the implicit conversion
