### ISSUE TITLE
[Bug report] UI: The error message box does not fade away automatically

### ISSUE THREAD

**Issue by danhuawang** [datastrato/gravitino#2688]
### Version

main branch

### Describe what's wrong

It's confusing when users switch schemas or tables on UI
<img width="1477" alt="image" src="https://github.com/datastrato/gravitino/assets/154112360/e8c2461e-7068-49ce-b132-77ce8a7b2e42">

### Error message and/or stacktrace

N/A

### How to reproduce

N/A

**Comment by ch3yne** [comment]
@danhuawang Is setting it to 4 seconds reasonable?
