### ISSUE TITLE
[Subtask] [spark-connector] support hive external table

### ISSUE THREAD

**Issue by FANNG1** [datastrato/gravitino#2736]
### Describe the subtask

support spark sql create external table:
```sql
CREATE EXTERNAL TABLE family (id INT, name STRING)
```
For external table, spark stores `external` = `true` in properties, while Gravitino requires `tableType` = `EXTERNAL_TABLE` in properties, we should do the transform in `HivePropertiesConverter`, add UT in `TestHivePropertiesConverter`, add integrate test in `SparkHiveCatalogIT`

please refer to  #2605

### Parent issue

#1549

**Comment by charliecheng630** [comment]
I would like to work on this. @FANNG1

**Comment by FANNG1** [comment]
@charliecheng630  thanks for taking this.
