### ISSUE TITLE
[Improvement] Add an option for setTestOnBorrow method  in gravitino configuration file

### ISSUE THREAD

**Issue by danhuawang** [datastrato/gravitino#2786]
### What would you like to be improved?

`basicDataSource.setTestOnBorrow(true);`  is required to be updated as `basicDataSource.setTestOnBorrow(false);`   before performance testing

Suggest to provide an option in config file to switch the parameter value

<img width="1046" alt="image" src="https://github.com/datastrato/gravitino/assets/154112360/2923c88f-aca2-4c93-ade6-afa9dd33ed22">

**Comment by jerryshao** [comment]
@yuqi1129 don't forget to do this.

**Comment by yuqi1129** [comment]
> @yuqi1129 don't forget to do this.

Got it.
