### ISSUE TITLE
[Improvement] Files with incorrect headers / misisng license information

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#2799]
### What would you like to be improved?

Looks like two files look like they are 3rd party code and they need to retain the original headers:
/clients/client-python/gravitino/utils/exceptions.py
/clients/client-python/gravitino/utils/http_client.py

Looks like they come from https://github.com/Kyligence/kylinpy if so this license needs to be added and mentioned in LICENSE.

### How should we improve?

Remove datastrato headers and add the original headers (if they exist). Update LICENSE and LICENSE.bin to mention files and license.

**Comment by shaofengshi** [comment]
let me double check with the author.

**Comment by zhaoyongjie** [comment]
@shaofengshi @justinmclean the initial kylinpy creator here. Yes, the `http_client.py` and `exceptions.py` were copied and modified from the kylinpy. Kylinpy is under [MIT license](https://pitt.libguides.com/openlicensing/MIT#:~:text=Users%20of%20software%20using%20an,and%20the%20X%20Windows%20System.) so we are able to use and modify it.

**Comment by justinmclean** [comment]
When copying any 3rd party code, you need to mention that in LICENSE and LICENSE.bin and copy the license. We also can't put our own headers on any 3rd party files.

**Comment by zhaoyongjie** [comment]
> When copying any 3rd party code, you need to mention that in LICENSE and LICENSE.bin and copy the license. We also can't put our own headers on any 3rd party files.

<img width="1051" alt="image" src="https://github.com/datastrato/gravitino/assets/2016594/f206d0bb-3fdd-4a51-9836-505022211801">

How about your thoughts from the declaration of MIT?

**Comment by justinmclean** [comment]
I'm not 100% sure what you mean by that question. If you are asking if the MIT license is compatible with the Apache 2.0 license then yes it is, but we still need to abide by the MIT license terms.

**Comment by xunliu** [comment]
hi @justinmclean 
Do you mean we need add code reference in the

### NOTICE
```
Kyligence kylinpy
Copyright xxxx-xxxx The XXXX Company information
```
like this?
https://github.com/datastrato/gravitino/blob/main/NOTICE#L31C1-L32C51

### LICENSE
```
Kylinpy
./kylinpy/client/client.py
```
like this?
https://github.com/datastrato/gravitino/blob/main/LICENSE#L275

**Comment by justinmclean** [comment]
As it is MIT-licensed, nothing needs to be added to the NOTICE. It needs to be added to LICENSE under the MIT section, and also to LICENSE.bin and the full license text needs to be added to the license directory.

**Comment by shaofengshi** [comment]
https://github.com/datastrato/gravitino/pull/2960 @justinmclean @zhaoyongjie I raised a PR, please review, thank you!
