### ISSUE TITLE
[Improvement] File with ioncorrect header / missing LICENSE information

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#2803]
### What would you like to be improved?

This file looks to be a 3rd party file from https://github.com/trinodb/trino
gravitino/trino-connector/src/main/java/com/datastrato/gravitino/trino/connector/system/GravitinoSystemConnector.java

### How should we improve?

Replace the original header and list file and license in LICENSE/LICENSE.bin

**Comment by diqiu50** [comment]
This file was written by me; it was not copied from Trino.

**Comment by justinmclean** [comment]
While you may have written most of the file are you 100% positive you didn't copy any code from MockConnector.java? There is a snippet of code that 82% matches what is in MockConnector.java.

**Comment by diqiu50** [comment]
Yes, I did not copy this class. The methods in this class are basically the simplest implementations of interfaces.

**Comment by justinmclean** [comment]
OK thanks I think we can close this.
