### ISSUE TITLE
[Improvement] Possible concurrent issue about tree lock

### ISSUE THREAD

**Issue by yuqi1129** [datastrato/gravitino#2829]
### What would you like to be improved?

Currently, we are using this design to implement tree lock.

- list -> parent write lock
- create -> itself write lock.
- load -> itself read lock
- alter -> itself write lock
- drop -> itself write lock

The following scenario will happen:

 - Thread1 get entity1 write lock
 - Thread1 rename entity1 to entity2 
 - Thread2 get entity2 write lock
 - Thread 1 release entity1 lock
 - Thread 2 release entity2 lock

It appears that the tree lock does not effectively address concurrent issues in this situation, so we should consider it. Author implementation can prevent these types of cases.

- list -> parent read lock
- create -> parent write lock
- load -> itself read lock
- alter -> parent write lock
- drop -> parent write lock

**Comment by bknbkn** [comment]
It seems that all write operations need to add parent locks, or add the same name check. You can consider this patch. https://github.com/datastrato/gravitino/pull/2732

**Comment by yuqi1129** [comment]
> It seems that all write operations need to add parent locks, or add the same name check. You can consider this patch. #2732

Yeah, I'm considering and evaluating it.

**Comment by jerryshao** [comment]
This is fixed by #2732
