### ISSUE TITLE
[Improvement] Increase retry times for Hive container

### ISSUE THREAD

**Issue by yuqi1129** [datastrato/gravitino#2848]
### What would you like to be improved?

In some cases, Hive container can't be luanched within a short time, it seems that the current retry count (5) is not enough.

The following is a case:

CI: https://github.com/datastrato/gravitino/actions/runs/8610140778/job/23595195265?pr=2820

HDFS data node log：
[hadoop-root-datanode-gravitino-ci-hive.log](https://github.com/datastrato/gravitino/files/14913575/hadoop-root-datanode-gravitino-ci-hive.log)
<img width="1873" alt="image" src="https://github.com/datastrato/gravitino/assets/15794564/6239e5ff-4b47-4795-a9e2-d8c8a24de1ac">

The Data node instance is not ready until `2024-04-09 04:17:44,603`.

Integration-test log:
[integration-test-integration-test.log](https://github.com/datastrato/gravitino/files/14913590/integration-test-integration-test.log)

<img width="1575" alt="image" src="https://github.com/datastrato/gravitino/assets/15794564/695326a5-e8b1-454e-aaad-50ce15030277">

Retry logic stops at `2024-04-09 04:16:48` and throws an exception that 'Hive container is not ready'

 

### How should we improve?

Increase the retry limits.

**Comment by yuqi1129** [comment]
@mchades @jerryshao 
What's your opinion on it?

**Comment by jerryshao** [comment]
I think we can increase the timeout, as well as using awaitability to control poll interval to avoid waiting for so long time.

**Comment by mchades** [comment]
I intend to refactor the `checkContainerStatus` method to pass the timeout parameter instead of the retry count.

**Comment by mchades** [comment]
Is this issue duplicated with https://github.com/datastrato/gravitino/issues/2270 ?

**Comment by yuqi1129** [comment]
It's close to duplicating others.
