### ISSUE TITLE
[Improvement] refactor  gravitino catalog to support FunctionCatalog

### ISSUE THREAD

**Issue by FANNG1** [datastrato/gravitino#2903]
### What would you like to be improved?

we must support FunctionCatalog in #2709, it's better to register specific catalog to Spark catalog manager,  the specific catalog could implement `FunctionCatalog`

### How should we improve?

#1227

**Comment by coolderli** [comment]
@FANNG1 Does this mean that we will support Functions in Gravitino? So we can list functions and get function.

**Comment by FANNG1** [comment]
> @FANNG1 Does this mean that we will support Functions in Gravitino? So we can list functions and get function.

No, supports functions in Gravitino are long term, this issue aims to refactor GravitinoCatalog to easily implement `FunctionCatalog` to support partitions for Iceberg.
