### ISSUE TITLE
[Improvement] Synchronize "getWrokingDirectory" to match the synchronization on "setWorkingDirectory".

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#2910]
### What would you like to be improved?

Both the getter and setter should be synchronized so that unexpected things might happen, currently, getWrokingDirectory could be called then another thread is in the middle of setWorkingDirectory.

### How should we improve?

both methods should be synchronized
clients/filesystem-hadoop3/src/main/java/com/datastrato/gravitino/filesystem/hadoop/GravitinoVirtualFileSystem.java

**Comment by xloya** [comment]
@justinmclean @jerryshao I'll open a PR to fix the issue.
