### ISSUE TITLE
[Improvement] Possible issue with dropSchema in HadoopCatalogOperations.java

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#2913]
### What would you like to be improved?

In catalogs/catalog-hadoop/src/main/java/com/datastrato/gravitino/catalog/hadoop/HadoopCatalogOperations.java
the dropSchema method always returns true even if the schema is not dropped, this might be unexpected.

### How should we improve?

Look at the return values more carefully and only return true if the schema is dropped.

**Comment by charliecheng630** [comment]
I would like to work on this. :)

**Comment by justinmclean** [comment]
Thanks for offering to work on this.
