### ISSUE TITLE
[Improvement] Use Collections.emptyList() rather than Collections.EMPTY_LIST

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#2916]
### What would you like to be improved?

Use of Collections.EMPTY_LIST can cause ClassCastException exactions at runtime, better to let the compiler catch these sort of issues.

### How should we improve?

Fix instances in:
trino-connector/src/main/java/com/datastrato/gravitino/trino/connector/catalog/hive/HiveMetadataAdapter.java
trino-connector/src/main/java/com/datastrato/gravitino/trino/connector/catalog/iceberg/IcebergMetadataAdapter.java

**Comment by charliecheng630** [comment]
I would like to work on this. :)

**Comment by justinmclean** [comment]
Thanks for your contribution!
