### ISSUE TITLE
[Bug report] Doc: incorrect description "Doesn't support cascade dropping schema" in mysql catalog part

### ISSUE THREAD

**Issue by danhuawang** [datastrato/gravitino#2942]
### Version

main branch

### Describe what's wrong

https://datastrato.ai/docs/0.4.0/jdbc-mysql-catalog
<img width="1447" alt="image" src="https://github.com/datastrato/gravitino/assets/154112360/76fc4099-6094-4fd8-b28a-df72132ed5f1">

### Error message and/or stacktrace

N/A

### How to reproduce

N/A

**Comment by jerryshao** [comment]
@mchades can you please check this?
