### ISSUE TITLE
[EPIC] Using simple catalog name as default in Trino connector

### ISSUE THREAD

**Issue by diqiu50** [datastrato/gravitino#2947]
### Describe the proposal

Using simple catalog as default in Trino connector
Currently the table name in Trino connector like `metalake.catalogname.schemaname.tablename`. we need to remove the metalake name.

### Task list

- [x] #2948
- [x] #2949
- [x] https://github.com/datastrato/gravitino/issues/2950

**Comment by jerryshao** [comment]
Fixed.
