### ISSUE TITLE
[Question] The datastrato project support maven?

### ISSUE THREAD

**Issue by xleoken** [datastrato/gravitino#2973]
### What would you like to be improved?

It seems that `maven` is more friendly for developers, can datastrato project support maven?

**Comment by yuqi1129** [comment]
@xleoken 
Thank you for your attention. Gravitino does not currently support Maven as the compile tool. What is your use case and why do you have to use Maven? What's the background?

**Comment by xleoken** [comment]
> @xleoken Thank you for your attention. Gravitino does not currently support Maven as the compile tool. What is your use case and why do you have to use Maven? What's the background?

Hi, many popular big data related projects are built using mvn, such as Spark, Flink, Hadoop, and so on. So I am more familiar with Maven. 

Met error when build `gravitino` during the first compilation, I am trying to solve it.

./gradlew clean build -x test

```
Downloading https://mirrors.cloud.tencent.com/gradle/gradle-8.2-bin.zip
............10%............20%............30%.............40%............50%............60%............70%.............80%............90%............100%

Welcome to Gradle 8.2!

Here are the highlights of this release:
 - Kotlin DSL: new reference documentation, assignment syntax by default
 - Kotlin DSL is now the default with Gradle init
 - Improved suggestions to resolve errors in console output

For more details see https://docs.gradle.org/8.2/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* Where:
Settings file '/work/projects/opensource/dc.work/he3cloud/gravitino/settings.gradle.kts' line: 5

* What went wrong:
Plugin [id: 'org.gradle.toolchains.foojay-resolver-convention', version: '0.7.0'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'org.gradle.toolchains.foojay-resolver-convention:org.gradle.toolchains.foojay-resolver-convention.gradle.plugin:0.7.0')
  Searched in the following repositories:
    Gradle Central Plugin Repository

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 4m 24s
```

**Comment by yuqi1129** [comment]
Oh, I see,  can you please create an issue about it if you are convenient?

**Comment by xleoken** [comment]
> Oh, I see, can you please create an issue about it if you are convenient?

Thanks, I will try to solve these problems myself.

The main purpose of this issue is to suggest using mvn for compilation. 😄
