### ISSUE TITLE
[FEATURE] Gravitino python client support backward compatibility

### ISSUE THREAD

**Issue by diqiu50** [datastrato/gravitino#2988]
### Describe the feature

Gravitino python client need support backward compatibility with Gravitino server. 
Can refer to: https://github.com/datastrato/gravitino/issues/2866

**Comment by jerryshao** [comment]
@noidname01 can you please help to work on this if you have time? You can refer to Java client to understand more about this.

**Comment by noidname01** [comment]
> @noidname01 can you please help to work on this if you have time? You can refer to Java client to understand more about this.

Sure, let me take a look.
