### ISSUE TITLE
[FEATURE] Provide specific classLoader for Partition operation

### ISSUE THREAD

**Issue by TEOTEO520** [datastrato/gravitino#2997]
### Describe the feature

There is no specific catalog classLoader for partition operation, if there is a partition operation need to use Thread.currentThread().getContextClassLoader() to get classLoader, it will get WebAppClassLoader, and this will cause ClassNotFoundException
<img width="989" alt="image" src="https://github.com/datastrato/gravitino/assets/58762426/d32ae583-5e46-449a-a1f6-91d8d28c1b70">

### Describe the solution

Provide specific classLoader for Partition operation

**Comment by yuqi1129** [comment]
Can you provide more details and additional stacks?

**Comment by TEOTEO520** [comment]
Like iceberg partition operation, it will get current thread classLoader to operate 
<img width="1727" alt="image" src="https://github.com/datastrato/gravitino/assets/58762426/d90ec47b-2826-4a25-b1fa-62b1d373c408">
<img width="1404" alt="image" src="https://github.com/datastrato/gravitino/assets/58762426/891186bc-404a-4892-86ab-ae725790d2e8">

**Comment by yuqi1129** [comment]
Iceberg catalog related class are loaded by `IsolatedClassloader`, so it seems that the class loader can't be `WebAppClassLoader`.

**Comment by TEOTEO520** [comment]
@mchades also agree that the partition operation need to be separate, you can ask him for details, if community decide to do it, please assign it for me

**Comment by FANNG1** [comment]
@TEOTEO520 ,  thanks for reportings this bug, does hive work well for partition operations?

**Comment by TEOTEO520** [comment]
> @TEOTEO520 , thanks for reporting this issue, does hive work well for partition operations?

Yes, but when hive do the operation of partition, it also use WebAppClassLoader, I'm confused it does work well
<img width="1356" alt="image" src="https://github.com/datastrato/gravitino/assets/58762426/7bfdd966-be67-4a21-8c8f-60c3e7a9ce0e">
