### ISSUE TITLE
[Improvement] Rethinking the implement of partition operations

### ISSUE THREAD

**Issue by FANNG1** [datastrato/gravitino#2999]
### What would you like to be improved?

The current partition operation is out of dispatcher,  leading to some issues:
1. #2997 
2.  blocks #2873 
3.  makes event listener hard to inject to partition operations.
```java
                  Table loadTable = dispatcher.loadTable(tableIdent);
                  Partition p = loadTable.supportPartitions().getPartition(partition);
                  return Utils.ok(new PartitionResponse(DTOConverters.toDTO(p)));
```to

**Comment by FANNG1** [comment]
cc @jerryshao @mchades @yuqi1129

**Comment by jerryshao** [comment]
@mchades please take a look.

**Comment by FANNG1** [comment]
> I think it is necessary to refactor this part, we have to carefully rethink the whole thing.
> 
> BTW, I'm curious why Hive's partition operation doesn't have such problem like #2997 mentioned.

I guess Hive partition operations doesn't invoke the `DynConstructer` to load a new class.
