### ISSUE TITLE
[Improvement] Access of static fields in AuthorizationUtils.java

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#3028]
### What would you like to be improved?

1. Access of static fields should be via the class they exist in not via a subclass. Both GROUP_SCHEMA_NAME and SYSTEM_CATALOG_RESERVED_NAME are incorrectly accessed in AuthorizationUtils.java.

### How should we improve?

Use correct class when accesing GROUP_SCHEMA_NAME and SYSTEM_CATALOG_RESERVED_NAME.

**Comment by hanwxx** [comment]
i will fix it
