### ISSUE TITLE
[Improvement] Arguments should be in the in correct order: expected value, actual value.

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#3030]
### What would you like to be improved?

Only a minor issue but it can make failed test messages confusing. When calling assert equals or similar calls the order of the arguments is the expected value followed by the actual value.

### How should we improve?

Correct the following:

In CatalogsPageTest.java this occurs multiple times:
Assertions.assertEquals(driver.getTitle(), WEB_TITLE);

In MetalakePageTest.java:
 Assertions.assertEquals(driver.getTitle(), WEB_TITLE);

In TestHivePropertiesConverter.java:
Assertions.assertEquals(hiveProperties.get(HivePropertiesConstants.GRAVITINO_HIVE_FORMAT), "PARQUET");
Assertions.assertEquals(hiveProperties.get(HivePropertiesConstants.GRAVITINO_HIVE_TABLE_TYPE), HivePropertiesConstants.GRAVITINO_HIVE_EXTERNAL_TABLE);

**Comment by jerryshao** [comment]
@lw-yang can you please leave a comment here, so that I can assign this issue to you.

**Comment by lw-yang** [comment]
I've fixed it
