### ISSUE TITLE
[Improvement] Remove call to Steams.peek in HiveTableOperations.java

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#3036]
### What would you like to be improved?

According to its JavaDocs, the intermediate Stream operation java.util.Stream.peek() exists mainly to support debugging. Unexpectedly peek() may be called only for some or none of the elements in the Stream.

### How should we improve?

Replace peek call. See #1958 for a similar issue.

**Comment by xiaozcy** [comment]
This is fixed by #3046
