### ISSUE TITLE
[Improvement] Improve regexp in GravitinoVirtualFileSystem.java

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#3037]
### What would you like to be improved?

The regexp `^(?:gvfs://fileset)?/([^/]+)/([^/]+)/([^/]+)(?:[/[^/]+]*)$` can be simplified.

### How should we improve?

Improve regexp

**Comment by yijhenlin** [comment]
Hi, I would like to help this.

**Comment by yijhenlin** [comment]
I think this regexp is the simplest way for capturing three groups without '/', otherwise it will have extra works to remove '/' after matches().

**Comment by yijhenlin** [comment]
Hi @justinmclean ,
I want to make sure that your expectation is to prune the boundary symbols '^' and '$', right?

**Comment by justinmclean** [comment]
I wasn't thinking about the boundary symbols, but see if you can simplify it and not back track.

**Comment by yijhenlin** [comment]
@justinmclean 
Sorry, I get it.
Is to simplify [/[^/]+]* to .* ?
I thought it was an inaccurate use of the character class.

According to the test case, which checked the string end with '/', '/file', '/dir/' and so on.
Therefore, for more accuracy, I would modify [/[^/]+]* to (/[^/]+)*/? .
And replace the non-capturing group ?: with independent, non-capturing group (atomic group) ?> to eliminate backtracking.
