### ISSUE TITLE
[Improvement] Use a string builder rather than concatenation in DorisTableOperations.java

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#3038]
### What would you like to be improved?

Use a string builder rather than concatenation for `comment += resultSet.getString("TABLE_COMMENT");`

### How should we improve?

Use a string builder

**Comment by jerryshao** [comment]
@xiaozcy can you please leave a message here so that I can assign the issue to you.

**Comment by xiaozcy** [comment]
> @xiaozcy can you please leave a message here so that I can assign the issue to you.

sure
