### ISSUE TITLE
[Bug report] Create kafka catalog failed with message `Can't delete entity as sub-entities is not empty`

### ISSUE THREAD

**Issue by yuqi1129** [datastrato/gravitino#3061]
### Version

main branch

### Describe what's wrong

<img width="1883" alt="image" src="https://github.com/datastrato/gravitino/assets/15794564/9af4fca4-602e-4393-b225-2684ea830cd4">

### Error message and/or stacktrace

Please see above

### How to reproduce

Please see above

**Comment by mchades** [comment]
duplicated with #3015
