### ISSUE TITLE
[Subtask] Unify PostgreSQL container management with ContainerSuite

### ISSUE THREAD

**Issue by unknowntpo** [datastrato/gravitino#3066]
### Describe the subtask

Subtask of #2765 

### Parent issue

#2765

**Comment by xiaozcy** [comment]
I'd like to work on this, would you assign this to me?

**Comment by justinmclean** [comment]
@xiaozcy, someone was already working on this. Is there something else you would like to work on?

**Comment by xiaozcy** [comment]
> @xiaozcy, someone was already working on this. Is there something else you would like to work on?

@justinmclean, got it. I took a cursory look at the PR and it's exactly the same way as I thought before.
