### ISSUE TITLE
[Bug report] Local run SparkIcebergCatalogIT Failed

### ISSUE THREAD

**Issue by mchades** [datastrato/gravitino#3072]
### Version

main branch

### Describe what's wrong

Local run `SparkIcebergCatalogIT > testIcebergPartitions()` FAILED

### Error message and/or stacktrace

<img width="1859" alt="image" src="https://github.com/datastrato/gravitino/assets/24897598/acd69a7b-d458-44a3-84f8-862e4ffa5716">

### How to reproduce

Local run SparkIcebergCatalogIT

**Comment by mchades** [comment]
@FANNG1 Please help take a look at this issue when you are free, thank you.

**Comment by FANNG1** [comment]
@caican00  could you help to check this? seems cause by time zone, `hdfs://192.168.215.5:9000/user/hive/default_db/test_iceberg_hours_partition_table/data/name=a/name_trunc=a/id_bucket=4/ts_hour=2024-01-01-04` exists

**Comment by caican00** [comment]
> @caican00 could you help to check this? seems cause by time zone, `hdfs://192.168.215.5:9000/user/hive/default_db/test_iceberg_hours_partition_table/data/name=a/name_trunc=a/id_bucket=4/ts_hour=2024-01-01-04` exists

@FANNG1 Sorry for the late reply. It is indeed caused by time zone, thank you very much for fixing this issue
