### ISSUE TITLE
[Improvement] Several methods are listed as @VisibleForTesting and accessed from production code

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#3080]
### What would you like to be improved?

The following methods are @VisibleForTesting when they probably should not be:
convertFromJdbcProperties and transformToJdbcProperties in JdbcTablePropertiesMetadata.java 
formatSchemaRequestPath in BaseSchemaCatalog.java
getCatalogIdentifier in OperationDispatcher.java
generateKey in TransactionalKvBackendImpl.java
loadPropertiesFromFile and loadFromProperties in Config.java

### How should we improve?

Remove @VisibleForTesting where possible.

**Comment by JosefinaOller** [comment]
Hello, can you assign me this task, please?

**Comment by xunliu** [comment]
hi @JosefinaOller ，Thank you for your interesting Gravitino project, I assigned this issue to you, Thanks!
