### ISSUE TITLE
[Improvement] Remove this hack in BaseCatalog.java

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#3081]
### What would you like to be improved?

Remove the hack.

### How should we improve?

Improve this code and where CATALOG_OPERATION_IMPL is used:
```java
  // A hack way to inject custom operation to Gravitino, the object you used is not stable, don't
  // use it unless you know what you are doing.
  @VisibleForTesting public static final String CATALOG_OPERATION_IMPL = "ops-impl";
  ```

**Comment by noidname01** [comment]
@justinmclean Hi, I'm new here, I wanna try to work on this issue. Just to make sure my understanding is correct, I can just replace createOps(conf) with newOps(conf) to remove this hack, and modify the following tests.
