### ISSUE TITLE
[Improvement] Improve greedy regular expressions

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#3088]
### What would you like to be improved?

In DorisExceptionConverter.java we have a greedy regular expression that could potentially cause issues.
```
  private static final String DATABASE_ALREADY_EXISTS_PATTERN_STRING =
      ".*detailMessage = Can't create database '.*'; database exists";
```

### How should we improve?

Change the regular expression to not be greedy or don't use a regular expression.

**Comment by BSSsunny** [comment]
What about change it to 
private static final String DATABASE_ALREADY_EXISTS_PATTERN_STRING =
      ".*?detailMessage = Can't create database '.*?'; database exists";

**Comment by BSSsunny** [comment]
How about change it to
`private static final String DATABASE_ALREADY_EXISTS_PATTERN_STRING =
      ".*?detailMessage = Can't create database '.*?'; database exists";`

**Comment by justinmclean** [comment]
I think that sounds like a better approach. If you have time, try it out and see what needs to change.

**Comment by kiratkumar47** [comment]
Hi @justinmclean 
#3399 
This PR is ready for review.
