### ISSUE TITLE
[Improvement] The semantics of delete operation for relational storage should be aligned with kv storage

### ISSUE THREAD

**Issue by jerryshao** [datastrato/gravitino#3092]
### What would you like to be improved?

Currently, for kv storage, the delete operation will return false if the key doesn't exist. Whereas, for relational store, it will throw an `NoSuchEntityException`, we should aligh relational store with kv store.

**Comment by jerryshao** [comment]
@yuqi1129 @xloya would you please help to check this. The difference of two systems makes other modules hard to use.

**Comment by yuqi1129** [comment]
Yeah, the JDBC backend will throw `NoSuchEntityException` if the entity to be deleted does not exist, so we will make it align with the KV backend and return `false` instead.

**Comment by xloya** [comment]
I will open a PR to hot fix this problem.
