### ISSUE TITLE
[Bug report](fileset catalog) Failed to drop schema include special characters "-",while create api support to create the schema include "-"

### ISSUE THREAD

**Issue by LauraXia123** [datastrato/gravitino#3094]
### Version

main branch

### Describe what's wrong

`curl -L -X POST 'http://localhost:8090/api/metalakes/m1/catalogs/catalog/schemas' \
-H 'Content-Type: application/json' \
-H 'Accept: application/vnd.gravitino.v1+json' \
-H 'Authorization: Bearer <TOKEN>' \
--data-raw '{      
  "name": "schema_abhdbd-jnndcjdncdncd-cmjdncjdnchdc-cjdncje",
  "comment": "This is a schema",
  "properties": {}
}'  `
{"code":0,"schema":{"name":"schema_abhdbd-jnndcjdncdncd-cmjdncjdnchdc-cjdncje","comment":"This is a schema","properties":{},"audit":{"creator":"anonymous","createTime":"2024-04-22T03:42:04.501172Z"}}}%                                                  /0.0s

`curl -L -X DELETE 'http://localhost:8090/api/metalakes/m1/catalogs/catalog/schemas/schema_abhdbd-jnndcjdncdncd-cmjdncjdnchdc-cjdncje' \
-H 'Accept: application/vnd.gravitino.v1+json'`
{"code":0,"dropped":false}%  

### Error message and/or stacktrace

N/A

### How to reproduce

N/A

**Comment by jerryshao** [comment]
Fixed by #3075
