### ISSUE TITLE
[Bug report] fileset commet meet garbled data

### ISSUE THREAD

**Issue by hanwxx** [datastrato/gravitino#3165]
### Version

main branch

### Describe what's wrong

Create or update fileset comment，when inputting Chinese, the data taken out is garbled.
example:
input: 这是fileset中文描述
output: ??fileset????

### Error message and/or stacktrace

no

### How to reproduce

create fileset:
![image](https://github.com/datastrato/gravitino/assets/160711189/ad101cf7-f244-4ff9-a8de-979a5ff53949)

get fileset:
![image](https://github.com/datastrato/gravitino/assets/160711189/5ad740fe-fe27-4d16-b272-b7d9ae8fe189)

data in mysql:
![image](https://github.com/datastrato/gravitino/assets/160711189/6431a314-3001-4f11-8858-389a3937c907)

**Comment by jerryshao** [comment]
@hanwxx can you please help to fix this issue?

**Comment by xloya** [comment]
I tracked some logs, and it seems that when it was requesting the server, garbled code had appeared.
![image](https://github.com/datastrato/gravitino/assets/26177232/9fa2b397-30c3-47e2-b6a4-253672b5f6d3)
![image](https://github.com/datastrato/gravitino/assets/26177232/1787093f-2027-4796-82e6-3a55d43a9de5)

**Comment by jerryshao** [comment]
So seems like some string codec issue happens between client and server.

**Comment by xloya** [comment]
I have found the source problem, will open a PR to fix this later.
