### ISSUE TITLE
[Improvement] Gravitino UI takes 4-10 seconds to display list of catalogs

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#3244]
### What would you like to be improved?

When using the playground it can take longer than expected time to display the list catalogs, this didn't use to be the case. This occurs every time and not just the first time.

### How should we improve?

Improve the time and/or cache the list of catalogs.

**Comment by shaofengshi** [comment]
+1, the loading time is longer than expected.

**Comment by jerryshao** [comment]
I guess the problem is that UI now changes to list all the catalog info, rather than name when listing, this takes longer time than before. @mchades can yu please help to check this?

**Comment by jerryshao** [comment]
The problem I guess is due to catalog load, because we have to filter out hidden value, which needs to create all the classloader each time, this is very time consuming. @mchades can you please investigate on this to figure out a better solution.
