### ISSUE TITLE
[Bug report] When using simple names metalake names are sill displayed and this can cause issues

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#3247]
### Version

main branch

### Describe what's wrong

The metalake name are displayed and returned when they should not be

### Error message and/or stacktrace

See below

### How to reproduce

Use the playground and connect via DBeaver or other tool, you can see the names include the metalake names:
<img width="335" alt="image" src="https://github.com/datastrato/gravitino/assets/144504/5d3f3b46-cf1a-4cd2-97f0-e7b5446aa358">
And any SQL generated (e.g to view a tables data) is invalid:
<img width="1143" alt="image" src="https://github.com/datastrato/gravitino/assets/144504/7981fb23-4155-43db-b0dd-f69f682bebdb">

**Comment by diqiu50** [comment]
@justinmclean I think it's caused by  DBeaver's caching,  Could you  recreate the datasource.

**Comment by justinmclean** [comment]
Yes that looks like that is the case you can close this.
