### ISSUE TITLE
[Improvement] Adding a new Apache Kafka catalog works but times out listing topics

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#3249]
### What would you like to be improved?

If you add a Kafka catalog using the URL of a non-running Kafka server in a catalog it be added with no error. It will timeout after 30 seconds (or so) of trying to list the topics when you click on the default "sechma".

### How should we improve?

1. Verify the URL when it is entered.
2. Shorten the timeout.
3. Improve the error message displayed to the user.

**Comment by jerryshao** [comment]
@mchades would you please check and try to improve this issue.

**Comment by justinmclean** [comment]
@mchades This has been resolved and can be closed. A combination of Kafka setup and networking caused the issue.

**Comment by justinmclean** [comment]
@mchades ignore my last comment - this is still an issue.
