### ISSUE TITLE
[Improvement] assertThat should do that

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#3251]
### What would you like to be improved?

AssertThat should be followed by an assertion, however `assertThat(computeActual("select * from system.jdbc.tables"));` in TestGravitinoConnector.java and ` assertThat(computeActual("select * from system.jdbc.tables"));` in TestGravitinoConnectorWithMetalakeCatalogName.java do not.

### How should we improve?

Fix the assertions.

**Comment by ishan-gupt** [comment]
@justinmclean can you assign this to me

**Comment by rohit-satya** [comment]
@justinmclean Please review above PR
