### ISSUE TITLE
[Improvement] Test arguments shoudl be in the right order

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#3252]
### What would you like to be improved?

A minor issue, but can cause confusion, test arguments should be in the right order.

Instances are as follows:
x3 in CatalogsPageTest.java:
```
Assertions.assertEquals(driver.getTitle(), WEB_TITLE);
```

In TestHivePropertiesConverter.java:
```
Assertions.assertEquals(hiveProperties.get(HivePropertiesConstants.GRAVITINO_HIVE_FORMAT), "PARQUET");
```

### How should we improve?

Swap order of arguments.

**Comment by jerryshao** [comment]
@kristopherkane can you please leave a comment here? So we can assign this issue to you.

**Comment by kristopherkane** [comment]
PR merged for 3252.
