### ISSUE TITLE
[Bug report]  Gravitino UI when creating a new fileset catalog it seems to be missing location property

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#3257]
### Version

main branch

### Describe what's wrong

When creating a new fileset there are no properties. Is this expected?
<img width="578" alt="image" src="https://github.com/datastrato/gravitino/assets/144504/74b8afa0-e98f-4590-8745-be3695888e44">

### Error message and/or stacktrace

N/A

### How to reproduce

Using the 0.5 release, create a new fileset catalog in the Gravitino UI.

**Comment by shaofengshi** [comment]
+1; Although the location property is optional, it is better to be there for ease of use.

**Comment by LauraXia123** [comment]
@jerryshao Is the location property equate to storageLocation property of api request body?
