### ISSUE TITLE
[Bug report] With only one metalake UI presents user with a choice

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#3285]
### Version

main branch

### Describe what's wrong

It looks like you can select from multiple metalake when there is only one metalake
<img width="471" alt="image" src="https://github.com/datastrato/gravitino/assets/144504/e0bd9ec9-419b-4539-8c20-1eedba520f76">

### Error message and/or stacktrace

N/A

### How to reproduce

Start the playground and look at the demo metalake.

**Comment by shaofengshi** [comment]
Justin, what's your suggstion? disable the drow-down list if there is only one choice?

**Comment by justinmclean** [comment]
I would either a) show a single entry and no drop-down list if there is only one metalake or b) not show it at all.
