### ISSUE TITLE
[Bug report] "Alt text" for metalake name is metalake name

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#3286]
### Version

main branch

### Describe what's wrong

The text that show up when you roll over a metalake name is the metalake name. This seems redundant - perhaps the metalake comment should show instead?
<img width="326" alt="image" src="https://github.com/datastrato/gravitino/assets/144504/f35c525f-e929-4b7c-ac1d-a62d27af7bea">

Note that no text shows for the catalog names, so this is also inconsistent.

### Error message and/or stacktrace

N/A

### How to reproduce

Roll over metalake name in Gravitino UI.

**Comment by danhuawang** [comment]
<img width="1452" alt="image" src="https://github.com/datastrato/gravitino/assets/154112360/07dd40bb-7588-400d-8b25-f2d7a713dfa4">
The text that show up in the details page is also necessary
