### ISSUE TITLE
[Improvement] Refer to ASF projects by their correct names

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#3288]
### What would you like to be improved?

ASF projects need to be referred to as "Apache Foo" not just "Foo", for instance, "kafka" on this create catalog page. Also note that being a name it needs to be capitalised as "Apache Kafka".
<img width="573" alt="image" src="https://github.com/datastrato/gravitino/assets/144504/adc177df-0101-47aa-9aaf-91e0e3255714">

### How should we improve?

Refer to the projects with the full name were they are first mentioned.

**Comment by mchades** [comment]
Where are you referring to that needs to be modified? Is it 1 or 2 in the picture below?

<img width="682" alt="image" src="https://github.com/datastrato/gravitino/assets/24897598/beca335c-9338-4ebd-8c00-666df2617ad7">

**Comment by ch3yne** [comment]
My understanding is that any mention of the ASF project name needs to be changed.
