### ISSUE TITLE
[Improvement] refactor JsonUtils.objectMapper()

### ISSUE THREAD

**Issue by FANNG1** [datastrato/gravitino#3313]
### What would you like to be improved?

There are possible problems about current implement:
1.  class method conflict when the application depends both on `client-java-runtime` and `common`, this's uncommon, but exists like spark connector rely on `client-java-runtime` and run integrate test in embed mode relay on `common` module.

```
// for `common` module
  public static com.fasterxml.jackson.databind.ObjectMapper objectMapper() {
    return ObjectMapperHolder.INSTANCE;
  }

// in `client-java-runtime` module
  public static  com.datastrato.gravitino.shaded.com.fasterxml.jackson.databind.ObjectMapper objectMapper() {
    return ObjectMapperHolder.INSTANCE;
  }
```
2. use a globle static ObjectMapper which could be changed unexpectedly, it's hard to maintance.
```java
GravitinoClientBase.java
    ObjectMapper mapper = JsonUtils.objectMapper();
    mapper.disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES);
```

current implement:

```java
  private static class ObjectMapperHolder {
    private static final ObjectMapper INSTANCE =
        JsonMapper.builder()
            .configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false)
            .configure(EnumFeature.WRITE_ENUMS_TO_LOWERCASE, true)
            .enable(MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS)
            .build()
            .registerModule(new JavaTimeModule());
  }

  public static ObjectMapper objectMapper() {
    return ObjectMapperHolder.INSTANCE;
  }
```

### How should we improve?

1. move objectMapper factory from common to client and server seperately.
2. create a new objectMapper when used.

**Comment by diqiu50** [comment]
The `client-java-runtime` includes the `common` module. Why do you need both modules?

The ObjectMapper is mostly common, except for certain configurations. I believe making it a singleton is not a good idea. Creating a new object each time can help avoid mutual interference. In practice, the ObjectMapper in the common module is used only with the client or server, and they are not in the same process, except during our tests.

**Comment by yuqi1129** [comment]
> The client-java-runtime includes the common module. Why do you need both modules?

+1. The module `spark-connetor` should only depend on one of them, so maybe you need to figure out why this happens. In my opinion, if there is no clear need, using a singleton is reasonable.

**Comment by FANNG1** [comment]
@yuqi1129 @diqiu50 , spark-connector depends on `client-java-runtime` and miniGravitino server depends on `common`,  this happens when run sparkIT in embedded mode. And why current integration test not encounter this problem, because it depends on `client` also and loads `JsonUtils` from `client` module, I guess.
