### ISSUE TITLE
[Improvement] output the alter status of table into the log

### ISSUE THREAD

**Issue by zhoukangcn** [datastrato/gravitino#3326]
### What would you like to be improved?

Because alter operation in Doris table is asynchronous, we should return table's status to client.

But Gravitino has not design a API to this, so firstly we print table's status to log

**Comment by jerryshao** [comment]
@yuqi1129 you forgot to add tag and assignee for this fixed issue.

**Comment by yuqi1129** [comment]
> @yuqi1129 you forgot to add tag and assignee for this fixed issue.

My mistake, I got it.
