### ISSUE TITLE
[Bug report] Build: Unable to build gravitino in Linux environment due to JAVA problem

### ISSUE THREAD

**Issue by rich7420** [datastrato/gravitino#3336]
### Version

main branch

### Describe what's wrong

When I use "./ gradlew build" to build environment. There are some failed test. My OS is Ubuntu 22.04.4 and openJDK is 11.0.22.
By the way, the command "./gradlew build -x test" has all successful test.
![image](https://github.com/datastrato/gravitino/assets/101171023/e745ab9a-6e36-4a55-b722-a651ed4b7555)

### Error message and/or stacktrace

![image](https://github.com/datastrato/gravitino/assets/101171023/d9235c47-15ba-4c3f-9b4d-28e496105f31)
![image](https://github.com/datastrato/gravitino/assets/101171023/332f4345-cfb1-493c-b63a-38e337e1978c)
![image](https://github.com/datastrato/gravitino/assets/101171023/d4bd80f2-d6db-4b23-b3bf-7b2224c09323)

### How to reproduce

Please see Above. Thanks

### Additional context

OS：Linux gravitino 6.5.0-28-generic #29~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Apr  4 14:39:20 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
JAVA：
openjdk 11.0.22 2024-01-16
OpenJDK Runtime Environment (build 11.0.22+7-post-Ubuntu-0ubuntu222.04.1)
OpenJDK 64-Bit Server VM (build 11.0.22+7-post-Ubuntu-0ubuntu222.04.1, mixed mode, sharing)

**Comment by xunliu** [comment]
hi @rich7420 Thanks you for report this issue.
@danhuawang Please look bug?

**Comment by mchades** [comment]
Could you please follow the [how-to-test doc](https://datastrato.ai/docs/0.5.0/how-to-test) and have a try?

**Comment by yuqi1129** [comment]
I can't reproduce it locally with linux `Linux ubuntu-intel 6.7.10-orbstack-00140-g04c64cb35a2e https://github.com/datastrato/gravitino/pull/1 SMP Mon Mar 18 04:39:53 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`, maybe I need ubuntu `22.0.4` image.

**Comment by rich7420** [comment]
> Could you please follow the [how-to-test doc](https://datastrato.ai/docs/0.5.0/how-to-test) and have a try?

I've tried 
`./gradlew test -PskipITs` 
and 
```
./gradlew build -x test
./gradlew test [--rerun-tasks] -PskipTests -PtestMode=embedded
```
In the duplicate Virtual Box, There is their error message.
`./gradlew test -PskipITs` 
![image](https://github.com/datastrato/gravitino/assets/101171023/c9ce700b-1e08-4137-b84b-d284400673bb)
![image](https://github.com/datastrato/gravitino/assets/101171023/79f9bb1c-136b-426f-895e-a04fab5bebdd)
![image](https://github.com/datastrato/gravitino/assets/101171023/c5c9e25c-d685-4d97-b922-317449611116)

`./gradlew build -x test`
![image](https://github.com/datastrato/gravitino/assets/101171023/a6b131c8-cf3c-4bf6-9a0a-4b8d5445e312)

`./gradlew test [--rerun-tasks] -PskipTests -PtestMode=embedded`
![image](https://github.com/datastrato/gravitino/assets/101171023/5b3b4659-8c53-4eaa-b2bc-e695be999a16)

**Comment by yuqi1129** [comment]
This seems to be introduced by https://github.com/datastrato/gravitino/issues/3197, I tried but can't reproduce it locally in the orback virtual machine.

**Comment by jerryshao** [comment]
I don't see any valuable information in the above description. How do you know that it is due to #3197?

**Comment by yuqi1129** [comment]
![image](https://github.com/datastrato/gravitino/assets/15794564/0d4170e6-de8b-425e-93a7-244073869d88)

The error stacks contain class `com.datastrato.gravitino.integration.test.util.CloseContainerExtension`. The final outcome may not be entirely accurate, all I can say is that it's just my guess.

**Comment by mchades** [comment]
@rich7420 
I have reproduced this issue locally, possibly because you did not start the docker server before working on IT. 

You can try pulling PR #3538 and running it again to see a clearer error message.
