### ISSUE TITLE
[Subtask] [flink-connector] Support GravitinoCatalogStore to register the catalog

### ISSUE THREAD

**Issue by coolderli** [datastrato/gravitino#3362]
### Describe the subtask

Flink introduces `CatalogStore` to register catalogs in Flink. In this issue, we will implement GravitinoCatalogStore to register the catalog.

1. https://nightlies.apache.org/flink/flink-docs-release-1.18/docs/dev/table/catalogs/#catalog-store.

2. https://cwiki.apache.org/confluence/display/FLINK/FLIP-295%3A+Support+lazy+initialization+of+catalogs+and+persistence+of+catalog+configurations

### Parent issue

#1354

**Comment by jerryshao** [comment]
@FANNG1 don't forget to assign and add the correct release version tag.

**Comment by FANNG1** [comment]
> @FANNG1 don't forget to assign and add the correct release version tag.

ok
