### ISSUE TITLE
[Bug report] missing assign partitions in `CapabilityHelpers`

### ISSUE THREAD

**Issue by xiaozcy** [datastrato/gravitino#3374]
### Version

main branch

### Describe what's wrong

Refer to #3189, I believe we are missing setting assignments in `com.datastrato.gravitino.catalog.CapabilityHelpers`

### Error message and/or stacktrace

None

### How to reproduce

None

**Comment by mchades** [comment]
Can you describe in detail the relationship between assignments and capability?

**Comment by xiaozcy** [comment]
> Can you describe in detail the relationship between assignments and capability?

In `TableNormalizeDispatcher`, we use `applyCapabilities(partitions, capability)` to wrap partition info passed by request. If we don't assign partitions in `CapabilityHelpers`, the table operation dispatcher would not get assignments correctly.
![image](https://github.com/datastrato/gravitino/assets/57973980/c30a5386-e6b0-47e1-bf9b-a101b416b42b)

**Comment by mchades** [comment]
got it. Would you like to fix this?

**Comment by xiaozcy** [comment]
Sure, I'll fix it later.
