### ISSUE TITLE
[Bug report] wrong version in 0.5.0 release package

### ISSUE THREAD

**Issue by mchades** [datastrato/gravitino#3475]
### Version

main branch

### Describe what's wrong

I downloaded the 0.5.0 release package and retrieved the server version using the REST version API.
```json
{
  "code": 0,
  "version": {
    "version": "0.5.0-SNAPSHOT",
    "compileDate": "23/04/2024 17:39:38",
    "gitCommit": "ebdf514eee9fe450ef79dcb1bf22c4454f75b40a"
  }
}
```

### Error message and/or stacktrace

"version": "0.5.0-SNAPSHOT"

### How to reproduce

downloaded the 0.5.0 release package and set up server, execute `curl -L -X GET 'http://localhost:8090/api/version' \
-H 'Accept: application/vnd.gravitino.v1+json'`

### Additional context

The right version should be "version": "0.5.0".
Here are two version packages in release libs:
<img width="348" alt="image" src="https://github.com/datastrato/gravitino/assets/24897598/74b82256-48ef-41b9-b1a0-0821c657cb64">

**Comment by jerryshao** [comment]
So you mean our release package has two jars?

**Comment by mchades** [comment]
> So you mean our release package has two jars?

yes

**Comment by jerryshao** [comment]
This is already fixed.
