### ISSUE TITLE
[Bug report] Font license not compatible with the Apache license

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#3593]
### Version

main branch

### Describe what's wrong

A font has been added to the Web UI and it license is not Category A.
"Third party SIL Open Font License v1.1 (OFL-1.1)
   (SIL OPEN FONT LICENSE Version 1.1) The Alata font family (https://github.com/SorkinType/Alata)"

### Error message and/or stacktrace

N/A but see https://www.apache.org/legal/resolved.html

### How to reproduce

N/A

### Additional context

font will need to be replaced with one that has a compatible license

**Comment by justinmclean** [comment]
Note that some other Google fonts are under the Apache license which would be suitable e.g. https://fonts.google.com/specimen/Roboto/about

**Comment by LauraXia123** [comment]
I can replace the fonts
