### ISSUE TITLE
[Subtask] Fix invalid-field-call Pylint rule for client-python

### ISSUE THREAD

**Issue by noidname01** [datastrato/gravitino#3769]
### Describe the subtask

* Currently the `field` function is used in several non-dataclass class, please try to read the source code and determine whether change the class to dataclass or just remove the `field` function.

### Parent issue

#3560

**Comment by jerryshao** [comment]
@featherchen can you please leave a comment here, so that I can assign the issue to you.

**Comment by featherchen** [comment]
> @featherchen can you please leave a comment here, so that I can assign the issue to you.

Sure, Thanks for the help.
