### ISSUE TITLE
[Subtask] Fix protected-access Pylint rule for client-python

### ISSUE THREAD

**Issue by noidname01** [datastrato/gravitino#3770]
### Describe the subtask

* Sometimes our code directly access the protected member in class, please modify the code to access those member by using getter function.

### Parent issue

#3560

**Comment by featherchen** [comment]
The problem is the access behavior in these classes, I will fix it soon.
![Screenshot from 2024-06-06 14-10-04](https://github.com/datastrato/gravitino/assets/57944334/5ef4eb25-5838-4226-ac41-58271236562c)
