### ISSUE TITLE
[Improvement] Support generating pydoc from client-python code

### ISSUE THREAD

**Issue by jerryshao** [datastrato/gravitino#3824]
### What would you like to be improved?

We would like to generate pydoc from client-python code, and can be deployed on to the website.

### How should we improve?

Add gradle build command to support generating pydoc from code.

**Comment by noidname01** [comment]
Hi @jerryshao, I would like to work on this. Can you assign this issue to me?

**Comment by jerryshao** [comment]
Sure, no problem.
