### ISSUE TITLE
[Bug report] Execution failed for task ':clients:client-python:miniforgeSetup'

### ISSUE THREAD

**Issue by prosscode** [datastrato/gravitino#3893]
### Version

main branch

### Describe what's wrong

Following the Quick start to execute the build command, this problem occurs.

my mac environment is jdk11 and th Gradle 8.2, looks like this file `Miniforge3-MacOSX-x86_64.sh` downloaded automatically.

### Error message and/or stacktrace

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':clients:client-python:miniforgeSetup'.
Process 'command '/gravitino/.gradle/python/MacOSX/Miniforge3/Miniforge3-MacOSX-x86_64.sh'' finished with non-zero exit value 1

<img width="1668" alt="image" src="https://github.com/datastrato/gravitino/assets/26180481/300bd0ee-a47a-463d-8637-30bfe6cbacc4">

<img width="419" alt="image" src="https://github.com/datastrato/gravitino/assets/26180481/fe4a7645-b9e0-40a2-81d7-f0a7b062b1b9">

### How to reproduce

`./gradlew clean`

`./gradlew clean build -x test`

**Comment by jerryshao** [comment]
@xunliu can you please help to check this?

**Comment by prosscode** [comment]
It could be an environmental compatibility issue. Look at these issues:
https://github.com/conda-forge/miniforge/issues/307
https://github.com/conda-forge/miniforge/issues/255

**Comment by prosscode** [comment]
Need to make sure that `conda-forge` is in the configuration of the channel. The file `.condarc` should look like

```
channels:
  - conda-forge
  - defaults
```

and then build the python module and it will work.
