### ISSUE TITLE
[Improvement] Improve the thrown exception in EntityStore

### ISSUE THREAD

**Issue by jerryshao** [datastrato/gravitino#3976]
### What would you like to be improved?

Currently, there're several misuse of exception in entity store.

<img width="866" alt="image" src="https://github.com/datastrato/gravitino/assets/850797/06d020d8-9e34-42e8-9a86-a68591c7f817">

In `put` method, we use `EntityAlreadyExistsException` but in `update` we use `AlreadyExistsException`, we should unify to use `EntityAlreadyExistsException`.

in relation storage backend.

<img width="713" alt="image" src="https://github.com/datastrato/gravitino/assets/850797/632670c4-70ee-49b7-940e-cb4c8852320c">

<img width="697" alt="image" src="https://github.com/datastrato/gravitino/assets/850797/31b19481-b445-48f3-a095-3b419bbf2c5a">

1. We also use `AlreadyExistsException`, this should be changed to `EntityAlreadyExistsException`, otherwise this exception will be leaked.
2. Instead of using `GravitinoRuntimeException`, we should use `IOException` instead to avoid exception leakage and conform to the interface definition.

**Comment by jerryshao** [comment]
@yuqi1129 @xloya please take a look when you have time.

**Comment by xloya** [comment]
@yuqi1129 Would you work on this issue?

**Comment by yuqi1129** [comment]
Yeah, I would like to do it.

**Comment by yuqi1129** [comment]
@xloya As I may start this next week, if you plan to work on it, please let me know. Thanks.

**Comment by xloya** [comment]
@yuqi1129 Sure, I'd like to do this today.
