### ISSUE TITLE
[EPIC] Authentication for Graviton

### ISSUE THREAD

**Issue by xunliu** [datastrato/gravitino#413]
### Describe the proposal

Graviton supports enterprise-grade authentication and authentication to protect user access and data security.
I think it is very important that we provide this going forward:
1. User login and logout
2. User Token management, assignment, and destruction of user token with expiration date
3. Saving of user information to Backend storage when a user operates Graviton
4. Support enterprise-grade authentication methods, such as `OSS` or `Kerberos` and others.
5. Graviton can use user information to authenticate with third-party systems, like., Hadoop, Hive, Mysql, and more.
6. Waiting to add more descriptions ...

### Task list

- [x] #414 
- [x] #737 
- [x] #704 
- [x] #776

**Comment by jerryshao** [comment]
I'm going to close this, can you please create a new EPIC issue to track all the user system and other things? @qqqttt123

**Comment by qqqttt123** [comment]
> I'm going to close this, can you please create a new EPIC issue to track all the user system and other things? @qqqttt123

OK.
