### ISSUE TITLE
[EPIC] Handle case sensitive problem in Graviton

### ISSUE THREAD

**Issue by yuqi1129** [datastrato/gravitino#423]
### Describe the proposal

As we have just reach the point that we would go with underlying storage information if there is a conflict between the information in underlying storage and that stored in graviton. Name Identifiers should follow this principle. For example, users create a table name 'A' through Graviton and the underlying storage is case-insensitive. The real name in the underlying storage is 'a', so we must use 'a' as the table name in Graviton.

### Survey
- https://docs.google.com/document/d/1PS5l9PEE2wMRp7caez1jt7eIMW_bhDu37GrOuA6_d9E/edit#heading=h.60ech7sdv58d

**Comment by mchades** [comment]
resolved by #2975
