### ISSUE TITLE
[Improvement] Simply method `listSchemas` in interface `SupportsSchemas` 

### ISSUE THREAD

**Issue by yuqi1129** [datastrato/gravitino#553]
### What would you like to be improved?

As any implementation of `SupportsSchemas` contains catalog entity informations, there is not need to pass name space information to method `SupportsSchemas` because catalog entity already holds it, so I propose if we can simplify this method signature.

**Comment by SteNicholas** [comment]
@yuqi1129,  the  param `namespace` of `listSchemas` in interface `SupportsSchemas` is a sequence of levels separated by dots, what's do you mean `there is not need to pass name space information`?

**Comment by yuqi1129** [comment]
> @yuqi1129, the param `namespace` of `listSchemas` in interface `SupportsSchemas` is a sequence of levels separated by dots, what's do you mean `there is not need to pass name space information`?

I mean we do not need to pass the namespace information in the method `listSchemas` because the implementation has contains this information. 

For example, the `namespace` implementation `HiveCatalogOperations` contains `metalake_name.catalog_name`, we also
holds the information needed for listing all the schemas in this catalog.

**Comment by shaofengshi** [comment]
I'm working on this. Plan to change the method signature to:

`  NameIdentifier[] listSchemas() throws NoSuchCatalogException;`

Another option is:

`  String[] listSchemas() throws NoSuchCatalogException;`

What do you think? @yuqi1129

**Comment by yuqi1129** [comment]
> I'm working on this. Plan to change the method signature to:
> 
> ` NameIdentifier[] listSchemas() throws NoSuchCatalogException;`
> 
> Another option is:
> 
> ` String[] listSchemas() throws NoSuchCatalogException;`
> 
> What do you think? @yuqi1129

Agreed, the former seems to be better.

**Comment by shaofengshi** [comment]
Close this issue as it has been finished.
