### ISSUE TITLE
[Improvement] Dependencies follow the alphabet order

### ISSUE THREAD

**Issue by qqqttt123** [datastrato/gravitino#738]
### What would you like to be improved?

Dependencies follow the alphabet order

**Comment by hiirrxnn** [comment]
In which file/files should I sort the dependencies?

**Comment by yuqi1129** [comment]
@qqqttt123 
Could you help to clarify it?

**Comment by hiirrxnn** [comment]
Is it a specific build.gradle.kts file or all ? Also , just the "implementation(xx)" ones or the "exclude(xx)" ones too ?

**Comment by qqqttt123** [comment]
> Is it a specific build.gradle.kts file or all ? Also , just the "implementation(xx)" ones or the "exclude(xx)" ones too ?

All build.gradle.kts.

**Comment by justinmclean** [comment]
@hiirrxnn how are you going with this? Do you need any help?
