### ISSUE TITLE
[Improvement] Reduce Iceberg's test class files

### ISSUE THREAD

**Issue by xunliu** [datastrato/gravitino#740]
### What would you like to be improved?

There are 3 test classes (IcebergRESTHiveCatalogIT, IcebergRESTJdbcCatalogIT , IcebergRESTServiceBaseIT) in Gravitino [Iceberg IT Test Cases](https://github.com/datastrato/gravitino/tree/main/integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/lakehouse/iceberg), and only the `catalogType` value is initialization is different.

@FANNG1  Can we use the `ParameterizedTest` annotation to combine them into one test case using different initialization parameters?

### How should we improve?

In JUnit, if you want to test class variables with different parameters, you can use the `@ParameterizedTest` annotation combined with annotations such as `@CsvSource`, `@ValueSource`, `@EnumSource`, etc.

Here is an example demonstrating how to test class variables with different parameters:

```java
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class ParameterizedTestExample {

    private int value;

    public ParameterizedTestExample(int value) {
        this.value = value;
    }

    @ParameterizedTest
    @CsvSource({"1", "2", "3"})
    void testWithCsvSource(int argument) {
        assertEquals(value + argument, value + argument);
    }
}
```

In this example, we define a `ParameterizedTestExample` class and receive a `value` parameter in the constructor. Then, we use the `@ParameterizedTest` annotation and the `@CsvSource` annotation to specify parameterized testing, where the `@CsvSource` annotation provides multiple parameters.

When you run this test, JUnit will execute the `testWithCsvSource` method multiple times with different parameter values for each test.

Using this approach, you can test class variables with different parameters to validate the behavior of the class under different parameter values.

**Comment by FANNG1** [comment]
I prefer to close this issue, because:
1.  junit5 doesn't support `class level ParameterizedTest`,  https://github.com/junit-team/junit5/issues/878 .  There'are some other ways to implement it, like https://github.com/apache/iceberg/pull/9161,  it's complicated and not worth for us for now.
2. Hive and Jdbc catalog test should tagged with `gravitino-docker-it` while `memorycatalog` should run without the tag.

**Comment by FANNG1** [comment]
@xunliu  what do you think?
