### ISSUE TITLE
[Improvement] Setting the workflow depends

### ISSUE THREAD

**Issue by xunliu** [datastrato/gravitino#768]
### What would you like to be improved?

Currently, `build.yml` and `integration-test.yml` execute out of order.
Integration tests should be performed after the build is successful

### How should we improve?

Setting the workflow depends:
1. First, execute `build.yml`,
2. When build workflow successed in the Github Action then execute Integration Test workflow.

**Comment by jerryshao** [comment]
Besides, I think the performance of the  CI machine is too bad, not sure if we can set up a CI by our own, using AWS EC2 or others to build a CI machine, I'm not sure if the price is lower or higher than the github CI.

**Comment by qqqttt123** [comment]
After discussion, this optimization is useless.
